### ISSUE TITLE
When loading many races concurrently, much CPU seems to be wasted on periodic recalculations

### ISSUE THREAD

**Issue by aksajhfduwafe** [aksajhfduwafe/bugzilla-to-github-issues-test#1171]
| Field | Value |
|---|---|
| **Reporter** | @axeluhl |
| **Assignee** | @axeluhl |
| **Product** | Sailing Race Analytics |
| **Component** | Server |
| **Version** | unspecified |
| **Hardware** | All |
| **OS** | All |
| **Severity** | major |
| **Priority** | P2 |
| **CC (unmapped)** | Simon Pamies (`s.pamies@the-placeholder-company.com`) |
| **Created** | 2013-01-24T23:05:36Z |
| **Original Bug** | [Bug 1171](https://bugzilla.sapsailing.com/bugzilla/show_bug.cgi?id=1171) |

---

I tried to load many races concurrently into our prod2 instance. The instance got slower and slower. It seems from the logs that I'll attach in a minute that the virtual wind tracks for the wind estimation are re-computed over and over again for each fix downloaded from TracTrac which causes so much CPU waste that all eight cores run at 100% all the time and loading of the tracks is terribly slow. This, in turn, causes some locks to take very long to release.

We should probably, as has been suggested before, consider switching off any re-calculations of cached values while *loading* a race (as opposed to live-tracking a race). This would require distinguishing different status of a race during loading / tracking.

Jan 24, 2013 10:33:43 PM com.sap.sailing.util.impl.LockUtil lock
INFO: Couldn't acquire lock writeLock lock for CourseImpl 49er Yellow - Race 6-H L3 in 5s at java.lang.Thread.getStackTrace(Thread.java:1567)
com.sap.sailing.util.impl.LockUtil.getStackTrace(LockUtil.java:107)
com.sap.sailing.util.impl.LockUtil.getCurrentStackTrace(LockUtil.java:115)
com.sap.sailing.util.impl.LockUtil.lock(LockUtil.java:39)
com.sap.sailing.util.impl.LockUtil.lockForWrite(LockUtil.java:80)
com.sap.sailing.domain.base.impl.CourseImpl.update(CourseImpl.java:368)
com.sap.sailing.domain.tractracadapter.impl.DomainFactoryImpl.updateCourseWaypoints(DomainFactoryImpl.java:138)
com.sap.sailing.domain.tractracadapter.impl.RaceCourseReceiver.handleEvent(RaceCourseReceiver.java:96)
com.sap.sailing.domain.tractracadapter.impl.AbstractReceiverWithQueue.run(AbstractReceiverWithQueue.java:118)
java.lang.Thread.run(Thread.java:722)

The current readers are:
Thread[TrackBasedEstimationWindTrackImpl cache invalidation timer for race 49er Yellow - Race 6,5,main]
java.util.logging.StreamHandler.publish(StreamHandler.java:191)
java.util.logging.ConsoleHandler.publish(ConsoleHandler.java:105)
java.util.logging.Logger.log(Logger.java:522)
java.util.logging.Logger.doLog(Logger.java:543)
java.util.logging.Logger.log(Logger.java:566)
java.util.logging.Logger.info(Logger.java:1085)
com.sap.sailing.util.impl.LockUtil.lock(LockUtil.java:50)
com.sap.sailing.util.impl.LockUtil.lockForRead(LockUtil.java:72)
com.sap.sailing.domain.tracking.impl.DynamicTrackedRaceImpl.lockForRead(DynamicTrackedRaceImpl.java:464)
com.sap.sailing.domain.tracking.impl.TrackedRaceImpl.getTrackedLeg(TrackedRaceImpl.java:733)
com.sap.sailing.domain.tracking.impl.TrackedRaceImpl.clusterBearingsByLegType(TrackedRaceImpl.java:1595)
com.sap.sailing.domain.tracking.impl.TrackedRaceImpl.getEstimatedWindDirectionWithConfidence(TrackedRaceImpl.java:1527)
com.sap.sailing.domain.tracking.impl.TrackBasedEstimationWindTrackImpl.refreshCacheIncrementally(TrackBasedEstimationWindTrackImpl.java:359)
com.sap.sailing.domain.tracking.impl.TrackBasedEstimationWindTrackImpl.access$2(TrackBasedEstimationWindTrackImpl.java:319)
com.sap.sailing.domain.tracking.impl.TrackBasedEstimationWindTrackImpl$2.run(TrackBasedEstimationWindTrackImpl.java:400)
java.util.TimerThread.mainLoop(Timer.java:555)
java.util.TimerThread.run(Timer.java:505)
Trying again...
Jan 24, 2013 10:33:43 PM com.sap.sailing.util.impl.LockUtil unlockAfterWrite
INFO: write lock mark passings lock for [] was held for more than 10s. It got unlocked here: java.lang.Thread.getStackTrace(Thread.java:1567)
com.sap.sailing.util.impl.LockUtil.getStackTrace(LockUtil.java:107)
com.sap.sailing.util.impl.LockUtil.getCurrentStackTrace(LockUtil.java:115)
com.sap.sailing.util.impl.LockUtil.unlockAfterWrite(LockUtil.java:98)
com.sap.sailing.domain.tracking.impl.DynamicTrackedRaceImpl.updateMarkPassings(DynamicTrackedRaceImpl.java:429)
com.sap.sailing.domain.tractracadapter.impl.MarkPassingReceiver.handleEvent(MarkPassingReceiver.java:97)
com.sap.sailing.domain.tractracadapter.impl.AbstractReceiverWithQueue.run(AbstractReceiverWithQueue.java:118)
java.lang.Thread.run(Thread.java:722)

Jan 24, 2013 10:33:44 PM com.sap.sailing.util.impl.LockUtil lock
INFO: Couldn't acquire lock readLock VirtualWindTrackImpl for race 49er Gold - Race 10 in 5s at java.lang.Thread.getStackTrace(Thread.java:1567)
com.sap.sailing.util.impl.LockUtil.getStackTrace(LockUtil.java:107)
com.sap.sailing.util.impl.LockUtil.getCurrentStackTrace(LockUtil.java:115)
com.sap.sailing.util.impl.LockUtil.lock(LockUtil.java:39)
com.sap.sailing.util.impl.LockUtil.lockForRead(LockUtil.java:72)
com.sap.sailing.domain.tracking.impl.TrackImpl.lockForRead(TrackImpl.java:66)
com.sap.sailing.domain.tracking.impl.TrackBasedEstimationWindTrackImpl.getAveragedWindUnsynchronized(TrackBasedEstimationWindTrackImpl.java:557)
com.sap.sailing.domain.tracking.impl.VirtualWindTrackImpl.getAveragedWindWithConfidence(VirtualWindTrackImpl.java:84)
com.sap.sailing.domain.tracking.impl.TrackedRaceImpl.getWindWithConfidence(TrackedRaceImpl.java:1172)
com.sap.sailing.domain.tracking.impl.TrackedRaceImpl.getWind(TrackedRaceImpl.java:1127)
com.sap.sailing.domain.tracking.impl.TrackedRaceImpl.getWind(TrackedRaceImpl.java:1122)
com.sap.sailing.domain.tracking.impl.TrackedRaceImpl.getTack(TrackedRaceImpl.java:1722)
com.sap.sailing.domain.tracking.impl.TrackedRaceImpl.createManeuverFromGroupOfCourseChanges(TrackedRaceImpl.java:1981)
com.sap.sailing.domain.tracking.impl.TrackedRaceImpl.groupChangesInSameDirectionIntoManeuvers(TrackedRaceImpl.java:1961)
com.sap.sailing.domain.tracking.impl.TrackedRaceImpl.detectManeuvers(TrackedRaceImpl.java:1842)
com.sap.sailing.domain.tracking.impl.TrackedRaceImpl.computeManeuvers(TrackedRaceImpl.java:1788)
com.sap.sailing.domain.tracking.impl.TrackedRaceImpl.access$4(TrackedRaceImpl.java:1756)
com.sap.sailing.domain.tracking.impl.TrackedRaceImpl$2.computeCacheUpdate(TrackedRaceImpl.java:374)
com.sap.sailing.domain.tracking.impl.TrackedRaceImpl$2.computeCacheUpdate(TrackedRaceImpl.java:1)
com.sap.sailing.util.impl.SmartFutureCache$1.call(SmartFutureCache.java:213)
java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334)
java.util.concurrent.FutureTask.run(FutureTask.java:166)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603)
java.lang.Thread.run(Thread.java:722)
The current writer is:
Thread[com.sap.sailing.domain.tractracadapter.impl.MarkPassingReceiver,5,main]
java.lang.Thread.setPriority0(Native Method)
java.lang.Thread.setPriority(Thread.java:1108)
java.lang.Thread.init(Thread.java:399)
java.lang.Thread.<init>(Thread.java:430)
java.util.TimerThread.<init>(Timer.java:499)
java.util.Timer.<init>(Timer.java:101)
com.sap.sailing.domain.tracking.impl.TrackBasedEstimationWindTrackImpl.startSchedulerForCacheRefresh(TrackBasedEstimationWindTrackImpl.java:393)
com.sap.sailing.domain.tracking.impl.TrackBasedEstimationWindTrackImpl.scheduleCacheRefresh(TrackBasedEstimationWindTrackImpl.java:269)
com.sap.sailing.domain.tracking.impl.TrackBasedEstimationWindTrackImpl.markPassingReceived(TrackBasedEstimationWindTrackImpl.java:526)
com.sap.sailing.domain.tracking.impl.DynamicTrackedRaceImpl.notifyListeners(DynamicTrackedRaceImpl.java:369)
com.sap.sailing.domain.tracking.impl.DynamicTrackedRaceImpl.updateMarkPassings(DynamicTrackedRaceImpl.java:454)
com.sap.sailing.domain.tractracadapter.impl.MarkPassingReceiver.handleEvent(MarkPassingReceiver.java:97)
com.sap.sailing.domain.tractracadapter.impl.AbstractReceiverWithQueue.run(AbstractReceiverWithQueue.java:118)
java.lang.Thread.run(Thread.java:722)

The current readers are:
Trying again...
Jan 24, 2013 10:33:44 PM com.sap.sailing.util.impl.LockUtil lock
INFO: Couldn't acquire lock readLock VirtualWindTrackImpl for race 470 W  - Race 3 in 5s at java.lang.Thread.getStackTrace(Thread.java:1567)
com.sap.sailing.util.impl.LockUtil.getStackTrace(LockUtil.java:107)
com.sap.sailing.util.impl.LockUtil.getCurrentStackTrace(LockUtil.java:115)
com.sap.sailing.util.impl.LockUtil.lock(LockUtil.java:39)
com.sap.sailing.util.impl.LockUtil.lockForRead(LockUtil.java:72)
com.sap.sailing.domain.tracking.impl.TrackImpl.lockForRead(TrackImpl.java:66)
com.sap.sailing.domain.tracking.impl.TrackBasedEstimationWindTrackImpl.getAveragedWindUnsynchronized(TrackBasedEstimationWindTrackImpl.java:557)
com.sap.sailing.domain.tracking.impl.VirtualWindTrackImpl.getAveragedWindWithConfidence(VirtualWindTrackImpl.java:84)
com.sap.sailing.domain.tracking.impl.TrackedRaceImpl.getWindWithConfidence(TrackedRaceImpl.java:1172)
com.sap.sailing.domain.tracking.impl.TrackedRaceImpl.getWind(TrackedRaceImpl.java:1127)
com.sap.sailing.domain.tracking.impl.TrackedRaceImpl.getWind(TrackedRaceImpl.java:1122)
com.sap.sailing.domain.tracking.impl.TrackedRaceImpl.getTack(TrackedRaceImpl.java:1722)
com.sap.sailing.domain.tracking.impl.TrackedRaceImpl.createManeuverFromGroupOfCourseChanges(TrackedRaceImpl.java:1981)
com.sap.sailing.domain.tracking.impl.TrackedRaceImpl.groupChangesInSameDirectionIntoManeuvers(TrackedRaceImpl.java:1944)
com.sap.sailing.domain.tracking.impl.TrackedRaceImpl.detectManeuvers(TrackedRaceImpl.java:1842)
com.sap.sailing.domain.tracking.impl.TrackedRaceImpl.computeManeuvers(TrackedRaceImpl.java:1788)
com.sap.sailing.domain.tracking.impl.TrackedRaceImpl.access$4(TrackedRaceImpl.java:1756)
com.sap.sailing.domain.tracking.impl.TrackedRaceImpl$2.computeCacheUpdate(TrackedRaceImpl.java:374)
com.sap.sailing.domain.tracking.impl.TrackedRaceImpl$2.computeCacheUpdate(TrackedRaceImpl.java:1)
com.sap.sailing.util.impl.SmartFutureCache$1.call(SmartFutureCache.java:213)
java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334)
java.util.concurrent.FutureTask.run(FutureTask.java:166)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603)
java.lang.Thread.run(Thread.java:722)

The current writer is:
Thread[com.sap.sailing.domain.tractracadapter.impl.MarkPassingReceiver,5,main]
java.lang.Thread.setPriority0(Native Method)
java.lang.Thread.setPriority(Thread.java:1108)
java.lang.Thread.init(Thread.java:399)
java.lang.Thread.<init>(Thread.java:430)
java.util.TimerThread.<init>(Timer.java:499)
java.util.Timer.<init>(Timer.java:101)
com.sap.sailing.domain.tracking.impl.TrackBasedEstimationWindTrackImpl.startSchedulerForCacheRefresh(TrackBasedEstimationWindTrackImpl.java:393)
com.sap.sailing.domain.tracking.impl.TrackBasedEstimationWindTrackImpl.scheduleCacheRefresh(TrackBasedEstimationWindTrackImpl.java:269)
com.sap.sailing.domain.tracking.impl.TrackBasedEstimationWindTrackImpl.markPassingReceived(TrackBasedEstimationWindTrackImpl.java:526)
com.sap.sailing.domain.tracking.impl.DynamicTrackedRaceImpl.notifyListeners(DynamicTrackedRaceImpl.java:369)
com.sap.sailing.domain.tracking.impl.DynamicTrackedRaceImpl.updateMarkPassings(DynamicTrackedRaceImpl.java:454)
com.sap.sailing.domain.tractracadapter.impl.MarkPassingReceiver.handleEvent(MarkPassingReceiver.java:97)
com.sap.sailing.domain.tractracadapter.impl.AbstractReceiverWithQueue.run(AbstractReceiverWithQueue.java:118)
java.lang.Thread.run(Thread.java:722)

The current readers are:
Trying again...

**Comment by aksajhfduwafe** [comment]
*@axeluhl* changed status from **NEW** to **RESOLVED** (FIXED)
