### ISSUE TITLE
Trying to open a Column in the Leaderboard Page, getting a 'Uncought Exception'.

### ISSUE THREAD

**Issue by aksajhfduwafe** [aksajhfduwafe/bugzilla-to-github-issues-test#1174]
| Field | Value |
|---|---|
| **Reporter** | Marcus Kammer (`marcus.kammer@sap.com`) |
| **Assignee** | @axeluhl |
| **Product** | Sailing Race Analytics |
| **Component** | Leaderboard |
| **Version** | unspecified |
| **Hardware** | Macintosh |
| **OS** | Mac OS |
| **Severity** | normal |
| **Priority** | P3 |
| **Created** | 2013-01-25T17:02:55Z |
| **Original Bug** | [Bug 1174](https://bugzilla.sapsailing.com/bugzilla/show_bug.cgi?id=1174) |

---

Trying to open a Column in the Leaderboard Page, getting a 'Uncought Exception'.
Master Branch, commit 5c5c4b2b161244942fed502620dc5d3a6a12ec94

**Comment by aksajhfduwafe** [comment]
**Marcus Kammer (`marcus.kammer@sap.com`)** commented:

17:00:07.100 [ERROR] [com.sap.sailing.gwt.ui.Leaderboard] Uncaught exception escaped

java.lang.AssertionError: null
    at com.google.gwt.dom.client.DivElement$.as(DivElement.java:33)
    at com.sap.sailing.gwt.ui.leaderboard.SortableExpandableColumnHeader$4.onBrowserEvent(SortableExpandableColumnHeader.java:144)
    at com.sap.sailing.gwt.ui.leaderboard.SortableExpandableColumnHeader$4.onBrowserEvent(SortableExpandableColumnHeader.java:1)
    at com.google.gwt.user.cellview.client.Header.onBrowserEvent(Header.java:92)
    at com.google.gwt.user.cellview.client.AbstractCellTable.onBrowserEvent2(AbstractCellTable.java:1888)
    at com.google.gwt.user.cellview.client.AbstractHasData.onBrowserEvent(AbstractHasData.java:739)
    at com.google.gwt.user.client.DOM.dispatchEventImpl(DOM.java:1351)
    at com.google.gwt.user.client.DOM.dispatchEvent(DOM.java:1307)
    at sun.reflect.GeneratedMethodAccessor75.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at com.google.gwt.dev.shell.MethodAdaptor.invoke(MethodAdaptor.java:103)
    at com.google.gwt.dev.shell.MethodDispatch.invoke(MethodDispatch.java:71)
    at com.google.gwt.dev.shell.OophmSessionHandler.invoke(OophmSessionHandler.java:172)
    at com.google.gwt.dev.shell.BrowserChannelServer.reactToMessagesWhileWaitingForReturn(BrowserChannelServer.java:338)
    at com.google.gwt.dev.shell.BrowserChannelServer.invokeJavascript(BrowserChannelServer.java:219)
    at com.google.gwt.dev.shell.ModuleSpaceOOPHM.doInvoke(ModuleSpaceOOPHM.java:136)
    at com.google.gwt.dev.shell.ModuleSpace.invokeNative(ModuleSpace.java:571)
    at com.google.gwt.dev.shell.ModuleSpace.invokeNativeObject(ModuleSpace.java:279)
    at com.google.gwt.dev.shell.JavaScriptHost.invokeNativeObject(JavaScriptHost.java:91)
    at com.google.gwt.core.client.impl.Impl.apply(Impl.java)
    at com.google.gwt.core.client.impl.Impl.entry0(Impl.java:242)
    at sun.reflect.GeneratedMethodAccessor73.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at com.google.gwt.dev.shell.MethodAdaptor.invoke(MethodAdaptor.java:103)
    at com.google.gwt.dev.shell.MethodDispatch.invoke(MethodDispatch.java:71)
    at com.google.gwt.dev.shell.OophmSessionHandler.invoke(OophmSessionHandler.java:172)
    at com.google.gwt.dev.shell.BrowserChannelServer.reactToMessages(BrowserChannelServer.java:293)
    at com.google.gwt.dev.shell.BrowserChannelServer.processConnection(BrowserChannelServer.java:547)
    at com.google.gwt.dev.shell.BrowserChannelServer.run(BrowserChannelServer.java:364)
    at java.lang.Thread.run(Thread.java:680)

**Comment by aksajhfduwafe** [comment]
**@axeluhl** commented:

Can you please specify the leaderboard and race you were trying to use?

**Comment by aksajhfduwafe** [comment]
**@axeluhl** commented:

The default leaderboard is not supported except for debugging purposes. If you have loaded many races from different boat classes in your server instance, the default leaderboard's behavior is undefined.

Can you reproduce the issue with a leaderboard that only has the 29er races of the Kieler Woche 2012?

**Comment by aksajhfduwafe** [comment]
**Marcus Kammer (`marcus.kammer@sap.com`)** commented:

The issue can be reproduced with a new Leaderboard that only has the 29er races of the Kieler Woche 2012.

**Comment by aksajhfduwafe** [comment]
**@axeluhl** commented:

Fixed with commit c9326e26e495de36e48945cbb770d27f1fe5eb87.

**Comment by aksajhfduwafe** [comment]
**@LennartH** commented:

Removed the work around for the click handling of SortableExpandableColumnHeaders. This isn't needed anymore with GWT 2.5.
Done with commit d53aec5a27243e7fac2f2922622dde86ff3a6570
