### ISSUE TITLE
Deadlock during attempt to obtain write lock for course update

### ISSUE THREAD

**Issue by aksajhfduwafe** [aksajhfduwafe/bugzilla-to-github-issues-test#1313]
| Field | Value |
|---|---|
| **Reporter** | @axeluhl |
| **Assignee** | @axeluhl |
| **Product** | Sailing Race Analytics |
| **Component** | Server |
| **Version** | unspecified |
| **Hardware** | All |
| **OS** | All |
| **Severity** | normal |
| **Priority** | P1 |
| **Created** | 2013-03-21T16:13:58Z |
| **Original Bug** | [Bug 1313](https://bugzilla.sapsailing.com/bugzilla/show_bug.cgi?id=1313) |

---

Writer:

com.sap.sailing.util.impl.LockUtil.getStackTrace(LockUtil.java:105)
com.sap.sailing.util.impl.LockUtil.getCurrentStackTrace(LockUtil.java:113)
com.sap.sailing.util.impl.LockUtil.lock(LockUtil.java:37)
com.sap.sailing.util.impl.LockUtil.lockForWrite(LockUtil.java:78)
com.sap.sailing.domain.base.impl.CourseImpl.update(CourseImpl.java:370)
com.sap.sailing.domain.swisstimingadapter.impl.DomainFactoryImpl.updateCourseWaypoints(DomainFactoryImpl.java:279)
com.sap.sailing.domain.swisstimingadapter.impl.SwissTimingRaceTrackerImpl.receivedCourseConfiguration(SwissTimingRaceTrackerImpl.java:331)
com.sap.sailing.domain.swisstimingadapter.impl.SailMasterConnectorImpl.notifyListenersCCG(SailMasterConnectorImpl.java:395)
com.sap.sailing.domain.swisstimingadapter.impl.SailMasterConnectorImpl.notifyListeners(SailMasterConnectorImpl.java:316)
com.sap.sailing.domain.swisstimingadapter.impl.SailMasterConnectorImpl.trackRace(SailMasterConnectorImpl.java:180)
com.sap.sailing.domain.swisstimingadapter.impl.SwissTimingRaceTrackerImpl.<init>(SwissTimingRaceTrackerImpl.java:100)
com.sap.sailing.domain.swisstimingadapter.impl.SwissTimingRaceTrackerImpl.<init>(SwissTimingRaceTrackerImpl.java:82)
com.sap.sailing.domain.swisstimingadapter.impl.SwissTimingFactoryImpl.createRaceTracker(SwissTimingFactoryImpl.java:87)
com.sap.sailing.domain.swisstimingadapter.impl.SwissTimingTrackingConnectivityParameters.createRaceTracker(SwissTimingTrackingConnectivityParameters.java:44)
com.sap.sailing.server.impl.RacingEventServiceImpl.addRace(RacingEventServiceImpl.java:743)
com.sap.sailing.server.impl.RacingEventServiceImpl.addSwissTimingRace(RacingEventServiceImpl.java:693)
com.sap.sailing.gwt.ui.server.SailingServiceImpl.trackWithSwissTiming(SailingServiceImpl.java:2435)
sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
java.lang.reflect.Method.invoke(Method.java:601)
com.google.gwt.user.server.rpc.RPC.invokeAndEncodeResponse(RPC.java:561)
com.google.gwt.user.server.rpc.RemoteServiceServlet.processCall(RemoteServiceServlet.java:208)
com.google.gwt.user.server.rpc.RemoteServiceServlet.processPost(RemoteServiceServlet.java:248)
com.google.gwt.user.server.rpc.AbstractRemoteServiceServlet.doPost(AbstractRemoteServiceServlet.java:62)
javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:547)
org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1359)
com.sap.sailing.server.gateway.GWTCacheControlServletFilter.doFilter(GWTCacheControlServletFilter.java:42)
org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1330)
org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:478)
org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:119)
org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:483)
org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:227)
org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:941)
org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:409)
org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:186)
org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:875)
org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:117)
org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:250)
org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:149)
org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:110)
org.eclipse.jetty.server.Server.handle(Server.java:349)
org.eclipse.jetty.server.HttpConnection.handleRequest(HttpConnection.java:441)
org.eclipse.jetty.server.HttpConnection$RequestHandler.content(HttpConnection.java:936)
org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:801)
org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:224)
org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:51)
org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:586)
org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:44)
org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:598)
org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:533)
java.lang.Thread.run(Thread.java:722)

Blocked Reader:

sun.misc.Unsafe.park(Native Method)
java.util.concurrent.locks.LockSupport.park(LockSupport.java:186)
java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(AbstractQueuedSynchronizer.java:834)
java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedInterruptibly(AbstractQueuedSynchronizer.java:994)
java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1303)
java.util.concurrent.FutureTask$Sync.innerGet(FutureTask.java:248)
java.util.concurrent.FutureTask.get(FutureTask.java:111)
com.sap.sailing.util.impl.SmartFutureCache.get(SmartFutureCache.java:343)
com.sap.sailing.domain.tracking.impl.TrackedRaceImpl.getManeuvers(TrackedRaceImpl.java:1900)
com.sap.sailing.gwt.ui.server.SailingServiceImpl.createLegEntry(SailingServiceImpl.java:927)
com.sap.sailing.gwt.ui.server.SailingServiceImpl.calculateRaceDetails(SailingServiceImpl.java:854)
com.sap.sailing.gwt.ui.server.SailingServiceImpl.getRaceDetails(SailingServiceImpl.java:720)
com.sap.sailing.gwt.ui.server.SailingServiceImpl.getLeaderboardEntryDTO(SailingServiceImpl.java:664)
com.sap.sailing.gwt.ui.server.SailingServiceImpl.access$5(SailingServiceImpl.java:651)
com.sap.sailing.gwt.ui.server.SailingServiceImpl$1.call(SailingServiceImpl.java:582)
com.sap.sailing.gwt.ui.server.SailingServiceImpl$1.call(SailingServiceImpl.java:1)
java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334)
java.util.concurrent.FutureTask.run(FutureTask.java:166)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603)
java.lang.Thread.run(Thread.java:722)

The reader is waiting for a Future to complete which is to compute the maneuvers for the ManeuverCache. The thread that is executing this Future is blocked trying to acquire the read lock on the course:

INFO: Couldn't acquire lock readLock lock for CourseImpl Laser - Race 1 in 5s at java.lang.Thread.getStackTrace(Thread.java:1567)
com.sap.sailing.util.impl.LockUtil.getStackTrace(LockUtil.java:105)
com.sap.sailing.util.impl.LockUtil.getCurrentStackTrace(LockUtil.java:113)
com.sap.sailing.util.impl.LockUtil.lock(LockUtil.java:37)
com.sap.sailing.util.impl.LockUtil.lockForRead(LockUtil.java:70)
com.sap.sailing.domain.base.impl.CourseImpl.lockForRead(CourseImpl.java:75)
com.sap.sailing.domain.base.impl.CourseImpl.getLastWaypoint(CourseImpl.java:350)
com.sap.sailing.domain.tracking.impl.TrackedRaceImpl.getTrackedLeg(TrackedRaceImpl.java:757)
com.sap.sailing.domain.tracking.impl.TrackedRaceImpl.createManeuverFromGroupOfCourseChanges(TrackedRaceImpl.java:2010)
com.sap.sailing.domain.tracking.impl.TrackedRaceImpl.groupChangesInSameDirectionIntoManeuvers(TrackedRaceImpl.java:1983)
com.sap.sailing.domain.tracking.impl.TrackedRaceImpl.detectManeuvers(TrackedRaceImpl.java:1864)
com.sap.sailing.domain.tracking.impl.TrackedRaceImpl.computeManeuvers(TrackedRaceImpl.java:1810)
com.sap.sailing.domain.tracking.impl.TrackedRaceImpl.access$4(TrackedRaceImpl.java:1778)
com.sap.sailing.domain.tracking.impl.TrackedRaceImpl$2.computeCacheUpdate(TrackedRaceImpl.java:386)
com.sap.sailing.domain.tracking.impl.TrackedRaceImpl$2.computeCacheUpdate(TrackedRaceImpl.java:1)
com.sap.sailing.util.impl.SmartFutureCache$1.call(SmartFutureCache.java:288)
java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334)
java.util.concurrent.FutureTask.run(FutureTask.java:166)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603)
java.lang.Thread.run(Thread.java:722)

This is probably caused by the writer having applied for the (fair) lock. Below goes the full round-trip of lock traces. Eventually, after suspending a few threads, the entire situation unraveled, probably because then, each time the writer times out, one reader can advance by just a little, until the writer finally gets its write lock granted.

Trying again...
Mar 21, 2013 3:20:38 PM com.sap.sailing.util.impl.LockUtil lock
INFO: Couldn't acquire lock readLock lock for CourseImpl Laser - Race 1 in 5s in thread pool-9-thread-1 at java.lang.Thread.getStackTrace(Thread.java:1567)
com.sap.sailing.util.impl.LockUtil.getStackTrace(LockUtil.java:105)
com.sap.sailing.util.impl.LockUtil.getCurrentStackTrace(LockUtil.java:113)
com.sap.sailing.util.impl.LockUtil.lock(LockUtil.java:37)
com.sap.sailing.util.impl.LockUtil.lockForRead(LockUtil.java:70)
com.sap.sailing.domain.base.impl.CourseImpl.lockForRead(CourseImpl.java:75)
com.sap.sailing.domain.base.impl.CourseImpl.getLastWaypoint(CourseImpl.java:350)
com.sap.sailing.domain.tracking.impl.TrackedRaceImpl.getTrackedLeg(TrackedRaceImpl.java:757)
com.sap.sailing.domain.tracking.impl.TrackedRaceImpl.createManeuverFromGroupOfCourseChanges(TrackedRaceImpl.java:2010)
com.sap.sailing.domain.tracking.impl.TrackedRaceImpl.groupChangesInSameDirectionIntoManeuvers(TrackedRaceImpl.java:1966)
com.sap.sailing.domain.tracking.impl.TrackedRaceImpl.detectManeuvers(TrackedRaceImpl.java:1864)
com.sap.sailing.domain.tracking.impl.TrackedRaceImpl.computeManeuvers(TrackedRaceImpl.java:1810)
com.sap.sailing.domain.tracking.impl.TrackedRaceImpl.access$4(TrackedRaceImpl.java:1778)
com.sap.sailing.domain.tracking.impl.TrackedRaceImpl$2.computeCacheUpdate(TrackedRaceImpl.java:386)
com.sap.sailing.domain.tracking.impl.TrackedRaceImpl$2.computeCacheUpdate(TrackedRaceImpl.java:1)
com.sap.sailing.util.impl.SmartFutureCache$1.call(SmartFutureCache.java:288)
java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334)
java.util.concurrent.FutureTask.run(FutureTask.java:166)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603)
java.lang.Thread.run(Thread.java:722)

The current readers are:
Thread[pool-2-thread-1,5,main]
sun.misc.Unsafe.park(Native Method)
java.util.concurrent.locks.LockSupport.park(LockSupport.java:186)
java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(AbstractQueuedSynchronizer.java:834)
java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedInterruptibly(AbstractQueuedSynchronizer.java:994)
java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1303)
java.util.concurrent.FutureTask$Sync.innerGet(FutureTask.java:248)
java.util.concurrent.FutureTask.get(FutureTask.java:111)
com.sap.sailing.util.impl.SmartFutureCache.get(SmartFutureCache.java:343)
com.sap.sailing.domain.tracking.impl.TrackedRaceImpl.getManeuvers(TrackedRaceImpl.java:1900)
com.sap.sailing.gwt.ui.server.SailingServiceImpl.createLegEntry(SailingServiceImpl.java:927)
com.sap.sailing.gwt.ui.server.SailingServiceImpl.calculateRaceDetails(SailingServiceImpl.java:854)
com.sap.sailing.gwt.ui.server.SailingServiceImpl.getRaceDetails(SailingServiceImpl.java:720)
com.sap.sailing.gwt.ui.server.SailingServiceImpl.getLeaderboardEntryDTO(SailingServiceImpl.java:664)
com.sap.sailing.gwt.ui.server.SailingServiceImpl.access$5(SailingServiceImpl.java:651)
com.sap.sailing.gwt.ui.server.SailingServiceImpl$1.call(SailingServiceImpl.java:582)
com.sap.sailing.gwt.ui.server.SailingServiceImpl$1.call(SailingServiceImpl.java:1)
java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334)
java.util.concurrent.FutureTask.run(FutureTask.java:166)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603)
java.lang.Thread.run(Thread.java:722)

Trying again...
Mar 21, 2013 3:20:38 PM com.sap.sailing.util.impl.LockUtil lock
INFO: Couldn't acquire lock readLock lock for CourseImpl Laser - Race 1 in 5s in thread TrackBasedEstimationWindTrackImpl cache invalidation timer for race SAM004901 at java.lang.Thread.getStackTrace(Thread.java:1567)
com.sap.sailing.util.impl.LockUtil.getStackTrace(LockUtil.java:105)
com.sap.sailing.util.impl.LockUtil.getCurrentStackTrace(LockUtil.java:113)
com.sap.sailing.util.impl.LockUtil.lock(LockUtil.java:37)
com.sap.sailing.util.impl.LockUtil.lockForRead(LockUtil.java:70)
com.sap.sailing.domain.base.impl.CourseImpl.lockForRead(CourseImpl.java:75)
com.sap.sailing.domain.tracking.impl.TrackedRaceImpl.clusterBearingsByLegType(TrackedRaceImpl.java:1604)
com.sap.sailing.domain.tracking.impl.TrackedRaceImpl.getEstimatedWindDirectionWithConfidence(TrackedRaceImpl.java:1539)
com.sap.sailing.domain.tracking.impl.TrackBasedEstimationWindTrackImpl.refreshCacheIncrementally(TrackBasedEstimationWindTrackImpl.java:361)
com.sap.sailing.domain.tracking.impl.TrackBasedEstimationWindTrackImpl.access$3(TrackBasedEstimationWindTrackImpl.java:321)
com.sap.sailing.domain.tracking.impl.TrackBasedEstimationWindTrackImpl$2.run(TrackBasedEstimationWindTrackImpl.java:406)
java.util.TimerThread.mainLoop(Timer.java:555)
java.util.TimerThread.run(Timer.java:505)

The current readers are:
Thread[pool-2-thread-1,5,main]
sun.misc.Unsafe.park(Native Method)
java.util.concurrent.locks.LockSupport.park(LockSupport.java:186)
java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(AbstractQueuedSynchronizer.java:834)
java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedInterruptibly(AbstractQueuedSynchronizer.java:994)
java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1303)
java.util.concurrent.FutureTask$Sync.innerGet(FutureTask.java:248)
java.util.concurrent.FutureTask.get(FutureTask.java:111)
com.sap.sailing.util.impl.SmartFutureCache.get(SmartFutureCache.java:343)
com.sap.sailing.domain.tracking.impl.TrackedRaceImpl.getManeuvers(TrackedRaceImpl.java:1900)
com.sap.sailing.gwt.ui.server.SailingServiceImpl.createLegEntry(SailingServiceImpl.java:927)
com.sap.sailing.gwt.ui.server.SailingServiceImpl.calculateRaceDetails(SailingServiceImpl.java:854)
com.sap.sailing.gwt.ui.server.SailingServiceImpl.getRaceDetails(SailingServiceImpl.java:720)
com.sap.sailing.gwt.ui.server.SailingServiceImpl.getLeaderboardEntryDTO(SailingServiceImpl.java:664)
com.sap.sailing.gwt.ui.server.SailingServiceImpl.access$5(SailingServiceImpl.java:651)
com.sap.sailing.gwt.ui.server.SailingServiceImpl$1.call(SailingServiceImpl.java:582)
com.sap.sailing.gwt.ui.server.SailingServiceImpl$1.call(SailingServiceImpl.java:1)
java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334)
java.util.concurrent.FutureTask.run(FutureTask.java:166)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603)
java.lang.Thread.run(Thread.java:722)

Trying again...
Mar 21, 2013 3:20:38 PM com.sap.sailing.util.impl.LockUtil lock
INFO: Couldn't acquire lock writeLock lock for CourseImpl Laser - Race 1 in 5s at java.lang.Thread.getStackTrace(Thread.java:1567)
com.sap.sailing.util.impl.LockUtil.getStackTrace(LockUtil.java:105)
com.sap.sailing.util.impl.LockUtil.getCurrentStackTrace(LockUtil.java:113)
com.sap.sailing.util.impl.LockUtil.lock(LockUtil.java:37)
com.sap.sailing.util.impl.LockUtil.lockForWrite(LockUtil.java:78)
com.sap.sailing.domain.base.impl.CourseImpl.update(CourseImpl.java:370)
com.sap.sailing.domain.swisstimingadapter.impl.DomainFactoryImpl.updateCourseWaypoints(DomainFactoryImpl.java:279)
com.sap.sailing.domain.swisstimingadapter.impl.SwissTimingRaceTrackerImpl.receivedCourseConfiguration(SwissTimingRaceTrackerImpl.java:331)
com.sap.sailing.domain.swisstimingadapter.impl.SailMasterConnectorImpl.notifyListenersCCG(SailMasterConnectorImpl.java:395)
com.sap.sailing.domain.swisstimingadapter.impl.SailMasterConnectorImpl.notifyListeners(SailMasterConnectorImpl.java:316)
com.sap.sailing.domain.swisstimingadapter.impl.SailMasterConnectorImpl.trackRace(SailMasterConnectorImpl.java:180)
com.sap.sailing.domain.swisstimingadapter.impl.SwissTimingRaceTrackerImpl.<init>(SwissTimingRaceTrackerImpl.java:100)
com.sap.sailing.domain.swisstimingadapter.impl.SwissTimingRaceTrackerImpl.<init>(SwissTimingRaceTrackerImpl.java:82)
com.sap.sailing.domain.swisstimingadapter.impl.SwissTimingFactoryImpl.createRaceTracker(SwissTimingFactoryImpl.java:87)
com.sap.sailing.domain.swisstimingadapter.impl.SwissTimingTrackingConnectivityParameters.createRaceTracker(SwissTimingTrackingConnectivityParameters.java:44)
com.sap.sailing.server.impl.RacingEventServiceImpl.addRace(RacingEventServiceImpl.java:743)
com.sap.sailing.server.impl.RacingEventServiceImpl.addSwissTimingRace(RacingEventServiceImpl.java:693)
com.sap.sailing.gwt.ui.server.SailingServiceImpl.trackWithSwissTiming(SailingServiceImpl.java:2435)
sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
java.lang.reflect.Method.invoke(Method.java:601)
com.google.gwt.user.server.rpc.RPC.invokeAndEncodeResponse(RPC.java:561)
com.google.gwt.user.server.rpc.RemoteServiceServlet.processCall(RemoteServiceServlet.java:208)
com.google.gwt.user.server.rpc.RemoteServiceServlet.processPost(RemoteServiceServlet.java:248)
com.google.gwt.user.server.rpc.AbstractRemoteServiceServlet.doPost(AbstractRemoteServiceServlet.java:62)
javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:547)
org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1359)
com.sap.sailing.server.gateway.GWTCacheControlServletFilter.doFilter(GWTCacheControlServletFilter.java:42)
org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1330)
org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:478)
org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:119)
org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:483)
org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:227)
org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:941)
org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:409)
org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:186)
org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:875)
org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:117)
org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:250)
org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:149)
org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:110)
org.eclipse.jetty.server.Server.handle(Server.java:349)
org.eclipse.jetty.server.HttpConnection.handleRequest(HttpConnection.java:441)
org.eclipse.jetty.server.HttpConnection$RequestHandler.content(HttpConnection.java:936)
org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:801)
org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:224)
org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:51)
org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:586)
org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:44)
org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:598)
org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:533)
java.lang.Thread.run(Thread.java:722)

The current readers are:
Thread[pool-2-thread-1,5,main]
sun.misc.Unsafe.park(Native Method)
java.util.concurrent.locks.LockSupport.park(LockSupport.java:186)
java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(AbstractQueuedSynchronizer.java:834)
java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedInterruptibly(AbstractQueuedSynchronizer.java:994)
java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1303)
java.util.concurrent.FutureTask$Sync.innerGet(FutureTask.java:248)
java.util.concurrent.FutureTask.get(FutureTask.java:111)
com.sap.sailing.util.impl.SmartFutureCache.get(SmartFutureCache.java:343)
com.sap.sailing.domain.tracking.impl.TrackedRaceImpl.getManeuvers(TrackedRaceImpl.java:1900)
com.sap.sailing.gwt.ui.server.SailingServiceImpl.createLegEntry(SailingServiceImpl.java:927)
com.sap.sailing.gwt.ui.server.SailingServiceImpl.calculateRaceDetails(SailingServiceImpl.java:854)
com.sap.sailing.gwt.ui.server.SailingServiceImpl.getRaceDetails(SailingServiceImpl.java:720)
com.sap.sailing.gwt.ui.server.SailingServiceImpl.getLeaderboardEntryDTO(SailingServiceImpl.java:664)
com.sap.sailing.gwt.ui.server.SailingServiceImpl.access$5(SailingServiceImpl.java:651)
com.sap.sailing.gwt.ui.server.SailingServiceImpl$1.call(SailingServiceImpl.java:582)
com.sap.sailing.gwt.ui.server.SailingServiceImpl$1.call(SailingServiceImpl.java:1)
java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334)
java.util.concurrent.FutureTask.run(FutureTask.java:166)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603)
java.lang.Thread.run(Thread.java:722)

Trying again...
Mar 21, 2013 3:20:43 PM com.sap.sailing.util.impl.LockUtil lock
INFO: Couldn't acquire lock readLock lock for CourseImpl Laser - Race 1 in 5s in thread TrackBasedEstimationWindTrackImpl cache invalidation timer for race SAM004901 at java.lang.Thread.getStackTrace(Thread.java:1567)
com.sap.sailing.util.impl.LockUtil.getStackTrace(LockUtil.java:105)
com.sap.sailing.util.impl.LockUtil.getCurrentStackTrace(LockUtil.java:113)
com.sap.sailing.util.impl.LockUtil.lock(LockUtil.java:37)
com.sap.sailing.util.impl.LockUtil.lockForRead(LockUtil.java:70)
com.sap.sailing.domain.base.impl.CourseImpl.lockForRead(CourseImpl.java:75)
com.sap.sailing.domain.tracking.impl.TrackedRaceImpl.clusterBearingsByLegType(TrackedRaceImpl.java:1604)
com.sap.sailing.domain.tracking.impl.TrackedRaceImpl.getEstimatedWindDirectionWithConfidence(TrackedRaceImpl.java:1539)
com.sap.sailing.domain.tracking.impl.TrackBasedEstimationWindTrackImpl.refreshCacheIncrementally(TrackBasedEstimationWindTrackImpl.java:361)
com.sap.sailing.domain.tracking.impl.TrackBasedEstimationWindTrackImpl.access$3(TrackBasedEstimationWindTrackImpl.java:321)
com.sap.sailing.domain.tracking.impl.TrackBasedEstimationWindTrackImpl$2.run(TrackBasedEstimationWindTrackImpl.java:406)
java.util.TimerThread.mainLoop(Timer.java:555)
java.util.TimerThread.run(Timer.java:505)

The current readers are:
Thread[pool-2-thread-1,5,main]
sun.misc.Unsafe.park(Native Method)
java.util.concurrent.locks.LockSupport.park(LockSupport.java:186)
java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(AbstractQueuedSynchronizer.java:834)
java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedInterruptibly(AbstractQueuedSynchronizer.java:994)
java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1303)
java.util.concurrent.FutureTask$Sync.innerGet(FutureTask.java:248)
java.util.concurrent.FutureTask.get(FutureTask.java:111)
com.sap.sailing.util.impl.SmartFutureCache.get(SmartFutureCache.java:343)
com.sap.sailing.domain.tracking.impl.TrackedRaceImpl.getManeuvers(TrackedRaceImpl.java:1900)
com.sap.sailing.gwt.ui.server.SailingServiceImpl.createLegEntry(SailingServiceImpl.java:927)
com.sap.sailing.gwt.ui.server.SailingServiceImpl.calculateRaceDetails(SailingServiceImpl.java:854)
com.sap.sailing.gwt.ui.server.SailingServiceImpl.getRaceDetails(SailingServiceImpl.java:720)
com.sap.sailing.gwt.ui.server.SailingServiceImpl.getLeaderboardEntryDTO(SailingServiceImpl.java:664)
com.sap.sailing.gwt.ui.server.SailingServiceImpl.access$5(SailingServiceImpl.java:651)
com.sap.sailing.gwt.ui.server.SailingServiceImpl$1.call(SailingServiceImpl.java:582)
com.sap.sailing.gwt.ui.server.SailingServiceImpl$1.call(SailingServiceImpl.java:1)
java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334)
java.util.concurrent.FutureTask.run(FutureTask.java:166)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603)
java.lang.Thread.run(Thread.java:722)

**Comment by aksajhfduwafe** [comment]
**@axeluhl** commented:

If 4. didn't have to acquire the course's read lock again that was already acquired by 2., the deadlock wouldn't occur. Why is 2. kicking off 4. in a separate thread at all?
