### ISSUE TITLE
NPE when removing race, trying to detach race log of Default Leaderboard

### ISSUE THREAD

**Issue by aksajhfduwafe** [aksajhfduwafe/bugzilla-to-github-issues-test#1423]
| Field | Value |
|---|---|
| **Reporter** | @axeluhl |
| **Assignee** | Simon Pamies (`s.pamies@the-placeholder-company.com`) |
| **Product** | Sailing Race Analytics |
| **Component** | Server |
| **Version** | unspecified |
| **Hardware** | All |
| **OS** | All |
| **Severity** | blocker |
| **Priority** | P1 |
| **CC (unmapped)** | Armin Zamani Farahani (`armin.zamani.farahani@sap.com`), Lukas Niemeier (`lukas.niemeier@student.hpi.uni-potsdam.de`), Simon Pamies (`s.pamies@the-placeholder-company.com`) |
| **Created** | 2013-06-04T22:21:10Z |
| **Original Bug** | [Bug 1423](https://bugzilla.sapsailing.com/bugzilla/show_bug.cgi?id=1423) |

---

A TrackedRace is currently still implicitly added to the DefaultLeaderboard as soon as it is created. This probably also assigns a trivial RaceLog to each such race.

When removing a race, the columns to which the race is assigned are found, and the race is detached from those columns. Regatta leaderboard columns are currently handled before flexible leaderboard columns, but this is just a coincidence. When the second log detach is attempted, the race doesn't have a log attached, and the NullPointerException shown below is thrown.

#1163 is asking to remove the default leaderboard altogether. However, this would only fix the case where one of two leaderboards to which the race is linked is the default leaderboard. The race could as well be linked to two non-default leaderboards. Then, when it is removed, how are its race logs handled?

The short-term remedy is to simply make DynamicTrackedRaceLog.removeFrom(...) null-safe. See commit 84e6a6d98f5858e482f3247b862b4875af055542. The core problem, however, remains unsolved by this: what is supposed to happen if a race is attached to a second leaderboard column regarding its race log, and what is supposed to happen if a race is detached from one leaderboard column but is still attached to one or more other columns?

I see the following options:

 a) A tracked race has a stack of race logs. When it is attached to a column, the column's race log is pushed onto this stack and becomes the current race's log. When a race is detached from a column, the log is removed from the stack (not necessarily a pop because it doesn't have to be in LIFO order) and the now top element is the current race log.
 
 b) A tracked race can have more than one race log at the same time, according to the "Composite" pattern. This set of race log would virtually be merged into a single race log. In other words, all race log events input through any of the columns to which the race is attached will reach the tracked race.

I personally prefer b) and think it should be fairly easy to build. What do the others think?

java.lang.NullPointerException
     at 
com.sap.sailing.domain.tracking.impl.DynamicTrackedRaceLogListener.removeFrom(DynamicTrackedRaceLogListener.java:52)
     at 
com.sap.sailing.domain.tracking.impl.DynamicTrackedRaceImpl.detachRaceLog(DynamicTrackedRaceImpl.java:673)
     at 
com.sap.sailing.domain.base.impl.AbstractRaceColumn.setTrackedRace(AbstractRaceColumn.java:117)
     at 
com.sap.sailing.domain.base.impl.RaceColumnInSeriesImpl.setTrackedRace(RaceColumnInSeriesImpl.java:90)
     at 
com.sap.sailing.domain.base.impl.AbstractRaceColumn.releaseTrackedRace(AbstractRaceColumn.java:143)
     at 
com.sap.sailing.server.impl.RacingEventServiceImpl.removeRace(RacingEventServiceImpl.java:1260)
     at 
com.sap.sailing.server.operationaltransformation.RemoveAndUntrackRace.internalApplyTo(RemoveAndUntrackRace.java:37)
     at 
com.sap.sailing.server.operationaltransformation.RemoveAndUntrackRace.internalApplyTo(RemoveAndUntrackRace.java:1)
     at 
com.sap.sailing.server.impl.RacingEventServiceImpl.apply(RacingEventServiceImpl.java:1619)
     at 
com.sap.sailing.gwt.ui.server.SailingServiceImpl.removeAndUntrackRaces(SailingServiceImpl.java:693)
     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
     at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
     at java.lang.reflect.Method.invoke(Unknown Source)
     at 
com.google.gwt.user.server.rpc.RPC.invokeAndEncodeResponse(RPC.java:561)
     at 
com.google.gwt.user.server.rpc.RemoteServiceServlet.processCall(RemoteServiceServlet.java:208)
     at 
com.google.gwt.user.server.rpc.RemoteServiceServlet.processPost(RemoteServiceServlet.java:248)
     at 
com.google.gwt.user.server.rpc.AbstractRemoteServiceServlet.doPost(AbstractRemoteServiceServlet.java:62)
     at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
     at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
     at 
org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:547)
     at 
org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1359)
     at 
com.sap.sailing.server.gateway.GWTCacheControlServletFilter.doFilter(GWTCacheControlServletFilter.java:42)
     at 
org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1330)
     at 
org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:478)
     at 
org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:119)
     at 
org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:483)
     at 
org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:227)
     at 
org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:941)
     at 
org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:409)
     at 
org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:186)
     at 
org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:875)
     at 
org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:117)
     at 
org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:250)
     at 
org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:149)
     at 
org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:110)
     at org.eclipse.jetty.server.Server.handle(Server.java:349)
     at 
org.eclipse.jetty.server.HttpConnection.handleRequest(HttpConnection.java:441)
     at 
org.eclipse.jetty.server.HttpConnection$RequestHandler.content(HttpConnection.java:936)
     at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:801)
     at 
org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:224)
     at 
org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:51)
     at 
org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:586)
     at 
org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:44)
     at 
org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:598)
     at 
org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:533)
     at java.lang.Thread.run(Unknown Source)

Jun 04, 2013 6:21:32 PM 
org.eclipse.jetty.server.handler.ContextHandler$Context log
Warnung: Exception while dispatching incoming RPC call
com.google.gwt.user.server.rpc.UnexpectedException: Service method 
'public abstract void 
com.sap.sailing.gwt.ui.client.SailingService.removeAndUntrackRaces(java.lang.Iterable)' 
threw an unexpected exception: java.lang.RuntimeException: 
java.lang.NullPointerException
     at 
com.google.gwt.user.server.rpc.RPC.encodeResponseForFailure(RPC.java:389)
     at 
com.google.gwt.user.server.rpc.RPC.invokeAndEncodeResponse(RPC.java:579)
     at 
com.google.gwt.user.server.rpc.RemoteServiceServlet.processCall(RemoteServiceServlet.java:208)
     at 
com.google.gwt.user.server.rpc.RemoteServiceServlet.processPost(RemoteServiceServlet.java:248)
     at 
com.google.gwt.user.server.rpc.AbstractRemoteServiceServlet.doPost(AbstractRemoteServiceServlet.java:62)
     at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
     at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
     at 
org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:547)
     at 
org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1359)
     at 
com.sap.sailing.server.gateway.GWTCacheControlServletFilter.doFilter(GWTCacheControlServletFilter.java:42)
     at 
org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1330)
     at 
org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:478)
     at 
org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:119)
     at 
org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:483)
     at 
org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:227)
     at 
org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:941)
     at 
org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:409)
     at 
org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:186)
     at 
org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:875)
     at 
org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:117)
     at 
org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:250)
     at 
org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:149)
     at 
org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:110)
     at org.eclipse.jetty.server.Server.handle(Server.java:349)
     at 
org.eclipse.jetty.server.HttpConnection.handleRequest(HttpConnection.java:441)
     at 
org.eclipse.jetty.server.HttpConnection$RequestHandler.content(HttpConnection.java:936)
     at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:801)
     at 
org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:224)
     at 
org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:51)
     at 
org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:586)
     at 
org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:44)
     at 
org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:598)
     at 
org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:533)
     at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.RuntimeException: java.lang.NullPointerException
     at 
com.sap.sailing.server.impl.RacingEventServiceImpl.apply(RacingEventServiceImpl.java:1624)
     at 
com.sap.sailing.gwt.ui.server.SailingServiceImpl.removeAndUntrackRaces(SailingServiceImpl.java:693)
     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
     at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
     at java.lang.reflect.Method.invoke(Unknown Source)
     at 
com.google.gwt.user.server.rpc.RPC.invokeAndEncodeResponse(RPC.java:561)
     ... 32 more
Caused by: java.lang.NullPointerException
     at 
com.sap.sailing.domain.tracking.impl.DynamicTrackedRaceLogListener.removeFrom(DynamicTrackedRaceLogListener.java:52)
     at 
com.sap.sailing.domain.tracking.impl.DynamicTrackedRaceImpl.detachRaceLog(DynamicTrackedRaceImpl.java:673)
     at 
com.sap.sailing.domain.base.impl.AbstractRaceColumn.setTrackedRace(AbstractRaceColumn.java:117)
     at 
com.sap.sailing.domain.base.impl.RaceColumnInSeriesImpl.setTrackedRace(RaceColumnInSeriesImpl.java:90)
     at 
com.sap.sailing.domain.base.impl.AbstractRaceColumn.releaseTrackedRace(AbstractRaceColumn.java:143)
     at 
com.sap.sailing.server.impl.RacingEventServiceImpl.removeRace(RacingEventServiceImpl.java:1260)
     at 
com.sap.sailing.server.operationaltransformation.RemoveAndUntrackRace.internalApplyTo(RemoveAndUntrackRace.java:37)
     at 
com.sap.sailing.server.operationaltransformation.RemoveAndUntrackRace.internalApplyTo(RemoveAndUntrackRace.java:1)
     at 
com.sap.sailing.server.impl.RacingEventServiceImpl.apply(RacingEventServiceImpl.java:1619)
     ... 38 more

**Comment by aksajhfduwafe** [comment]
**Lukas Niemeier (`lukas.niemeier@student.hpi.uni-potsdam.de`)** commented:

When a TrackedRace is linked to two (or more) non-default leaderboards race officers are able to maintain the two or more RaceColumn's logs separately (without any knowledge of the linkage). Regarding the proposed solutions...
a) ... one of the two (or more) race officers wins and is in control of the TrackedRace's log. The other race officers are still maintaining "their" RaceColumn's log without any effect on the connected TrackedRace. RegattaOverview will show all race officer's logs separately (since it's showing the RaceColumns). Is there a use case for this scenario? Which officer should win?
b) ... all race officers are maintaining the TrackedRace's log without any knowledge of each other. I'm not sure how we can ensure a meaningful log in this case.

Summary: what are the use cases for a TrackedRace linked to several RaceColumns? Are there any constraints? Can we somehow assume that the linked RaceColumns (logs) are not maintained by multiple race officers?

**Comment by aksajhfduwafe** [comment]
**@axeluhl** commented:

I agree that it would be preferable to have at most one RaceLog linked to one TrackedRace. This would require that when a TrackedRace is linked to a leaderboard when it already is linked to another leaderboard and therefore already has a RaceLog associated, the user disambiguates and makes an explicit choice, telling which column's RaceLog is to be attached to the TrackedRace. This decision needs to be replicated and stored persistently so that when a server is restarted, the configuration is restored accordingly. I guess it's the effort caused by all this that so far made it an unfavorable option.

The situation gets even worse when the Default Leaderboard is involved. The linking to this leaderboard happens implicitly, without the user knowing. As long as we maintain the Default Leaderboard, I would agree to any proposal that suggests not having any RaceLog on any of the default leaderboard's columns.

But this doesn't solve the explicit association of the same TrackedRace with two "real" columns, as in the "Nixdorf Cup" example. Maybe it would be helpful to be able to configure a leaderboard such that it doesn't contribute any RaceLogs on its columns. This way, leaderboards such as the Default Leaderboard or a "shadow leaderboard" such as the Nixdorf Cup example could be configured this way and then don't contribute any RaceLog to the tracked races that are attached. With such a configuration we could make it an error to try to add a second RaceLog to a TrackedRace.

**Comment by aksajhfduwafe** [comment]
**Simon Pamies (`s.pamies@the-placeholder-company.com`)** commented:

On branch consolidated-race-logs (ccacf7e0261a15df4a10f9a45179097245c423aa) I've introduced the possibility to have two race logs for one tracked race. The code as it is now follows the "Composite" pattern and at least fixes the NPE.

As Lukas mentioned this now can lead to strange behaviour when both race logs are active and fire events and I'm not happy with this. But we not only have "real" usescases where one attaches a race willingly to two columns but also the case where you attach a race to a column but didn't want to (sometimes related to responsiveness of GWT interface).

I would propose the following: 

We introduce a new Leaderboard property "allowMultipleLinking". If this is set to true then one can assign one race to multiple columns (Nixdorf case). A property description clearly states that the behaviour for multiple active logs is undefined and that the order of linking matters (last linked column+log wins). 

If the property is false (default) then the interface does not allow linking a race to multiple columns.

This property will only control linking for user actions and won't be evaluated for operations like implicit linking.

I think this is the easiest and most user friendly way to go that also gives us enough control.

**Comment by aksajhfduwafe** [comment]
**@axeluhl** commented:

I like the branch. Merged to master with 4f069c839d05ec07633a99cf0be6daa8600542af. However, it's not exactly a Composite pattern because there is no RaceLog implementation that aggregates the multiple RaceLog objects that may currently be attached to a TrackedRace. Would this be helpful? At least we could then have a single StartTimeFinder that traverses the composite race log. But I wouldn't know how to solve the question of how to assign a pass ID in the presence of multiple different underlying pass IDs.

Next step: I'll change the way the start time extraction works in TrackedRace. I don't think it's clever to push the start time into the startTimeReceived field. Instead, I think in addition to checking the startTimeReceived field when getStartOfRace() is called, the first check should be with a StartTimeFinder that scans all race logs.

**Comment by aksajhfduwafe** [comment]
**@axeluhl** commented:

Commit 86ff9e2c2666b4548ac265511af42ea51cd38415 extracts the race start time dynamically from all attached race logs. Please review.

**Comment by aksajhfduwafe** [comment]
**Lukas Niemeier (`lukas.niemeier@student.hpi.uni-potsdam.de`)** commented:

NPE is fixed for now. See #1444 for further discussion of the problem.
