### ISSUE TITLE
Deadlock regarding wind tracks

### ISSUE THREAD

**Issue by aksajhfduwafe** [aksajhfduwafe/bugzilla-to-github-issues-test#1483]
| Field | Value |
|---|---|
| **Reporter** | @axeluhl |
| **Assignee** | @axeluhl |
| **Product** | Sailing Race Analytics |
| **Component** | Server |
| **Version** | unspecified |
| **Hardware** | All |
| **OS** | All |
| **Severity** | normal |
| **Priority** | P1 |
| **Created** | 2013-07-05T11:50:34Z |
| **Original Bug** | [Bug 1483](https://bugzilla.sapsailing.com/bugzilla/show_bug.cgi?id=1483) |

---

Jul 05, 2013 11:44:56 AM com.sap.sailing.util.impl.LockUtil lock
INFO: Couldn't acquire lock writeLock VirtualWindTrackImpl for race 49FX Gold R10 in 5s in thread UDPReceiver ToListenerDispatcher for listener ExpeditionWindTracker on UDP port 2013 at
java.lang.Thread.getStackTrace(Thread.java:1567)
com.sap.sailing.util.impl.LockUtil.getStackTrace(LockUtil.java:359)
com.sap.sailing.util.impl.LockUtil.getCurrentStackTrace(LockUtil.java:367)
com.sap.sailing.util.impl.LockUtil.lock(LockUtil.java:389)
com.sap.sailing.util.impl.LockUtil.acquireLockVirtuallyOrActually(LockUtil.java:106)
com.sap.sailing.util.impl.LockUtil.lockForWrite(LockUtil.java:86)
com.sap.sailing.domain.tracking.impl.TrackImpl.lockForWrite(TrackImpl.java:75)
com.sap.sailing.domain.tracking.impl.TrackBasedEstimationWindTrackImpl.scheduleCacheRefresh(TrackBasedEstimationWindTrackImpl.java:266)
com.sap.sailing.domain.tracking.impl.TrackBasedEstimationWindTrackImpl.invalidateForNewWind(TrackBasedEstimationWindTrackImpl.java:486)
com.sap.sailing.domain.tracking.impl.TrackBasedEstimationWindTrackImpl.windDataReceived(TrackBasedEstimationWindTrackImpl.java:470)
com.sap.sailing.domain.tracking.impl.DynamicTrackedRaceImpl.notifyListeners(DynamicTrackedRaceImpl.java:332)
com.sap.sailing.domain.tracking.impl.DynamicTrackedRaceImpl.recordWind(DynamicTrackedRaceImpl.java:608)
com.sap.sailing.expeditionconnector.ExpeditionWindTracker.received(ExpeditionWindTracker.java:118)
com.sap.sailing.expeditionconnector.ExpeditionWindTracker.received(ExpeditionWindTracker.java:1)
com.sap.sailing.udpconnector.UDPReceiver$ToListenerDispatcher.run(UDPReceiver.java:65)

The current readers are:
Thread[qtp1397325628-1230,5,main]
com.sap.sailing.util.impl.LockUtil.lock(LockUtil.java:381)
com.sap.sailing.util.impl.LockUtil.acquireLockVirtuallyOrActually(LockUtil.java:106)
com.sap.sailing.util.impl.LockUtil.lockForRead(LockUtil.java:82)
com.sap.sailing.domain.base.impl.CourseImpl.lockForRead(CourseImpl.java:84)
com.sap.sailing.domain.base.impl.CourseImpl.getLastWaypoint(CourseImpl.java:364)
com.sap.sailing.domain.tracking.impl.TrackedRaceImpl.getTrackedLeg(TrackedRaceImpl.java:820)
com.sap.sailing.domain.tracking.impl.TrackedRaceImpl.clusterBearingsByLegType(TrackedRaceImpl.java:1681)
com.sap.sailing.domain.tracking.impl.TrackedRaceImpl.getEstimatedWindDirectionWithConfidence(TrackedRaceImpl.java:1611)
com.sap.sailing.domain.tracking.impl.TrackBasedEstimationWindTrackImpl.getEstimatedWindDirection(TrackBasedEstimationWindTrackImpl.java:447)
com.sap.sailing.domain.tracking.impl.TrackBasedEstimationWindTrackImpl.access$1(TrackBasedEstimationWindTrackImpl.java:430)
com.sap.sailing.domain.tracking.impl.TrackBasedEstimationWindTrackImpl$EstimatedWindFixesAsNavigableSet.getWindWithConfidence(TrackBasedEstimationWindTrackImpl.java:644)
com.sap.sailing.domain.tracking.impl.TrackBasedEstimationWindTrackImpl$EstimatedWindFixesAsNavigableSet.getWind(TrackBasedEstimationWindTrackImpl.java:639)
com.sap.sailing.domain.tracking.impl.VirtualWindFixesAsNavigableSet.floor(VirtualWindFixesAsNavigableSet.java:163)
com.sap.sailing.domain.tracking.impl.VirtualWindFixesAsNavigableSet$1.next(VirtualWindFixesAsNavigableSet.java:190)
com.sap.sailing.domain.tracking.impl.VirtualWindFixesAsNavigableSet$1.next(VirtualWindFixesAsNavigableSet.java:1)
com.sap.sailing.domain.tracking.impl.PartialNavigableSetView$FilteringIterator.advance(PartialNavigableSetView.java:64)
com.sap.sailing.domain.tracking.impl.PartialNavigableSetView$FilteringIterator.<init>(PartialNavigableSetView.java:57)
com.sap.sailing.domain.tracking.impl.PartialNavigableSetView.iterator(PartialNavigableSetView.java:319)
com.sap.sailing.domain.tracking.impl.TrackImpl.getFixesIterator(TrackImpl.java:252)
com.sap.sailing.server.gateway.impl.WindJsonGetServlet.getRelevantFixes(WindJsonGetServlet.java:98)
com.sap.sailing.server.gateway.impl.WindJsonGetServlet.getResult(WindJsonGetServlet.java:81)
com.sap.sailing.server.gateway.impl.WindJsonGetServlet.doGet(WindJsonGetServlet.java:73)
javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:547)
org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:480)
org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:119)
org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:483)
org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:227)
org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:941)
org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:409)
org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:186)
org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:875)
org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:117)
org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:250)
org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:149)
org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:110)
org.eclipse.jetty.server.Server.handle(Server.java:349)
org.eclipse.jetty.server.HttpConnection.handleRequest(HttpConnection.java:441)
org.eclipse.jetty.server.HttpConnection$RequestHandler.headerComplete(HttpConnection.java:919)
org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:582)
org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:218)
org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:51)
org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:586)
org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:44)
org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:598)
org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:533)
java.lang.Thread.run(Thread.java:722)

Trying again...
Jul 05, 2013 11:44:56 AM com.sap.sailing.util.impl.LockUtil lock
INFO: Couldn't acquire lock readLock VirtualWindTrackImpl for race 49FX Gold R10 in 5s in thread pool-27-thread-2 at java.lang.Thread.getStackTrace(Thread.java:1567)
com.sap.sailing.util.impl.LockUtil.getStackTrace(LockUtil.java:359)
com.sap.sailing.util.impl.LockUtil.getCurrentStackTrace(LockUtil.java:367)
com.sap.sailing.util.impl.LockUtil.lock(LockUtil.java:389)
com.sap.sailing.util.impl.LockUtil.acquireLockVirtuallyOrActually(LockUtil.java:106)
com.sap.sailing.util.impl.LockUtil.lockForRead(LockUtil.java:82)
com.sap.sailing.domain.tracking.impl.TrackImpl.lockForRead(TrackImpl.java:66)
com.sap.sailing.domain.tracking.impl.TrackBasedEstimationWindTrackImpl.getAveragedWindUnsynchronized(TrackBasedEstimationWindTrackImpl.java:570)
com.sap.sailing.domain.tracking.impl.VirtualWindTrackImpl.getAveragedWindWithConfidence(VirtualWindTrackImpl.java:84)
com.sap.sailing.domain.tracking.impl.TrackedRaceImpl.getWindWithConfidence(TrackedRaceImpl.java:1253)
com.sap.sailing.domain.tracking.impl.TrackedRaceImpl.getWind(TrackedRaceImpl.java:1208)
com.sap.sailing.domain.tracking.impl.TrackedRaceImpl.getWind(TrackedRaceImpl.java:1203)
com.sap.sailing.domain.tracking.impl.TrackedRaceImpl.getTack(TrackedRaceImpl.java:1815)
com.sap.sailing.domain.tracking.impl.TrackedRaceImpl.createManeuverFromGroupOfCourseChanges(TrackedRaceImpl.java:2104)
com.sap.sailing.domain.tracking.impl.TrackedRaceImpl.groupChangesInSameDirectionIntoManeuvers(TrackedRaceImpl.java:2066)
com.sap.sailing.domain.tracking.impl.TrackedRaceImpl.detectManeuvers(TrackedRaceImpl.java:1959)
com.sap.sailing.domain.tracking.impl.TrackedRaceImpl.computeManeuvers(TrackedRaceImpl.java:1890)
com.sap.sailing.domain.tracking.impl.TrackedRaceImpl.access$4(TrackedRaceImpl.java:1854)
com.sap.sailing.domain.tracking.impl.TrackedRaceImpl$2.computeCacheUpdate(TrackedRaceImpl.java:405)
com.sap.sailing.domain.tracking.impl.TrackedRaceImpl$2.computeCacheUpdate(TrackedRaceImpl.java:1)
com.sap.sailing.util.SmartFutureCache$FutureTaskWithCancelBlocking.call(SmartFutureCache.java:320)
com.sap.sailing.util.SmartFutureCache$SettableCallable.call(SmartFutureCache.java:198)
java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334)
java.util.concurrent.FutureTask.run(FutureTask.java:166)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603)
java.lang.Thread.run(Thread.java:722)

The current readers are:
Thread[qtp1397325628-1230,5,main]
com.sap.sailing.util.impl.LockUtil.acquireLockVirtuallyOrActually(LockUtil.java:93)
com.sap.sailing.util.impl.LockUtil.lockForRead(LockUtil.java:82)
com.sap.sailing.domain.base.impl.CourseImpl.lockForRead(CourseImpl.java:84)
com.sap.sailing.domain.tracking.impl.DynamicTrackedRaceImpl.lockForRead(DynamicTrackedRaceImpl.java:512)
com.sap.sailing.domain.tracking.impl.TrackedRaceImpl.getTrackedLeg(TrackedRaceImpl.java:807)
com.sap.sailing.domain.tracking.impl.TrackedRaceImpl.clusterBearingsByLegType(TrackedRaceImpl.java:1681)
com.sap.sailing.domain.tracking.impl.TrackedRaceImpl.getEstimatedWindDirectionWithConfidence(TrackedRaceImpl.java:1611)
com.sap.sailing.domain.tracking.impl.TrackBasedEstimationWindTrackImpl.getEstimatedWindDirection(TrackBasedEstimationWindTrackImpl.java:447)
com.sap.sailing.domain.tracking.impl.TrackBasedEstimationWindTrackImpl.access$1(TrackBasedEstimationWindTrackImpl.java:430)
com.sap.sailing.domain.tracking.impl.TrackBasedEstimationWindTrackImpl$EstimatedWindFixesAsNavigableSet.getWindWithConfidence(TrackBasedEstimationWindTrackImpl.java:644)
com.sap.sailing.domain.tracking.impl.TrackBasedEstimationWindTrackImpl$EstimatedWindFixesAsNavigableSet.getWind(TrackBasedEstimationWindTrackImpl.java:639)
com.sap.sailing.domain.tracking.impl.VirtualWindFixesAsNavigableSet.floor(VirtualWindFixesAsNavigableSet.java:163)
com.sap.sailing.domain.tracking.impl.VirtualWindFixesAsNavigableSet$1.next(VirtualWindFixesAsNavigableSet.java:190)
com.sap.sailing.domain.tracking.impl.VirtualWindFixesAsNavigableSet$1.next(VirtualWindFixesAsNavigableSet.java:1)
com.sap.sailing.domain.tracking.impl.PartialNavigableSetView$FilteringIterator.advance(PartialNavigableSetView.java:64)
com.sap.sailing.domain.tracking.impl.PartialNavigableSetView$FilteringIterator.<init>(PartialNavigableSetView.java:57)
com.sap.sailing.domain.tracking.impl.PartialNavigableSetView.iterator(PartialNavigableSetView.java:319)
com.sap.sailing.domain.tracking.impl.TrackImpl.getFixesIterator(TrackImpl.java:252)
com.sap.sailing.server.gateway.impl.WindJsonGetServlet.getRelevantFixes(WindJsonGetServlet.java:98)
com.sap.sailing.server.gateway.impl.WindJsonGetServlet.getResult(WindJsonGetServlet.java:81)
com.sap.sailing.server.gateway.impl.WindJsonGetServlet.doGet(WindJsonGetServlet.java:73)
javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:547)
org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:480)
org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:119)
org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:483)
org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:227)
org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:941)
org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:409)
org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:186)
org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:875)
org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:117)
org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:250)
org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:149)
org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:110)
org.eclipse.jetty.server.Server.handle(Server.java:349)
org.eclipse.jetty.server.HttpConnection.handleRequest(HttpConnection.java:441)
org.eclipse.jetty.server.HttpConnection$RequestHandler.headerComplete(HttpConnection.java:919)
org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:582)
org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:218)
org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:51)
org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:586)
org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:44)
org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:598)
org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:533)
java.lang.Thread.run(Thread.java:722)

Trying again...
Jul 05, 2013 11:44:56 AM com.sap.sailing.util.impl.LockUtil lock
INFO: Couldn't acquire lock readLock VirtualWindTrackImpl for race 49FX Gold R10 in 5s in thread pool-27-thread-4 at java.lang.Thread.getStackTrace(Thread.java:1567)
com.sap.sailing.util.impl.LockUtil.getStackTrace(LockUtil.java:359)
com.sap.sailing.util.impl.LockUtil.getCurrentStackTrace(LockUtil.java:367)
com.sap.sailing.util.impl.LockUtil.lock(LockUtil.java:389)
com.sap.sailing.util.impl.LockUtil.acquireLockVirtuallyOrActually(LockUtil.java:106)
com.sap.sailing.util.impl.LockUtil.lockForRead(LockUtil.java:82)
com.sap.sailing.domain.tracking.impl.TrackImpl.lockForRead(TrackImpl.java:66)
com.sap.sailing.domain.tracking.impl.TrackBasedEstimationWindTrackImpl.getAveragedWindUnsynchronized(TrackBasedEstimationWindTrackImpl.java:570)
com.sap.sailing.domain.tracking.impl.VirtualWindTrackImpl.getAveragedWindWithConfidence(VirtualWindTrackImpl.java:84)
com.sap.sailing.domain.tracking.impl.TrackedRaceImpl.getWindWithConfidence(TrackedRaceImpl.java:1253)
com.sap.sailing.domain.tracking.impl.TrackedRaceImpl.getWind(TrackedRaceImpl.java:1208)
com.sap.sailing.domain.tracking.impl.TrackedRaceImpl.getWind(TrackedRaceImpl.java:1203)
com.sap.sailing.domain.tracking.impl.TrackedRaceImpl.getTack(TrackedRaceImpl.java:1815)
com.sap.sailing.domain.tracking.impl.TrackedRaceImpl.createManeuverFromGroupOfCourseChanges(TrackedRaceImpl.java:2104)
com.sap.sailing.domain.tracking.impl.TrackedRaceImpl.groupChangesInSameDirectionIntoManeuvers(TrackedRaceImpl.java:2083)
com.sap.sailing.domain.tracking.impl.TrackedRaceImpl.detectManeuvers(TrackedRaceImpl.java:1959)
com.sap.sailing.domain.tracking.impl.TrackedRaceImpl.computeManeuvers(TrackedRaceImpl.java:1890)
com.sap.sailing.domain.tracking.impl.TrackedRaceImpl.access$4(TrackedRaceImpl.java:1854)
com.sap.sailing.domain.tracking.impl.TrackedRaceImpl$2.computeCacheUpdate(TrackedRaceImpl.java:405)
com.sap.sailing.domain.tracking.impl.TrackedRaceImpl$2.computeCacheUpdate(TrackedRaceImpl.java:1)
com.sap.sailing.util.SmartFutureCache$FutureTaskWithCancelBlocking.call(SmartFutureCache.java:320)
com.sap.sailing.util.SmartFutureCache$SettableCallable.call(SmartFutureCache.java:198)
java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334)
java.util.concurrent.FutureTask.run(FutureTask.java:166)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603)
java.lang.Thread.run(Thread.java:722)

The current readers are:
Thread[qtp1397325628-1230,5,main]
com.sap.sailing.util.impl.LockUtil.acquireLockVirtuallyOrActually(LockUtil.java:93)
com.sap.sailing.util.impl.LockUtil.lockForRead(LockUtil.java:82)
com.sap.sailing.domain.base.impl.CourseImpl.lockForRead(CourseImpl.java:84)
com.sap.sailing.domain.tracking.impl.DynamicTrackedRaceImpl.lockForRead(DynamicTrackedRaceImpl.java:512)
com.sap.sailing.domain.tracking.impl.TrackedRaceImpl.getTrackedLeg(TrackedRaceImpl.java:807)
com.sap.sailing.domain.tracking.impl.TrackedRaceImpl.clusterBearingsByLegType(TrackedRaceImpl.java:1681)
com.sap.sailing.domain.tracking.impl.TrackedRaceImpl.getEstimatedWindDirectionWithConfidence(TrackedRaceImpl.java:1611)
com.sap.sailing.domain.tracking.impl.TrackBasedEstimationWindTrackImpl.getEstimatedWindDirection(TrackBasedEstimationWindTrackImpl.java:447)
com.sap.sailing.domain.tracking.impl.TrackBasedEstimationWindTrackImpl.access$1(TrackBasedEstimationWindTrackImpl.java:430)
com.sap.sailing.domain.tracking.impl.TrackBasedEstimationWindTrackImpl$EstimatedWindFixesAsNavigableSet.getWindWithConfidence(TrackBasedEstimationWindTrackImpl.java:644)
com.sap.sailing.domain.tracking.impl.TrackBasedEstimationWindTrackImpl$EstimatedWindFixesAsNavigableSet.getWind(TrackBasedEstimationWindTrackImpl.java:639)
com.sap.sailing.domain.tracking.impl.VirtualWindFixesAsNavigableSet.floor(VirtualWindFixesAsNavigableSet.java:163)
com.sap.sailing.domain.tracking.impl.VirtualWindFixesAsNavigableSet$1.next(VirtualWindFixesAsNavigableSet.java:190)
com.sap.sailing.domain.tracking.impl.VirtualWindFixesAsNavigableSet$1.next(VirtualWindFixesAsNavigableSet.java:1)
com.sap.sailing.domain.tracking.impl.PartialNavigableSetView$FilteringIterator.advance(PartialNavigableSetView.java:64)
com.sap.sailing.domain.tracking.impl.PartialNavigableSetView$FilteringIterator.<init>(PartialNavigableSetView.java:57)
com.sap.sailing.domain.tracking.impl.PartialNavigableSetView.iterator(PartialNavigableSetView.java:319)
com.sap.sailing.domain.tracking.impl.TrackImpl.getFixesIterator(TrackImpl.java:252)
com.sap.sailing.server.gateway.impl.WindJsonGetServlet.getRelevantFixes(WindJsonGetServlet.java:98)
com.sap.sailing.server.gateway.impl.WindJsonGetServlet.getResult(WindJsonGetServlet.java:81)
com.sap.sailing.server.gateway.impl.WindJsonGetServlet.doGet(WindJsonGetServlet.java:73)
javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:547)
org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:480)
org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:119)
org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:483)
org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:227)
org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:941)
org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:409)
org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:186)
org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:875)
org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:117)
org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:250)
org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:149)
org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:110)
org.eclipse.jetty.server.Server.handle(Server.java:349)
org.eclipse.jetty.server.HttpConnection.handleRequest(HttpConnection.java:441)
org.eclipse.jetty.server.HttpConnection$RequestHandler.headerComplete(HttpConnection.java:919)
org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:582)
org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:218)
org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:51)
org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:586)
org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:44)
org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:598)
org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:533)
java.lang.Thread.run(Thread.java:722)

Trying again...
Jul 05, 2013 11:44:56 AM com.sap.sailing.util.impl.LockUtil lock
INFO: Couldn't acquire lock readLock VirtualWindTrackImpl for race 49FX Gold R10 in 5s in thread pool-27-thread-1 at java.lang.Thread.getStackTrace(Thread.java:1567)
com.sap.sailing.util.impl.LockUtil.getStackTrace(LockUtil.java:359)
com.sap.sailing.util.impl.LockUtil.getCurrentStackTrace(LockUtil.java:367)
com.sap.sailing.util.impl.LockUtil.lock(LockUtil.java:389)
com.sap.sailing.util.impl.LockUtil.acquireLockVirtuallyOrActually(LockUtil.java:106)
com.sap.sailing.util.impl.LockUtil.lockForRead(LockUtil.java:82)
com.sap.sailing.domain.tracking.impl.TrackImpl.lockForRead(TrackImpl.java:66)
com.sap.sailing.domain.tracking.impl.TrackBasedEstimationWindTrackImpl.getAveragedWindUnsynchronized(TrackBasedEstimationWindTrackImpl.java:570)
com.sap.sailing.domain.tracking.impl.VirtualWindTrackImpl.getAveragedWindWithConfidence(VirtualWindTrackImpl.java:84)
com.sap.sailing.domain.tracking.impl.TrackedRaceImpl.getWindWithConfidence(TrackedRaceImpl.java:1253)
com.sap.sailing.domain.tracking.impl.TrackedRaceImpl.getWind(TrackedRaceImpl.java:1208)
com.sap.sailing.domain.tracking.impl.TrackedRaceImpl.getWind(TrackedRaceImpl.java:1203)
com.sap.sailing.domain.tracking.impl.TrackedRaceImpl.getTack(TrackedRaceImpl.java:1815)
com.sap.sailing.domain.tracking.impl.TrackedRaceImpl.createManeuverFromGroupOfCourseChanges(TrackedRaceImpl.java:2104)
com.sap.sailing.domain.tracking.impl.TrackedRaceImpl.groupChangesInSameDirectionIntoManeuvers(TrackedRaceImpl.java:2083)
com.sap.sailing.domain.tracking.impl.TrackedRaceImpl.detectManeuvers(TrackedRaceImpl.java:1959)
com.sap.sailing.domain.tracking.impl.TrackedRaceImpl.computeManeuvers(TrackedRaceImpl.java:1890)
com.sap.sailing.domain.tracking.impl.TrackedRaceImpl.access$4(TrackedRaceImpl.java:1854)
com.sap.sailing.domain.tracking.impl.TrackedRaceImpl$2.computeCacheUpdate(TrackedRaceImpl.java:405)
com.sap.sailing.domain.tracking.impl.TrackedRaceImpl$2.computeCacheUpdate(TrackedRaceImpl.java:1)
com.sap.sailing.util.SmartFutureCache$FutureTaskWithCancelBlocking.call(SmartFutureCache.java:320)
com.sap.sailing.util.SmartFutureCache$SettableCallable.call(SmartFutureCache.java:198)
java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334)
java.util.concurrent.FutureTask.run(FutureTask.java:166)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603)
java.lang.Thread.run(Thread.java:722)

The current readers are:
Thread[qtp1397325628-1230,5,main]
com.sap.sailing.util.impl.LockUtil.acquireLockVirtuallyOrActually(LockUtil.java:93)
com.sap.sailing.util.impl.LockUtil.lockForRead(LockUtil.java:82)
com.sap.sailing.domain.base.impl.CourseImpl.lockForRead(CourseImpl.java:84)
com.sap.sailing.domain.tracking.impl.DynamicTrackedRaceImpl.lockForRead(DynamicTrackedRaceImpl.java:512)
com.sap.sailing.domain.tracking.impl.TrackedRaceImpl.getTrackedLeg(TrackedRaceImpl.java:807)
com.sap.sailing.domain.tracking.impl.TrackedRaceImpl.clusterBearingsByLegType(TrackedRaceImpl.java:1681)
com.sap.sailing.domain.tracking.impl.TrackedRaceImpl.getEstimatedWindDirectionWithConfidence(TrackedRaceImpl.java:1611)
com.sap.sailing.domain.tracking.impl.TrackBasedEstimationWindTrackImpl.getEstimatedWindDirection(TrackBasedEstimationWindTrackImpl.java:447)
com.sap.sailing.domain.tracking.impl.TrackBasedEstimationWindTrackImpl.access$1(TrackBasedEstimationWindTrackImpl.java:430)
com.sap.sailing.domain.tracking.impl.TrackBasedEstimationWindTrackImpl$EstimatedWindFixesAsNavigableSet.getWindWithConfidence(TrackBasedEstimationWindTrackImpl.java:644)
com.sap.sailing.domain.tracking.impl.TrackBasedEstimationWindTrackImpl$EstimatedWindFixesAsNavigableSet.getWind(TrackBasedEstimationWindTrackImpl.java:639)
com.sap.sailing.domain.tracking.impl.VirtualWindFixesAsNavigableSet.floor(VirtualWindFixesAsNavigableSet.java:163)
com.sap.sailing.domain.tracking.impl.VirtualWindFixesAsNavigableSet$1.next(VirtualWindFixesAsNavigableSet.java:190)
com.sap.sailing.domain.tracking.impl.VirtualWindFixesAsNavigableSet$1.next(VirtualWindFixesAsNavigableSet.java:1)
com.sap.sailing.domain.tracking.impl.PartialNavigableSetView$FilteringIterator.advance(PartialNavigableSetView.java:64)
com.sap.sailing.domain.tracking.impl.PartialNavigableSetView$FilteringIterator.<init>(PartialNavigableSetView.java:57)
com.sap.sailing.domain.tracking.impl.PartialNavigableSetView.iterator(PartialNavigableSetView.java:319)
com.sap.sailing.domain.tracking.impl.TrackImpl.getFixesIterator(TrackImpl.java:252)
com.sap.sailing.server.gateway.impl.WindJsonGetServlet.getRelevantFixes(WindJsonGetServlet.java:98)
com.sap.sailing.server.gateway.impl.WindJsonGetServlet.getResult(WindJsonGetServlet.java:81)
com.sap.sailing.server.gateway.impl.WindJsonGetServlet.doGet(WindJsonGetServlet.java:73)
javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:547)
org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:480)
org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:119)
org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:483)
org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:227)
org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:941)
org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:409)
org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:186)
org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:875)
org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:117)
org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:250)
org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:149)
org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:110)
org.eclipse.jetty.server.Server.handle(Server.java:349)
org.eclipse.jetty.server.HttpConnection.handleRequest(HttpConnection.java:441)
org.eclipse.jetty.server.HttpConnection$RequestHandler.headerComplete(HttpConnection.java:919)
org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:582)
org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:218)
org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:51)
org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:586)
org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:44)
org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:598)
org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:533)
java.lang.Thread.run(Thread.java:722)

**Comment by aksajhfduwafe** [comment]
**@axeluhl** commented:

Created attachment 152
Log excerpt documenting the situation

[deadlock.gz](https://github.com/aksajhfduwafe/bugzilla-to-github-issues-test-attachments/raw/main/1483/152_deadlock.gz) — Log excerpt documenting the situation (application/octet-stream, 661314 bytes)

**Comment by aksajhfduwafe** [comment]
**@axeluhl** commented:

But nothing in the log suggests a true deadlock. Either it's varying threads, or it's threads caught in a location that is less than suspicious, with no "synchronized" and no lockForRead/Write anywhere near.

I suppose that the server was just under heavy load. With three sending wind units, starting to track new races and many client requests going on, most likely the long-standing locks would have unraveled by themselves had we only waited for a bit longer.

**Comment by aksajhfduwafe** [comment]
*@axeluhl* changed status from **NEW** to **RESOLVED** (WORKSFORME)
