### ISSUE TITLE
Make leaderboard calculation robust against NoWindException/NoWindError and empty course or course with undefined positions

### ISSUE THREAD

**Issue by aksajhfduwafe** [aksajhfduwafe/bugzilla-to-github-issues-test#1561]
| Field | Value |
|---|---|
| **Reporter** | @axeluhl |
| **Assignee** | @axeluhl |
| **Product** | Sailing Race Analytics |
| **Component** | Server |
| **Version** | unspecified |
| **Hardware** | All |
| **OS** | All |
| **Severity** | normal |
| **Priority** | P2 |
| **CC (unmapped)** | Simon Pamies (`s.pamies@the-placeholder-company.com`) |
| **Created** | 2013-10-14T23:48:38Z |
| **Original Bug** | [Bug 1561](https://bugzilla.sapsailing.com/bugzilla/show_bug.cgi?id=1561) |

---

Use an ESS race without loading wind data and try to get a leaderboard display. Try the same for a race with an empty course or with a course where no mark tracks have been recorded and make sure no exceptions bubble all the way up. It's okay to display empty columns with no values when they cannot be computed.

**Comment by aksajhfduwafe** [comment]
**@axeluhl** commented:

This entails calculating the rank differently when windward distance to leader isn't available. This would then need to resort to along-track distance to leader instead.

**Comment by aksajhfduwafe** [comment]
**@axeluhl** commented:

The next one is this:

Caused by: com.sap.sailing.domain.common.NoWindException: Need to know wind direction in race Race 2 to determine whether leg RC-Black Conical -> Red is an upwind or downwind leg
	at com.sap.sailing.domain.tracking.impl.TrackedLegImpl.getLegType(TrackedLegImpl.java:154)
	at com.sap.sailing.domain.leaderboard.impl.AbstractSimpleLeaderboardImpl.createLegEntry(AbstractSimpleLeaderboardImpl.java:1600)
	at com.sap.sailing.domain.leaderboard.impl.AbstractSimpleLeaderboardImpl.calculateRaceDetails(AbstractSimpleLeaderboardImpl.java:1561)
	at com.sap.sailing.domain.leaderboard.impl.AbstractSimpleLeaderboardImpl.getRaceDetails(AbstractSimpleLeaderboardImpl.java:1510)
	at com.sap.sailing.domain.leaderboard.impl.AbstractSimpleLeaderboardImpl.getLeaderboardEntryDTO(AbstractSimpleLeaderboardImpl.java:1385)
	at com.sap.sailing.domain.leaderboard.impl.AbstractSimpleLeaderboardImpl.lambda$1(AbstractSimpleLeaderboardImpl.java:1275)
	... 5 more

**Comment by aksajhfduwafe** [comment]
*Subscribing participants (reporter + CC):*

@fmittag @jens-rommel

*Unmapped (no GitHub account known):* Simon Pamies (`s.pamies@the-placeholder-company.com`)
