### ISSUE TITLE
Make the data mining tests runnable on the Hudson

### ISSUE THREAD

**Issue by aksajhfduwafe** [aksajhfduwafe/bugzilla-to-github-issues-test#1721]
| Field | Value |
|---|---|
| **Reporter** | @LennartH |
| **Assignee** | @LennartH |
| **Product** | Sailing Race Analytics |
| **Component** | DataMining |
| **Version** | unspecified |
| **Hardware** | PC |
| **OS** | Windows |
| **Severity** | normal |
| **Priority** | P1 |
| **Created** | 2014-01-22T18:44:24Z |
| **Original Bug** | [Bug 1721](https://bugzilla.sapsailing.com/bugzilla/show_bug.cgi?id=1721) |

---

The execution of the data mining tests fail, because the tests aren't set up correctly.

I already tried to move all inner classes to their own files and checked that no class name matches *Test or Test*, that is no test class. But the test still fail on the Hudson.

**Comment by aksajhfduwafe** [comment]
**@axeluhl** commented:

See http://jira.codehaus.org/browse/SUREFIRE-825.

**Comment by aksajhfduwafe** [comment]
**@axeluhl** commented:

Attempting a fix according to comment 1 (on this issue). The code in Junit4TestChecker grabs the following annotation classes:

38    {
39        this.junitClass = getJUnitClass( testClassLoader, junit.framework.Test.class.getName() );
40        this.runWith = getJUnitClass( testClassLoader, org.junit.runner.RunWith.class.getName() );
41    }

If the runWith annotation is not found, this will later lead to the NPE:

56        Annotation runWithAnnotation = testClass.getAnnotation( runWith );

With Class.getAnnotation(Class):

    public <A extends Annotation> A getAnnotation(Class<A> annotationClass) {
        if (annotationClass == null)
            throw new NullPointerException();

        initAnnotationsIfNecessary();
        return (A) annotations.get(annotationClass);
    }

So if the RunWith class isn't found, e.g., because of lack of import of the org.junit.runner package, a NullPointerException will be thrown by Class.getAnnotation(...). Adding org.junit.runner to the imported packages sounds like a promising potential fix.

**Comment by aksajhfduwafe** [comment]
**@axeluhl** commented:

Here is, by the way, the original error message and stack trace from the Hudson build:

Command-line arguments:  -data /home/hudson/repo/jobs/SAPSailingAnalytics-dataMining/workspace/java/com.sap.sailing.datamining.test/bin/work/data -app
lication org.eclipse.tycho.surefire.osgibooter.headlesstest -testproperties /home/hudson/repo/jobs/SAPSailingAnalytics-dataMining/workspace/java/com.s
ap.sailing.datamining.test/bin/surefire.properties

!ENTRY org.eclipse.osgi 4 0 2014-01-23 08:33:30.958
!MESSAGE Application error
!STACK 1
org.apache.maven.surefire.util.SurefireReflectionException: java.lang.reflect.InvocationTargetException; nested exception is java.lang.reflect.Invocat
ionTargetException: null
java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:601)
        at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:164)
        at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:110)
        at org.apache.maven.surefire.booter.SurefireStarter.invokeProvider(SurefireStarter.java:175)
        at org.apache.maven.surefire.booter.SurefireStarter.runSuitesInProcess(SurefireStarter.java:123)
        at org.eclipse.tycho.surefire.osgibooter.OsgiSurefireBooter.run(OsgiSurefireBooter.java:85)
        at org.eclipse.tycho.surefire.osgibooter.HeadlessTestApplication.run(HeadlessTestApplication.java:21)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:601)
        at org.eclipse.equinox.internal.app.EclipseAppContainer.callMethodWithException(EclipseAppContainer.java:587)
        at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:198)
        at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:110)
        at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:79)
        at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:354)
        at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:181)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:601)
        at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:636)
        at org.eclipse.equinox.launcher.Main.basicRun(Main.java:591)
        at org.eclipse.equinox.launcher.Main.run(Main.java:1450)
        at org.eclipse.equinox.launcher.Main.main(Main.java:1426)
Caused by: java.lang.NullPointerException
        at java.lang.Class.getAnnotation(Class.java:3046)
        at org.apache.maven.surefire.common.junit4.JUnit4TestChecker.isValidJUnit4Test(JUnit4TestChecker.java:63)
        at org.apache.maven.surefire.common.junit4.JUnit4TestChecker.accept(JUnit4TestChecker.java:52)
        at org.apache.maven.surefire.util.DefaultDirectoryScanner.locateTestClasses(DefaultDirectoryScanner.java:80)
        at org.apache.maven.surefire.junit4.JUnit4Provider.scanClassPath(JUnit4Provider.java:174)
        at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:83)
        ... 28 more
