### ISSUE TITLE
NPE when trying to correct leaderboard scores

### ISSUE THREAD

**Issue by aksajhfduwafe** [aksajhfduwafe/bugzilla-to-github-issues-test#1722]
| Field | Value |
|---|---|
| **Reporter** | Frederik Petersen (`bugz@fpetersen.eu`) |
| **Assignee** | @axeluhl |
| **Product** | Sailing Race Analytics |
| **Component** | Server |
| **Version** | unspecified |
| **Hardware** | PC |
| **OS** | Windows |
| **Severity** | normal |
| **Priority** | P1 |
| **CC (unmapped)** | Simon Pamies (`s.pamies@the-placeholder-company.com`) |
| **Created** | 2014-01-23T16:40:52Z |
| **Original Bug** | [Bug 1722](https://bugzilla.sapsailing.com/bugzilla/show_bug.cgi?id=1722) |

---

I get this NPE when opening the Leaderboard editing panel (newest master (fa3144bd5ffb94f11193db0fe37dcbfa563ddfb8)):

17:35:01.022 [ERROR] [com.sap.sailing.gwt.ui.LeaderboardEditing] Uncaught exception escaped
java.lang.NullPointerException: null
    at com.google.gwt.i18n.client.NumberFormat.format(NumberFormat.java:966)
    at com.sap.sailing.gwt.ui.leaderboardedit.EditableLeaderboardPanel$UncorrectedNetPointsViewProvider.getValue(EditableLeaderboardPanel.java:385)
    at com.sap.sailing.gwt.ui.leaderboardedit.EditableLeaderboardPanel$UncorrectedNetPointsViewProvider.getValue(EditableLeaderboardPanel.java:1)
    at com.google.gwt.cell.client.CompositeCell.render(CompositeCell.java:210)
    at com.sap.sailing.gwt.ui.leaderboardedit.EditableLeaderboardPanel$CompositeCellRememberingRenderingContextAndObject.render(EditableLeaderboardPanel.java:256)
    at com.sap.sailing.gwt.ui.leaderboardedit.EditableLeaderboardPanel$CompositeCellRememberingRenderingContextAndObject.render(EditableLeaderboardPanel.java:1)
    at com.google.gwt.cell.client.CompositeCell.render(CompositeCell.java:151)
    at com.sap.sailing.gwt.ui.leaderboardedit.EditableLeaderboardPanel$CompositeCellRememberingRenderingContextAndObject.render(EditableLeaderboardPanel.java:243)
    at com.sap.sailing.gwt.ui.leaderboardedit.EditableLeaderboardPanel$CompositeCellRememberingRenderingContextAndObject.render(EditableLeaderboardPanel.java:1)
    at com.google.gwt.user.cellview.client.Column.render(Column.java:165)
    at com.sap.sailing.gwt.ui.leaderboard.ExpandableSortableColumn.defaultRender(ExpandableSortableColumn.java:228)
    at com.sap.sailing.gwt.ui.leaderboardedit.EditableLeaderboardPanel$EditableRaceColumn.render(EditableLeaderboardPanel.java:283)
    at com.sap.sailing.gwt.ui.leaderboard.LeaderboardPanel$RaceColumn.render(LeaderboardPanel.java:1)
    at com.google.gwt.user.cellview.client.AbstractCellTableBuilder.renderCell(AbstractCellTableBuilder.java:206)
    at com.google.gwt.user.cellview.client.DefaultCellTableBuilder.buildRowImpl(DefaultCellTableBuilder.java:129)
    at com.sap.sailing.gwt.ui.leaderboard.SortedCellTableWithStylableHeaders$1.buildRowImpl(SortedCellTableWithStylableHeaders.java:32)
    at com.google.gwt.user.cellview.client.AbstractCellTableBuilder.buildRow(AbstractCellTableBuilder.java:87)
    at com.google.gwt.user.cellview.client.AbstractCellTable.buildRowValues(AbstractCellTable.java:2357)
    at com.google.gwt.user.cellview.client.AbstractCellTable.replaceAllChildren(AbstractCellTable.java:2158)
    at com.google.gwt.user.cellview.client.AbstractHasData$View.replaceAllChildren(AbstractHasData.java:245)
    at com.google.gwt.user.cellview.client.HasDataPresenter.resolvePendingState(HasDataPresenter.java:1351)
    at com.google.gwt.user.cellview.client.HasDataPresenter.access$3(HasDataPresenter.java:1062)
    at com.google.gwt.user.cellview.client.HasDataPresenter$2.execute(HasDataPresenter.java:984)
    at com.google.gwt.core.client.impl.SchedulerImpl$Task$.executeScheduled$(SchedulerImpl.java:50)
    at com.google.gwt.core.client.impl.SchedulerImpl.runScheduledTasks(SchedulerImpl.java:180)
    at com.google.gwt.core.client.impl.SchedulerImpl.flushFinallyCommands(SchedulerImpl.java:279)
    at com.google.gwt.core.client.impl.Impl.exit(Impl.java:266)
    at com.google.gwt.core.client.impl.Impl.entry0(Impl.java:257)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at com.google.gwt.dev.shell.MethodAdaptor.invoke(MethodAdaptor.java:103)
    at com.google.gwt.dev.shell.MethodDispatch.invoke(MethodDispatch.java:71)
    at com.google.gwt.dev.shell.OophmSessionHandler.invoke(OophmSessionHandler.java:172)
    at com.google.gwt.dev.shell.BrowserChannelServer.reactToMessages(BrowserChannelServer.java:293)
    at com.google.gwt.dev.shell.BrowserChannelServer.processConnection(BrowserChannelServer.java:547)
    at com.google.gwt.dev.shell.BrowserChannelServer.run(BrowserChannelServer.java:364)
    at java.lang.Thread.run(Thread.java:744)

**Comment by aksajhfduwafe** [comment]
**@axeluhl** commented:

Scores can be null, and the new UncorrectedNetPointsViewProvider class doesn't deal with this properly. Will first try to create a failing Selenium test for this. We had more than one occasion in the past where all of a sudden a simple change killed our ability to correct scores which at an event is a major showstopper.

**Comment by aksajhfduwafe** [comment]
**@axeluhl** commented:

Because it's a UI-related problem. Please check the stack trace. The problem occurs in the UI when the renderer is finding a null result. The problems with the LeaderboardEditing page have largely been UI problems that a server-side JUnit test would not be able to catch.

**Comment by aksajhfduwafe** [comment]
*@axeluhl* changed status from **ASSIGNED** to **RESOLVED** (FIXED)
