### ISSUE TITLE
RaceCommittee App crashes when trying to load competitors during end of race

### ISSUE THREAD

**Issue by aksajhfduwafe** [aksajhfduwafe/bugzilla-to-github-issues-test#1788]
| Field | Value |
|---|---|
| **Reporter** | Simon Pamies (`s.pamies@the-placeholder-company.com`) |
| **Assignee** | Simon Pamies (`s.pamies@the-placeholder-company.com`) |
| **Product** | Sailing Race Analytics |
| **Component** | Race Management |
| **Version** | unspecified |
| **Hardware** | All |
| **OS** | All |
| **Severity** | blocker |
| **Priority** | P1 |
| **CC (unmapped)** | Lukas Niemeier (`lukas.niemeier@student.hpi.uni-potsdam.de`) |
| **Created** | 2014-02-20T08:12:04Z |
| **Original Bug** | [Bug 1788](https://bugzilla.sapsailing.com/bugzilla/show_bug.cgi?id=1788) |

---

02-20 16:05:31.427: E/com.sap.sailing.racecommittee.app.data.loaders.OnlineDataLoader(16616): com.sap.sailing.server.gateway.deserialization.JsonDeserializationException: java.lang.NullPointerException
02-20 16:05:31.427: E/com.sap.sailing.racecommittee.app.data.loaders.OnlineDataLoader(16616): 	at com.sap.sailing.server.gateway.deserialization.impl.CompetitorJsonDeserializer.deserialize(CompetitorJsonDeserializer.java:73)
02-20 16:05:31.427: E/com.sap.sailing.racecommittee.app.data.loaders.OnlineDataLoader(16616): 	at com.sap.sailing.server.gateway.deserialization.impl.CompetitorJsonDeserializer.deserialize(CompetitorJsonDeserializer.java:1)
02-20 16:05:31.427: E/com.sap.sailing.racecommittee.app.data.loaders.OnlineDataLoader(16616): 	at com.sap.sailing.racecommittee.app.data.parsers.CompetitorsDataParser.parse(CompetitorsDataParser.java:30)
02-20 16:05:31.427: E/com.sap.sailing.racecommittee.app.data.loaders.OnlineDataLoader(16616): 	at com.sap.sailing.racecommittee.app.data.parsers.CompetitorsDataParser.parse(CompetitorsDataParser.java:1)
02-20 16:05:31.427: E/com.sap.sailing.racecommittee.app.data.loaders.OnlineDataLoader(16616): 	at com.sap.sailing.racecommittee.app.data.loaders.OnlineDataLoader.loadDataInBackground(OnlineDataLoader.java:102)
02-20 16:05:31.427: E/com.sap.sailing.racecommittee.app.data.loaders.OnlineDataLoader(16616): 	at com.sap.sailing.racecommittee.app.data.loaders.OnlineDataLoader.loadInBackground(OnlineDataLoader.java:90)
02-20 16:05:31.427: E/com.sap.sailing.racecommittee.app.data.loaders.OnlineDataLoader(16616): 	at com.sap.sailing.racecommittee.app.data.loaders.OnlineDataLoader.loadInBackground(OnlineDataLoader.java:1)
02-20 16:05:31.427: E/com.sap.sailing.racecommittee.app.data.loaders.OnlineDataLoader(16616): 	at android.content.AsyncTaskLoader.onLoadInBackground(AsyncTaskLoader.java:255)
02-20 16:05:31.427: E/com.sap.sailing.racecommittee.app.data.loaders.OnlineDataLoader(16616): 	at android.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:66)
02-20 16:05:31.427: E/com.sap.sailing.racecommittee.app.data.loaders.OnlineDataLoader(16616): 	at android.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:55)
02-20 16:05:31.427: E/com.sap.sailing.racecommittee.app.data.loaders.OnlineDataLoader(16616): 	at android.os.AsyncTask$2.call(AsyncTask.java:264)
02-20 16:05:31.427: E/com.sap.sailing.racecommittee.app.data.loaders.OnlineDataLoader(16616): 	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:305)
02-20 16:05:31.427: E/com.sap.sailing.racecommittee.app.data.loaders.OnlineDataLoader(16616): 	at java.util.concurrent.FutureTask.run(FutureTask.java:137)
02-20 16:05:31.427: E/com.sap.sailing.racecommittee.app.data.loaders.OnlineDataLoader(16616): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
02-20 16:05:31.427: E/com.sap.sailing.racecommittee.app.data.loaders.OnlineDataLoader(16616): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
02-20 16:05:31.427: E/com.sap.sailing.racecommittee.app.data.loaders.OnlineDataLoader(16616): 	at java.lang.Thread.run(Thread.java:856)
02-20 16:05:31.427: E/com.sap.sailing.racecommittee.app.data.loaders.OnlineDataLoader(16616): Caused by: java.lang.NullPointerException
02-20 16:05:31.427: E/com.sap.sailing.racecommittee.app.data.loaders.OnlineDataLoader(16616): 	at com.sap.sailing.domain.base.impl.TransientCompetitorStoreImpl.getOrCreateCompetitor(TransientCompetitorStoreImpl.java:88)
02-20 16:05:31.427: E/com.sap.sailing.racecommittee.app.data.loaders.OnlineDataLoader(16616): 	at com.sap.sailing.server.gateway.deserialization.impl.CompetitorJsonDeserializer.deserialize(CompetitorJsonDeserializer.java:70)
02-20 16:05:31.427: E/com.sap.sailing.racecommittee.app.data.loaders.OnlineDataLoader(16616): 	... 15 more

**Comment by aksajhfduwafe** [comment]
*Simon Pamies (`s.pamies@the-placeholder-company.com`)* changed status from **NEW** to **RESOLVED** (FIXED)

**Comment by aksajhfduwafe** [comment]
*Subscribing participants (reporter + CC):*

@axeluhl

*Unmapped (no GitHub account known):* Lukas Niemeier (`lukas.niemeier@student.hpi.uni-potsdam.de`), Simon Pamies (`s.pamies@the-placeholder-company.com`)
