### ISSUE TITLE
Unknown GWT internal exception occuring during RaceBoard loading

### ISSUE THREAD

**Issue by aksajhfduwafe** [aksajhfduwafe/bugzilla-to-github-issues-test#2141]
| Field | Value |
|---|---|
| **Reporter** | Simon Pamies (`s.pamies@the-placeholder-company.com`) |
| **Assignee** | Simon Pamies (`s.pamies@the-placeholder-company.com`) |
| **Product** | Sailing Race Analytics |
| **Component** | Frontend |
| **Version** | unspecified |
| **Hardware** | All |
| **OS** | All |
| **Severity** | normal |
| **Priority** | P1 |
| **Created** | 2014-08-07T16:52:30Z |
| **Original Bug** | [Bug 2141](https://bugzilla.sapsailing.com/bugzilla/show_bug.cgi?id=2141) |

---

18:37:08.367 [ERROR] [com.sap.sailing.gwt.ui.RaceBoard] Uncaught exception escaped

com.google.gwt.core.client.JavaScriptException: (TypeError) @com.google.gwt.core.client.impl.Impl::apply(Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;)([JavaScript object(1040), JavaScript object(1039), JavaScript object(1050)]): undefined is not a function
    at com.google.gwt.dev.shell.BrowserChannelServer.invokeJavascript(BrowserChannelServer.java:249)
    at com.google.gwt.dev.shell.ModuleSpaceOOPHM.doInvoke(ModuleSpaceOOPHM.java:136)
    at com.google.gwt.dev.shell.ModuleSpace.invokeNative(ModuleSpace.java:576)
    at com.google.gwt.dev.shell.ModuleSpace.invokeNativeObject(ModuleSpace.java:284)
    at com.google.gwt.dev.shell.JavaScriptHost.invokeNativeObject(JavaScriptHost.java:91)
    at com.google.gwt.core.client.impl.Impl.apply(Impl.java)
    at com.google.gwt.core.client.impl.Impl.entry0(Impl.java:356)
    at sun.reflect.GeneratedMethodAccessor76.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:601)
    at com.google.gwt.dev.shell.MethodAdaptor.invoke(MethodAdaptor.java:103)
    at com.google.gwt.dev.shell.MethodDispatch.invoke(MethodDispatch.java:71)
    at com.google.gwt.dev.shell.OophmSessionHandler.invoke(OophmSessionHandler.java:172)
    at com.google.gwt.dev.shell.BrowserChannelServer.reactToMessages(BrowserChannelServer.java:293)
    at com.google.gwt.dev.shell.BrowserChannelServer.processConnection(BrowserChannelServer.java:547)
    at com.google.gwt.dev.shell.BrowserChannelServer.run(BrowserChannelServer.java:364)
    at java.lang.Thread.run(Thread.java:722)

**Comment by aksajhfduwafe** [comment]
**Simon Pamies (`s.pamies@the-placeholder-company.com`)** commented:

No further stack trace available.

**Comment by aksajhfduwafe** [comment]
**@axeluhl** commented:

The root cause was the BoundsUtil that was used with a null-valued maps.getBounds(), throwing a masked NPE. Fixed by commit e113796fbfd854e581b5844c72b16af21b62de3d.

**Comment by aksajhfduwafe** [comment]
*@axeluhl* changed status from **NEW** to **RESOLVED** (FIXED)

**Comment by aksajhfduwafe** [comment]
*Subscribing participants (reporter + CC):*

@axeluhl

*Unmapped (no GitHub account known):* Simon Pamies (`s.pamies@the-placeholder-company.com`)
