### ISSUE TITLE
Problem with transitive replication

### ISSUE THREAD

**Issue by aksajhfduwafe** [aksajhfduwafe/bugzilla-to-github-issues-test#2600]
| Field | Value |
|---|---|
| **Reporter** | @axeluhl |
| **Assignee** | @axeluhl |
| **Product** | Sailing Race Analytics |
| **Component** | Server |
| **Version** | unspecified |
| **Hardware** | All |
| **OS** | All |
| **Severity** | normal |
| **Priority** | P2 |
| **CC (unmapped)** | Simon Pamies (`s.pamies@the-placeholder-company.com`) |
| **Created** | 2015-02-05T10:54:48Z |
| **Original Bug** | [Bug 2600](https://bugzilla.sapsailing.com/bugzilla/show_bug.cgi?id=2600) |

---

During the first day in Singapore we face some serious issues with transitive replication. The primary replica worked nicely and reliably. Replicas replicating off this primary replica all had trouble. In particular, it seems that race-to-leaderboard-column-associations weren't replicated properly. All transitive replica only had R6 and R8 of that day linked. Refreshing the tracked races loaded state showed that instead of ten races loaded the set of races loaded went down to R6 and R8, the two ones linked to the leaderboard.

So, for some reasons (perhaps re-loading the races on the master?) the transitive replicas got out of sync, but the primary replica got it right.

As a consequence of the races that disappeared, the GPS positions replicated to the transitive replicas had to throw the following exception:

java.lang.NullPointerException
        at com.sap.sailing.server.operationaltransformation.UpdateTrackedRaceStatus.internalApplyTo(UpdateTrackedRaceStatus.java:21)
        at com.sap.sailing.server.operationaltransformation.UpdateTrackedRaceStatus.internalApplyTo(UpdateTrackedRaceStatus.java:1)
        at com.sap.sse.replication.impl.ReplicableWithObjectInputStream.applyReplicated(ReplicableWithObjectInputStream.java:229)
        at com.sap.sse.replication.Replicable.applyReceivedReplicated(Replicable.java:178)
        at com.sap.sse.replication.impl.ReplicationReceiver$1.run(ReplicationReceiver.java:304)
        at com.sap.sse.replication.impl.ReplicationReceiver.apply(ReplicationReceiver.java:308)
        at com.sap.sse.replication.impl.ReplicationReceiver.applyOrQueue(ReplicationReceiver.java:290)
        at com.sap.sse.replication.impl.ReplicationReceiver.readOperationAndApplyOrQueueIt(ReplicationReceiver.java:276)
        at com.sap.sse.replication.impl.ReplicationReceiver.run(ReplicationReceiver.java:183)
        at java.lang.Thread.run(Thread.java:745)

**Comment by aksajhfduwafe** [comment]
**@axeluhl** commented:

The master writes the operations to the Rabbit queue more or less in the order in which they are executed. The primary replica probably uses the prarallel executor.

**Comment by aksajhfduwafe** [comment]
*@axeluhl* changed status from **ASSIGNED** to **RESOLVED** (FIXED)
