### ISSUE TITLE
Can't resolve GPSFixMongoHandler and can't load smartphone GPS Fixes

### ISSUE THREAD

**Issue by aksajhfduwafe** [aksajhfduwafe/bugzilla-to-github-issues-test#2767]
| Field | Value |
|---|---|
| **Reporter** | @axeluhl |
| **Assignee** | @axeluhl |
| **Product** | Sailing Race Analytics |
| **Component** | Smartphone Tracking |
| **Version** | unspecified |
| **Hardware** | All |
| **OS** | All |
| **Severity** | normal |
| **Priority** | P1 |
| **CC (unmapped)** | Jan Broß (`jan.bross@arcor.de`) |
| **Created** | 2015-04-23T06:29:24Z |
| **Original Bug** | [Bug 2767](https://bugzilla.sapsailing.com/bugzilla/show_bug.cgi?id=2767) |

---

WARNING: Could not load track for Dan Nowlan
com.sap.sse.common.NoCorrespondingServiceRegisteredException: Could not find service (Service: GPSFixMongoHandler, Type: com.sap.sailing.domain.tracking.impl.GPSFixMovingImpl)
	at com.sap.sse.osgi.CachedOsgiTypeBasedServiceFinder.findService(CachedOsgiTypeBasedServiceFinder.java:45)
	at com.sap.sailing.domain.persistence.racelog.tracking.impl.MongoGPSFixStoreImpl.loadGPSFix(MongoGPSFixStoreImpl.java:77)
	at com.sap.sailing.domain.persistence.racelog.tracking.impl.MongoGPSFixStoreImpl.loadTrack(MongoGPSFixStoreImpl.java:97)
	at com.sap.sailing.domain.persistence.racelog.tracking.impl.MongoGPSFixStoreImpl.loadCompetitorTrack(MongoGPSFixStoreImpl.java:115)
	at com.sap.sailing.domain.tracking.impl.TrackedRaceImpl$8.run(TrackedRaceImpl.java:2879)

The bundle registrations for those types of services at this point are:

{com.sap.sailing.domain.persistence.racelog.tracking.DeviceIdentifierMongoHandler}={type=smartphoneUUID, service.id=33, service.bundleid=23, service.scope=singleton}
  "Registered by bundle:" com.sap.sailing.domain.racelogtrackingadapter_1.0.0.201504222331 [23]
  "Bundles using service"
    com.sap.sailing.server_1.0.0.201504222331 [42]
{com.sap.sailing.server.gateway.serialization.racelog.tracking.DeviceIdentifierJsonHandler}={type=smartphoneUUID, service.id=34, service.bundleid=23, service.scope=singleton}
  "Registered by bundle:" com.sap.sailing.domain.racelogtrackingadapter_1.0.0.201504222331 [23]
  "Bundles using service"
    com.sap.sailing.server.gateway_1.0.0.201504222331 [43]
{com.sap.sailing.domain.racelogtracking.DeviceIdentifierStringSerializationHandler}={type=smartphoneUUID, service.id=35, service.bundleid=23, service.scope=singleton}
  "Registered by bundle:" com.sap.sailing.domain.racelogtrackingadapter_1.0.0.201504222331 [23]
  "Bundles using service"
    com.sap.sailing.gwt.ui_1.0.0.201504222331 [34]
{com.sap.sailing.domain.persistence.racelog.tracking.DeviceIdentifierMongoHandler}={type=PING, service.id=36, service.bundleid=23, service.scope=singleton}
  "Registered by bundle:" com.sap.sailing.domain.racelogtrackingadapter_1.0.0.201504222331 [23]
  "Bundles using service"
    com.sap.sailing.server_1.0.0.201504222331 [42]
{com.sap.sailing.server.gateway.serialization.racelog.tracking.DeviceIdentifierJsonHandler}={type=PING, service.id=37, service.bundleid=23, service.scope=singleton}
  "Registered by bundle:" com.sap.sailing.domain.racelogtrackingadapter_1.0.0.201504222331 [23]
  "Bundles using service"
    com.sap.sailing.server.gateway_1.0.0.201504222331 [43]
{com.sap.sailing.domain.persistence.racelog.tracking.DeviceIdentifierMongoHandler}={type=FILE, service.id=38, service.bundleid=23, service.scope=singleton}
  "Registered by bundle:" com.sap.sailing.domain.racelogtrackingadapter_1.0.0.201504222331 [23]
  "Bundles using service"
    com.sap.sailing.server_1.0.0.201504222331 [42]
{com.sap.sailing.server.gateway.serialization.racelog.tracking.DeviceIdentifierJsonHandler}={type=FILE, service.id=39, service.bundleid=23, service.scope=singleton}
  "Registered by bundle:" com.sap.sailing.domain.racelogtrackingadapter_1.0.0.201504222331 [23]
  "Bundles using service"
    com.sap.sailing.server.gateway_1.0.0.201504222331 [43]
{com.sap.sailing.domain.racelogtracking.DeviceIdentifierStringSerializationHandler}={type=FILE, service.id=40, service.bundleid=23, service.scope=singleton}
  "Registered by bundle:" com.sap.sailing.domain.racelogtrackingadapter_1.0.0.201504222331 [23]
  "Bundles using service"
    com.sap.sailing.gwt.ui_1.0.0.201504222331 [34]
{com.sap.sailing.server.gateway.serialization.racelog.tracking.GPSFixJsonHandler}={type=GPSFix, service.id=41, service.bundleid=23, service.scope=singleton}
  "Registered by bundle:" com.sap.sailing.domain.racelogtrackingadapter_1.0.0.201504222331 [23]
  "No bundles using service."
{com.sap.sailing.server.gateway.serialization.racelog.tracking.GPSFixJsonHandler}={type=GPSFixMoving, service.id=42, service.bundleid=23, service.scope=singleton}
  "Registered by bundle:" com.sap.sailing.domain.racelogtrackingadapter_1.0.0.201504222331 [23]
  "No bundles using service."
{com.sap.sailing.server.gateway.serialization.racelog.tracking.GPSFixJsonHandler}={type=GPSFixNmea, service.id=43, service.bundleid=23, service.scope=singleton}
  "Registered by bundle:" com.sap.sailing.domain.racelogtrackingadapter_1.0.0.201504222331 [23]
  "No bundles using service."
{com.sap.sailing.server.gateway.serialization.racelog.tracking.GPSFixJsonHandler}={type=GPSFixMovingNmea, service.id=44, service.bundleid=23, service.scope=singleton}
  "Registered by bundle:" com.sap.sailing.domain.racelogtrackingadapter_1.0.0.201504222331 [23]
  "No bundles using service."
{com.sap.sailing.domain.racelogtracking.RaceLogTrackingAdapterFactory}={service.id=45, service.bundleid=23, service.scope=singleton}
  "Registered by bundle:" com.sap.sailing.domain.racelogtrackingadapter_1.0.0.201504222331 [23]
  "Bundles using service"
    com.sap.sailing.gwt.ui_1.0.0.201504222331 [34]

**Comment by aksajhfduwafe** [comment]
**@axeluhl** commented:

Analysis: during the implemention of a solution for #489 (rotatable map) I moved GPSFix and GPSFixMoving together with their implementing classes from com.sap.sailing.domain.tracking.impl to com.sap.sailing.domain.common.tracking.impl so they are visible to the GWT clients and serializable. The database contains the fix  as fully-qualified class name:

	"GPSFIX_TYPE" : "com.sap.sailing.domain.tracking.impl.GPSFixMovingImpl"
	
This causes the service to not be found because it's registration with the OSGi registry in the Activator works like this:

	properties.put(TypeBasedServiceFinder.TYPE, GPSFixMovingImpl.class.getName());
	registrations.add(context.registerService(GPSFixMongoHandler.class,
                        new GPSFixMovingMongoHandlerImpl(racingEventService.getMongoObjectFactory(),
                                racingEventService.getDomainObjectFactory()), properties));
                                
which uses GPSFixMovingImpl.class.getName(), therefore the fully-qualified class name, as service property.

Using a fully-qualified class name in the DB of course has its obvious drawbacks, particular when moving or renaming the package or the class during a refactoring.

I see two options:

 1) Migrate the DB content so that fixes using the old FQCN then have the new FQCN
 2) Change the service registration so that the old FQCN is used explicitly (but will this work for new fixes being written? Probably not...)
 3) Register the service for both, old and new FQCN
 
I'll try 3) now.
