### ISSUE TITLE
Exceptions during polar / simulation calculations

### ISSUE THREAD

**Issue by aksajhfduwafe** [aksajhfduwafe/bugzilla-to-github-issues-test#2803]
| Field | Value |
|---|---|
| **Reporter** | @axeluhl |
| **Assignee** | @rocrv |
| **Product** | Sailing Race Analytics |
| **Component** | Server |
| **Version** | unspecified |
| **Hardware** | All |
| **OS** | All |
| **Severity** | normal |
| **Priority** | P1 |
| **CC (unmapped)** | Frederik Petersen (`bugz@fpetersen.eu`) |
| **Created** | 2015-05-01T08:02:40Z |
| **Original Bug** | [Bug 2803](https://bugzilla.sapsailing.com/bugzilla/show_bug.cgi?id=2803) |

---

SEVERE: SmartFutureCache.FutureTaskWithCancelBlocking.call
java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at com.sap.sailing.server.simulation.SimulationServiceImpl.getAllPaths(SimulationServiceImpl.java:444)
	at com.sap.sailing.server.simulation.SimulationServiceImpl.getAllPathsEvenTimed(SimulationServiceImpl.java:481)
	at com.sap.sailing.server.simulation.SimulationServiceImpl.computeSimulationResults(SimulationServiceImpl.java:405)
	at com.sap.sailing.server.simulation.SimulationServiceImpl$1.computeCacheUpdate(SimulationServiceImpl.java:86)
	at com.sap.sailing.server.simulation.SimulationServiceImpl$1.computeCacheUpdate(SimulationServiceImpl.java:1)
	at com.sap.sse.util.SmartFutureCache$FutureTaskWithCancelBlocking.call(SmartFutureCache.java:320)
	at com.sap.sse.util.SmartFutureCache$SettableCallable.call(SmartFutureCache.java:200)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
	at com.sap.sailing.simulator.impl.PolarDiagramBase.optimalDirectionsDownwind(PolarDiagramBase.java:766)
	at com.sap.sailing.simulator.impl.PathGeneratorTreeGrow360.getStep(PathGeneratorTreeGrow360.java:128)
	at com.sap.sailing.simulator.impl.PathGeneratorTreeGrow360.getPathCandWind(PathGeneratorTreeGrow360.java:220)
	at com.sap.sailing.simulator.impl.PathGeneratorTreeGrow360.getPath(PathGeneratorTreeGrow360.java:727)
	at com.sap.sailing.simulator.impl.SimulatorImpl.getPath(SimulatorImpl.java:58)
	at com.sap.sailing.server.simulation.SimulationServiceImpl.lambda$1(SimulationServiceImpl.java:428)
	at com.sap.sailing.server.simulation.SimulationServiceImpl$$Lambda$31/254510689.call(Unknown Source)
	... 4 more

May 01, 2015 7:59:40 AM com.sap.sse.util.SmartFutureCache get
SEVERE: get
java.util.concurrent.ExecutionException: java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at com.sap.sse.util.SmartFutureCache$FutureTaskWithCancelBlocking.get(SmartFutureCache.java:289)
	at com.sap.sse.util.SmartFutureCache.get(SmartFutureCache.java:652)
	at com.sap.sailing.server.simulation.SimulationServiceImpl.getSimulationResults(SimulationServiceImpl.java:299)
	at com.sap.sailing.gwt.ui.server.SailingServiceImpl.getSimulatorResults(SailingServiceImpl.java:1455)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.gwt.user.server.rpc.RPC.invokeAndEncodeResponse(RPC.java:587)
	at com.google.gwt.user.server.rpc.RemoteServiceServlet.processCall(RemoteServiceServlet.java:333)
	at com.google.gwt.user.server.rpc.RemoteServiceServlet.processCall(RemoteServiceServlet.java:303)
	at com.google.gwt.user.server.rpc.RemoteServiceServlet.processPost(RemoteServiceServlet.java:373)
	at com.google.gwt.user.server.rpc.AbstractRemoteServiceServlet.doPost(AbstractRemoteServiceServlet.java:62)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:769)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1667)
	at com.sap.sse.gwt.server.GWTCacheControlServletFilter.doFilter(GWTCacheControlServletFilter.java:42)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1650)
	at org.apache.shiro.web.servlet.AbstractShiroFilter.executeChain(AbstractShiroFilter.java:449)
	at org.apache.shiro.web.servlet.AbstractShiroFilter$1.call(AbstractShiroFilter.java:365)
	at org.apache.shiro.subject.support.SubjectCallable.doCall(SubjectCallable.java:90)
	at org.apache.shiro.subject.support.SubjectCallable.call(SubjectCallable.java:83)
	at org.apache.shiro.subject.support.DelegatingSubject.execute(DelegatingSubject.java:383)
	at org.apache.shiro.web.servlet.AbstractShiroFilter.doFilterInternal(AbstractShiroFilter.java:362)
	at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1650)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:583)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:553)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:223)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1125)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1059)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:215)
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:110)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.eclipse.jetty.server.Server.handle(Server.java:485)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:290)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:248)
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:606)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:535)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at com.sap.sse.util.SmartFutureCache$FutureTaskWithCancelBlocking.call(SmartFutureCache.java:368)
	at com.sap.sse.util.SmartFutureCache$SettableCallable.call(SmartFutureCache.java:200)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	... 1 more
Caused by: java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at com.sap.sailing.server.simulation.SimulationServiceImpl.getAllPaths(SimulationServiceImpl.java:444)
	at com.sap.sailing.server.simulation.SimulationServiceImpl.getAllPathsEvenTimed(SimulationServiceImpl.java:481)
	at com.sap.sailing.server.simulation.SimulationServiceImpl.computeSimulationResults(SimulationServiceImpl.java:405)
	at com.sap.sailing.server.simulation.SimulationServiceImpl$1.computeCacheUpdate(SimulationServiceImpl.java:86)
	at com.sap.sailing.server.simulation.SimulationServiceImpl$1.computeCacheUpdate(SimulationServiceImpl.java:1)
	at com.sap.sse.util.SmartFutureCache$FutureTaskWithCancelBlocking.call(SmartFutureCache.java:320)
	... 5 more
Caused by: java.lang.NullPointerException
	at com.sap.sailing.simulator.impl.PolarDiagramBase.optimalDirectionsDownwind(PolarDiagramBase.java:766)
	at com.sap.sailing.simulator.impl.PathGeneratorTreeGrow360.getStep(PathGeneratorTreeGrow360.java:128)
	at com.sap.sailing.simulator.impl.PathGeneratorTreeGrow360.getPathCandWind(PathGeneratorTreeGrow360.java:220)
	at com.sap.sailing.simulator.impl.PathGeneratorTreeGrow360.getPath(PathGeneratorTreeGrow360.java:727)
	at com.sap.sailing.simulator.impl.SimulatorImpl.getPath(SimulatorImpl.java:58)
	at com.sap.sailing.server.simulation.SimulationServiceImpl.lambda$1(SimulationServiceImpl.java:428)
	at com.sap.sailing.server.simulation.SimulationServiceImpl$$Lambda$31/254510689.call(Unknown Source)
	... 4 more

**Comment by aksajhfduwafe** [comment]
**@axeluhl** commented:

389a0c62ef6d925f82e80a73db8ec774d576e38a contains a first fix, but there are more code locations where null can strike, e.g., the stack trace from the description that points at line 766.

How should the PolarDiagramBase behave in case of sparse data?

**Comment by aksajhfduwafe** [comment]
**@rocrv** commented:

The reported exception occurs if no jibe-speeds are available.

There is a check in the constructor of PolarDiagramGPS for such cases.
But maybe/probably this check needs to be extended.

In which race did this happen?
