### ISSUE TITLE
TrackImpl.getLastFixAtOrBefore fails if the TimePoint of a race is null

### ISSUE THREAD

**Issue by aksajhfduwafe** [aksajhfduwafe/bugzilla-to-github-issues-test#2989]
| Field | Value |
|---|---|
| **Reporter** | Simon Pamies (`s.pamies@the-placeholder-company.com`) |
| **Assignee** | @axeluhl |
| **Product** | Sailing Race Analytics |
| **Component** | Server |
| **Version** | unspecified |
| **Hardware** | All |
| **OS** | All |
| **Severity** | major |
| **Priority** | P2 |
| **Created** | 2015-06-20T16:10:56Z |
| **Original Bug** | [Bug 2989](https://bugzilla.sapsailing.com/bugzilla/show_bug.cgi?id=2989) |

---

Caused by: java.lang.NullPointerException
	at com.sap.sse.common.impl.AbstractTimePoint$1.compare(AbstractTimePoint.java:18)
	at com.sap.sse.common.impl.AbstractTimePoint$1.compare(AbstractTimePoint.java:1)
	at com.sap.sse.common.impl.AbstractTimePoint.compareTo(AbstractTimePoint.java:25)
	at com.sap.sse.common.impl.AbstractTimePoint.compareTo(AbstractTimePoint.java:1)
	at com.sap.sailing.domain.tracking.impl.TimedComparator.compare(TimedComparator.java:14)
	at com.sap.sailing.domain.tracking.impl.TimedComparator.compare(TimedComparator.java:1)
	at java.util.Collections.indexedBinarySearch(Collections.java:332)
	at java.util.Collections.binarySearch(Collections.java:320)
	at com.sap.sse.util.impl.ArrayListNavigableSet.binarySearch(ArrayListNavigableSet.java:131)
	at com.sap.sse.util.impl.ArrayListNavigableSet.floor(ArrayListNavigableSet.java:200)
	at com.sap.sailing.domain.tracking.impl.PartialNavigableSetView.floor(PartialNavigableSetView.java:266)
	at com.sap.sailing.domain.tracking.impl.TrackImpl.getLastFixAtOrBefore(TrackImpl.java:150)
	at com.sap.sailing.domain.tracking.impl.GPSFixTrackImpl.getFixesForPositionEstimation(GPSFixTrackImpl.java:294)
	at com.sap.sailing.domain.tracking.impl.GPSFixTrackImpl.getEstimatedPosition(GPSFixTrackImpl.java:353)
	at com.sap.sailing.domain.tracking.impl.TrackedRaceImpl.getLineMarksAndPositions(TrackedRaceImpl.java:3421)
	at com.sap.sailing.domain.tracking.impl.TrackedRaceImpl.getLineLengthAndAdvantage(TrackedRaceImpl.java:3349)
	at com.sap.sailing.domain.tracking.impl.TrackedRaceImpl.getStartLine(TrackedRaceImpl.java:3484)
	at com.sap.sailing.dashboards.gwt.server.startanalysis.StartAnalysisDTOFactory.createStartAnalysisWindAndLineData(StartAnalysisDTOFactory.java:145)
	at com.sap.sailing.dashboards.gwt.server.startanalysis.StartAnalysisDTOFactory.addStaticDataToStartAnalysisDTOFrom(StartAnalysisDTOFactory.java:116)
	at com.sap.sailing.dashboards.gwt.server.startanalysis.StartAnalysisDTOFactory.createStartAnalysisForCompetitorAndTrackedRace(StartAnalysisDTOFactory.java:48)
	at com.sap.sailing.dashboards.gwt.server.startanalysis.StartAnalysisCreationController.checkStartAnalysisForCompetitorInTrackedRace(StartAnalysisCreationController.java:27)
	at com.sap.sailing.dashboards.gwt.server.RibDashboardServiceImpl.getStartAnalysisListForCompetitorIDAndLeaderboardName(RibDashboardServiceImpl.java:253)

**Comment by aksajhfduwafe** [comment]
**@axeluhl** commented:

Starting branch #2989. I'll fix this for now by
 1) using getStartOfRace() which will produce a valid start time in more cases than getStartTimeReceived() (e.g., from the RaceLog if this hasn't been ping-ponged through TracTrac)
 2) handle null

**Comment by aksajhfduwafe** [comment]
**Simon Pamies (`s.pamies@the-placeholder-company.com`)** commented:

I like - merged - thanks

**Comment by aksajhfduwafe** [comment]
*Simon Pamies (`s.pamies@the-placeholder-company.com`)* changed status from **ASSIGNED** to **RESOLVED** (FIXED)
