### ISSUE TITLE
Leaderboards not being displayed anymore

### ISSUE THREAD

**Issue by aksajhfduwafe** [aksajhfduwafe/bugzilla-to-github-issues-test#2990]
| Field | Value |
|---|---|
| **Reporter** | Simon Pamies (`s.pamies@the-placeholder-company.com`) |
| **Assignee** | @axeluhl |
| **Product** | Sailing Race Analytics |
| **Component** | Server |
| **Version** | unspecified |
| **Hardware** | All |
| **OS** | All |
| **Severity** | critical |
| **Priority** | P1 |
| **Created** | 2015-06-21T09:22:51Z |
| **Original Bug** | [Bug 2990](https://bugzilla.sapsailing.com/bugzilla/show_bug.cgi?id=2990) |

---

86d4067ba4fec61f2037e0e18efefbce0ed06a0a leads to leaderboards not being able to be loaded anymore. Neither overall nor regatta.

Jun 21, 2015 9:20:43 AM com.sap.sailing.domain.leaderboard.impl.AbstractSimpleLeaderboardImpl computeDTO
SEVERE: com.sap.sailing.domain.leaderboard.impl.AbstractSimpleLeaderboardImpl.computeDTO(Extreme Sailing Series 2015 Overall, Sat Jun 20 16:02:09 UTC 2015, [], addOverallDetails=true): exception during computing competitor ordering for race column Cardiff
java.util.concurrent.ExecutionException: java.lang.RuntimeException: java.lang.NullPointerException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at com.sap.sailing.domain.leaderboard.impl.AbstractSimpleLeaderboardImpl.computeDTO(AbstractSimpleLeaderboardImpl.java:1216)
	at com.sap.sailing.domain.leaderboard.caching.LeaderboardDTOCache$2.call(LeaderboardDTOCache.java:167)
	at com.sap.sailing.domain.leaderboard.caching.LeaderboardDTOCache$2.call(LeaderboardDTOCache.java:1)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.RuntimeException: java.lang.NullPointerException
	at com.sap.sailing.domain.leaderboard.impl.ScoreCorrectionImpl.getCorrectedNonMaxedScore(ScoreCorrectionImpl.java:461)
	at com.sap.sailing.domain.leaderboard.impl.ScoreCorrectionImpl.getCorrectedScore(ScoreCorrectionImpl.java:366)
	at com.sap.sailing.domain.leaderboard.impl.AbstractSimpleLeaderboardImpl.getNetPoints(AbstractSimpleLeaderboardImpl.java:433)
	at com.sap.sailing.domain.leaderboard.impl.AbstractSimpleLeaderboardImpl.getCompetitorsFromBestToWorst(AbstractSimpleLeaderboardImpl.java:556)
	at com.sap.sailing.domain.leaderboard.impl.AbstractSimpleLeaderboardImpl.lambda$0(AbstractSimpleLeaderboardImpl.java:1209)
	at com.sap.sailing.domain.leaderboard.impl.AbstractSimpleLeaderboardImpl$$Lambda$40/1756346252.call(Unknown Source)
	... 4 more
Caused by: java.lang.NullPointerException
	at com.sap.sailing.domain.leaderboard.impl.LeaderboardTotalRankComparator.<init>(LeaderboardTotalRankComparator.java:85)
	at com.sap.sailing.domain.leaderboard.impl.AbstractSimpleLeaderboardImpl.getTotalRankComparator(AbstractSimpleLeaderboardImpl.java:625)
	at com.sap.sailing.domain.leaderboard.impl.AbstractSimpleLeaderboardImpl.getCompetitorsFromBestToWorst(AbstractSimpleLeaderboardImpl.java:614)
	at com.sap.sailing.domain.leaderboard.impl.AbstractSimpleLeaderboardImpl.getCompetitorsFromBestToWorst(AbstractSimpleLeaderboardImpl.java:606)
	at com.sap.sailing.domain.leaderboard.meta.AbstractMetaLeaderboard.getTrackedRank(AbstractMetaLeaderboard.java:157)
	at com.sap.sailing.domain.leaderboard.impl.AbstractSimpleLeaderboardImpl$1.call(AbstractSimpleLeaderboardImpl.java:436)
	at com.sap.sailing.domain.leaderboard.impl.AbstractSimpleLeaderboardImpl$1.call(AbstractSimpleLeaderboardImpl.java:1)
	at com.sap.sailing.domain.leaderboard.impl.ScoreCorrectionImpl.getCorrectedNonMaxedScore(ScoreCorrectionImpl.java:451)
	... 9 more

Jun 21, 2015 9:20:43 AM com.sap.sailing.domain.leaderboard.impl.ScoreCorrectionImpl getCorrectedNonMaxedScore
SEVERE: Exception while computing corrected non maxed score
java.lang.NullPointerException
	at com.sap.sailing.domain.leaderboard.impl.LeaderboardTotalRankComparator.<init>(LeaderboardTotalRankComparator.java:85)
	at com.sap.sailing.domain.leaderboard.impl.AbstractSimpleLeaderboardImpl.getTotalRankComparator(AbstractSimpleLeaderboardImpl.java:625)
	at com.sap.sailing.domain.leaderboard.impl.AbstractSimpleLeaderboardImpl.getCompetitorsFromBestToWorst(AbstractSimpleLeaderboardImpl.java:614)
	at com.sap.sailing.domain.leaderboard.impl.AbstractSimpleLeaderboardImpl.getCompetitorsFromBestToWorst(AbstractSimpleLeaderboardImpl.java:606)
	at com.sap.sailing.domain.leaderboard.meta.AbstractMetaLeaderboard.getTrackedRank(AbstractMetaLeaderboard.java:157)
	at com.sap.sailing.domain.leaderboard.impl.AbstractSimpleLeaderboardImpl$1.call(AbstractSimpleLeaderboardImpl.java:436)
	at com.sap.sailing.domain.leaderboard.impl.AbstractSimpleLeaderboardImpl$1.call(AbstractSimpleLeaderboardImpl.java:1)
	at com.sap.sailing.domain.leaderboard.impl.ScoreCorrectionImpl.getCorrectedNonMaxedScore(ScoreCorrectionImpl.java:451)
	at com.sap.sailing.domain.leaderboard.impl.ScoreCorrectionImpl.getCorrectedScore(ScoreCorrectionImpl.java:366)
	at com.sap.sailing.domain.leaderboard.impl.AbstractSimpleLeaderboardImpl.getNetPoints(AbstractSimpleLeaderboardImpl.java:433)
	at com.sap.sailing.domain.leaderboard.impl.AbstractSimpleLeaderboardImpl.getTotalPoints(AbstractSimpleLeaderboardImpl.java:507)
	at com.sap.sailing.domain.leaderboard.impl.LeaderboardTotalRankComparator.<init>(LeaderboardTotalRankComparator.java:89)
	at com.sap.sailing.domain.leaderboard.impl.AbstractSimpleLeaderboardImpl.getTotalRankComparator(AbstractSimpleLeaderboardImpl.java:625)
	at com.sap.sailing.domain.leaderboard.impl.AbstractSimpleLeaderboardImpl.getCompetitorsFromBestToWorst(AbstractSimpleLeaderboardImpl.java:614)
	at com.sap.sailing.domain.leaderboard.impl.AbstractSimpleLeaderboardImpl.getCompetitorsFromBestToWorst(AbstractSimpleLeaderboardImpl.java:606)
	at com.sap.sailing.domain.leaderboard.impl.AbstractSimpleLeaderboardImpl.computeDTO(AbstractSimpleLeaderboardImpl.java:1264)
	at com.sap.sailing.domain.leaderboard.caching.LeaderboardDTOCache$2.call(LeaderboardDTOCache.java:167)
	at com.sap.sailing.domain.leaderboard.caching.LeaderboardDTOCache$2.call(LeaderboardDTOCache.java:1)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by aksajhfduwafe** [comment]
*Simon Pamies (`s.pamies@the-placeholder-company.com`)* changed status from **NEW** to **RESOLVED** (WORKSFORME)
