### ISSUE TITLE
Crash trying to reset a race

### ISSUE THREAD

**Issue by aksajhfduwafe** [aksajhfduwafe/bugzilla-to-github-issues-test#3203]
| Field | Value |
|---|---|
| **Reporter** | @axeluhl |
| **Assignee** | @mars3142 |
| **Product** | Sailing Race Analytics |
| **Component** | Race Management |
| **Version** | unspecified |
| **Hardware** | All |
| **OS** | All |
| **Severity** | blocker |
| **Priority** | P1 |
| **CC (unmapped)** | Samuel Oey (`oey@ubilabs.net`) |
| **Created** | 2015-08-11T16:14:07Z |
| **Original Bug** | [Bug 3203](https://bugzilla.sapsailing.com/bugzilla/show_bug.cgi?id=3203) |

**Duplicate of:** #3176

---

I used the RCApp on a ussailing.sapsailing.com event, connecting to a race for which I had already set a preliminary start time on the server. The app showed a strange blown-up huge font label "22:". Trying to reset the race using the "Reset race" option from the menu led to the crash. Will try to attach log. Version is said to be "7 - Laser (Code 7)".

**Comment by aksajhfduwafe** [comment]
**@axeluhl** commented:

Tue Aug 11 12:09:45 EDT 2015 - Exception occured on thread 1:
java.lang.IllegalArgumentException: Spinner adapter view type count must be 1
	at android.widget.Spinner.setAdapter(Spinner.java:439)
	at com.sap.sailing.racecommittee.app.ui.fragments.raceinfo.StartTimeFragment.initViewsRelative(StartTimeFragment.java:318)
	at com.sap.sailing.racecommittee.app.ui.fragments.raceinfo.StartTimeFragment.onActivityCreated(StartTimeFragment.java:264)
	at android.app.Fragment.performActivityCreated(Fragment.java:2061)
	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:912)
	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1067)
	at android.app.BackStackRecord.run(BackStackRecord.java:833)
	at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1452)
	at android.app.FragmentManagerImpl$1.run(FragmentManager.java:447)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:211)
	at android.app.ActivityThread.main(ActivityThread.java:5335)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1016)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:811)

Tue Aug 11 12:10:10 EDT 2015 - Exception occured on thread 1:
java.lang.IllegalArgumentException: Spinner adapter view type count must be 1
	at android.widget.Spinner.setAdapter(Spinner.java:439)
	at com.sap.sailing.racecommittee.app.ui.fragments.raceinfo.StartTimeFragment.initViewsRelative(StartTimeFragment.java:318)
	at com.sap.sailing.racecommittee.app.ui.fragments.raceinfo.StartTimeFragment.onActivityCreated(StartTimeFragment.java:264)
	at android.app.Fragment.performActivityCreated(Fragment.java:2061)
	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:912)
	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1067)
	at android.app.BackStackRecord.run(BackStackRecord.java:833)
	at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1452)
	at android.app.FragmentManagerImpl$1.run(FragmentManager.java:447)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:211)
	at android.app.ActivityThread.main(ActivityThread.java:5335)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1016)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:811)

**Comment by aksajhfduwafe** [comment]
**@axeluhl** commented:



*** This bug has been marked as a duplicate of #3176 ***
