### ISSUE TITLE
SAP Sail InSight (from PlayStore) crashes at startup

### ISSUE THREAD

**Issue by aksajhfduwafe** [aksajhfduwafe/bugzilla-to-github-issues-test#3488]
| Field | Value |
|---|---|
| **Reporter** | @mars3142 |
| **Assignee** | @mars3142 |
| **Product** | Sailing Race Analytics |
| **Component** | Race Management |
| **Version** | unspecified |
| **Hardware** | Mobile |
| **OS** | Android |
| **Severity** | blocker |
| **Priority** | P1 |
| **CC (unmapped)** | Jan Broß (`jan.bross@arcor.de`), Samuel Oey (`oey@ubilabs.net`) |
| **Created** | 2016-03-01T11:04:54Z |
| **Original Bug** | [Bug 3488](https://bugzilla.sapsailing.com/bugzilla/show_bug.cgi?id=3488) |

---

Logcat:

03-01 11:54:57.513 19437 19437 D AndroidRuntime: Shutting down VM
03-01 11:54:57.521 19437 19437 E AndroidRuntime: FATAL EXCEPTION: main
03-01 11:54:57.521 19437 19437 E AndroidRuntime: Process: com.sap.sailing.android.tracking.app, PID: 19437
03-01 11:54:57.521 19437 19437 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.sap.sailing.android.tracking.app/com.sap.sailing.android.tracking.app.ui.activities.StartActivity}: android.view.InflateException: Binary XML file line #6: Binary XML file line #6: Error inflating class <unknown>
03-01 11:54:57.521 19437 19437 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2416)
03-01 11:54:57.521 19437 19437 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
03-01 11:54:57.521 19437 19437 E AndroidRuntime: 	at android.app.ActivityThread.-wrap11(ActivityThread.java)
03-01 11:54:57.521 19437 19437 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
03-01 11:54:57.521 19437 19437 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
03-01 11:54:57.521 19437 19437 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:148)
03-01 11:54:57.521 19437 19437 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:5417)
03-01 11:54:57.521 19437 19437 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
03-01 11:54:57.521 19437 19437 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
03-01 11:54:57.521 19437 19437 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
03-01 11:54:57.521 19437 19437 E AndroidRuntime: Caused by: android.view.InflateException: Binary XML file line #6: Binary XML file line #6: Error inflating class <unknown>
03-01 11:54:57.521 19437 19437 E AndroidRuntime: 	at android.view.LayoutInflater.inflate(LayoutInflater.java:539)
03-01 11:54:57.521 19437 19437 E AndroidRuntime: 	at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
03-01 11:54:57.521 19437 19437 E AndroidRuntime: 	at com.sap.sailing.android.ui.fragments.AbstractHomeFragment.onCreateView(AbstractHomeFragment.java:40)
03-01 11:54:57.521 19437 19437 E AndroidRuntime: 	at com.sap.sailing.android.tracking.app.ui.fragments.HomeFragment.onCreateView(HomeFragment.java:57)
03-01 11:54:57.521 19437 19437 E AndroidRuntime: 	at android.support.v4.app.Fragment.performCreateView(Fragment.java:1789)
03-01 11:54:57.521 19437 19437 E AndroidRuntime: 	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:955)
03-01 11:54:57.521 19437 19437 E AndroidRuntime: 	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1138)
03-01 11:54:57.521 19437 19437 E AndroidRuntime: 	at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:740)
03-01 11:54:57.521 19437 19437 E AndroidRuntime: 	at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1501)
03-01 11:54:57.521 19437 19437 E AndroidRuntime: 	at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:551)
03-01 11:54:57.521 19437 19437 E AndroidRuntime: 	at com.sap.sailing.android.shared.ui.activities.LoggableActivity.onStart(LoggableActivity.java:29)
03-01 11:54:57.521 19437 19437 E AndroidRuntime: 	at com.sap.sailing.android.shared.ui.activities.SendingServiceAwareActivity.onStart(SendingServiceAwareActivity.java:67)
03-01 11:54:57.521 19437 19437 E AndroidRuntime: 	at com.sap.sailing.android.shared.ui.activities.AbstractStartActivity.onStart(AbstractStartActivity.java:37)
03-01 11:54:57.521 19437 19437 E AndroidRuntime: 	at com.sap.sailing.android.tracking.app.ui.activities.StartActivity.onStart(StartActivity.java:47)
03-01 11:54:57.521 19437 19437 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1237)
03-01 11:54:57.521 19437 19437 E AndroidRuntime: 	at android.app.Activity.performStart(Activity.java:6268)
03-01 11:54:57.521 19437 19437 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2379)
03-01 11:54:57.521 19437 19437 E AndroidRuntime: 	... 9 more
03-01 11:54:57.521 19437 19437 E AndroidRuntime: Caused by: android.view.InflateException: Binary XML file line #6: Error inflating class <unknown>
03-01 11:54:57.521 19437 19437 E AndroidRuntime: 	at android.view.LayoutInflater.createView(LayoutInflater.java:645)
03-01 11:54:57.521 19437 19437 E AndroidRuntime: 	at com.android.internal.policy.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:58)
03-01 11:54:57.521 19437 19437 E AndroidRuntime: 	at android.view.LayoutInflater.onCreateView(LayoutInflater.java:694)
03-01 11:54:57.521 19437 19437 E AndroidRuntime: 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:762)
03-01 11:54:57.521 19437 19437 E AndroidRuntime: 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:704)
03-01 11:54:57.521 19437 19437 E AndroidRuntime: 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:835)
03-01 11:54:57.521 19437 19437 E AndroidRuntime: 	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798)
03-01 11:54:57.521 19437 19437 E AndroidRuntime: 	at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
03-01 11:54:57.521 19437 19437 E AndroidRuntime: 	... 25 more
03-01 11:54:57.521 19437 19437 E AndroidRuntime: Caused by: java.lang.reflect.InvocationTargetException
03-01 11:54:57.521 19437 19437 E AndroidRuntime: 	at java.lang.reflect.Constructor.newInstance(Native Method)
03-01 11:54:57.521 19437 19437 E AndroidRuntime: 	at android.view.LayoutInflater.createView(LayoutInflater.java:619)
03-01 11:54:57.521 19437 19437 E AndroidRuntime: 	... 32 more
03-01 11:54:57.521 19437 19437 E AndroidRuntime: Caused by: android.content.res.Resources$NotFoundException: File  from drawable resource ID #0x7f02017c
03-01 11:54:57.521 19437 19437 E AndroidRuntime: 	at android.content.res.Resources.loadDrawableForCookie(Resources.java:2640)
03-01 11:54:57.521 19437 19437 E AndroidRuntime: 	at android.content.res.Resources.loadDrawable(Resources.java:2540)
03-01 11:54:57.521 19437 19437 E AndroidRuntime: 	at android.content.res.TypedArray.getDrawable(TypedArray.java:870)
03-01 11:54:57.521 19437 19437 E AndroidRuntime: 	at android.widget.ImageView.<init>(ImageView.java:152)
03-01 11:54:57.521 19437 19437 E AndroidRuntime: 	at android.widget.ImageView.<init>(ImageView.java:140)
03-01 11:54:57.521 19437 19437 E AndroidRuntime: 	at android.widget.ImageView.<init>(ImageView.java:136)
03-01 11:54:57.521 19437 19437 E AndroidRuntime: 	... 34 more
03-01 11:54:57.521 19437 19437 E AndroidRuntime: Caused by: java.io.FileNotFoundExcept
03-01 11:54:57.523  4765  4784 W ActivityManager:   Force finishing activity com.sap.sailing.android.tracking.app/.ui.activities.StartActivity

**Comment by aksajhfduwafe** [comment]
**@axeluhl** commented:

Jan and I were able to reproduce the crash on Jan's Samsung.

**Comment by aksajhfduwafe** [comment]
**@mars3142** commented:

App in PlayStore is working.
