### ISSUE TITLE
Large cache and out of bounds exception and NPE

### ISSUE THREAD

**Issue by aksajhfduwafe** [aksajhfduwafe/bugzilla-to-github-issues-test#3815]
| Field | Value |
|---|---|
| **Reporter** | Steffen Wagner (`mail.sap@steffenwagner.com`) |
| **Assignee** | @axeluhl |
| **Product** | Sailing Race Analytics |
| **Component** | Race Management |
| **Version** | unspecified |
| **Hardware** | Mobile |
| **OS** | Android |
| **Severity** | major |
| **Priority** | P1 |
| **CC (unmapped)** | Samuel Oey (`oey@ubilabs.net`) |
| **Created** | 2016-07-24T06:21:13Z |
| **Original Bug** | [Bug 3815](https://bugzilla.sapsailing.com/bugzilla/show_bug.cgi?id=3815) |

---

After starting two phones this morning insights directly crashed and did not open anymore. 
We saw that the cache of the app rose to 3GB (which may be a big bunch of unsent fixes?). After clearing the cache and data app works again.

Sun Jul 24 08:08:38 MESZ 2016 - Exception occured on thread 1:
java.lang.RuntimeException: Unable to create service com.sap.sailing.android.shared.services.sending.MessageSendingService: java.lang.ArrayIndexOutOfBoundsException: length=2; index=2
	at android.app.ActivityThread.handleCreateService(ActivityThread.java:2830)
	at android.app.ActivityThread.access$1900(ActivityThread.java:174)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1389)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:146)
	at android.app.ActivityThread.main(ActivityThread.java:5593)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
	at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.ArrayIndexOutOfBoundsException: length=2; index=2
	at com.sap.sailing.android.shared.services.sending.MessagePersistenceManager.restoreMessages(MessagePersistenceManager.java:121)
	at com.sap.sailing.android.shared.services.sending.MessageSendingService.sendDelayedMessages(MessageSendingService.java:262)
	at com.sap.sailing.android.shared.services.sending.MessageSendingService.handleDelayedMessages(MessageSendingService.java:256)
	at com.sap.sailing.android.shared.services.sending.MessageSendingService.onCreate(MessageSendingService.java:203)
	at android.app.ActivityThread.handleCreateService(ActivityThread.java:2820)
	... 10 more

Sun Jul 24 08:05:03 MESZ 2016 - Exception occured on thread 1:
java.lang.NullPointerException: replacement == null
	at java.lang.String.replace(String.java:1355)
	at com.sap.sailing.android.tracking.app.utils.AppPreferences.getServerCompetiorTeamPath(AppPreferences.java:67)
	at com.sap.sailing.android.tracking.app.ui.activities.RegattaActivity.getTeamImageApiUrl(RegattaActivity.java:272)
	at com.sap.sailing.android.tracking.app.ui.activities.RegattaActivity.askServerAboutTeamImageUrl(RegattaActivity.java:279)
	at com.sap.sailing.android.tracking.app.ui.activities.RegattaActivity.setTeamImage(RegattaActivity.java:243)
	at com.sap.sailing.android.tracking.app.ui.activities.RegattaActivity.access$200(RegattaActivity.java:67)
	at com.sap.sailing.android.tracking.app.ui.activities.RegattaActivity$2.onPreDraw(RegattaActivity.java:221)
	at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:891)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2193)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1251)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6540)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:813)
	at android.view.Choreographer.doCallbacks(Choreographer.java:613)
	at android.view.Choreographer.doFrame(Choreographer.java:583)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:799)
	at android.os.Handler.handleCallback(Handler.java:733)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:146)
	at android.app.ActivityThread.main(ActivityThread.java:5593)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
	at dalvik.system.NativeStart.main(Native Method)

**Comment by aksajhfduwafe** [comment]
**@mars3142** commented:

The ArrayIndexOutOfBoundsException is within the restore of the load of the stored Sending Intents:

    [...]
    String[] lineParts = persistedMessage.split(";");
    String url = lineParts[2]; // crashed here
    [...]

If the persisted message isn't correctly formatted, this error will happen. I looked at the loading file routine, which generates the Intent array for the restore method. The whole file is loaded into a string (3GB!?) and than splitted on the line break.

This code is shared across all three apps, so a fix/workaround can have big impact. We could fix this in multiple ways:

1) Optimize the file loading routine. For example not to load the complete file content into a large string before splitting it.

2) Split the delayedMessage.txt file after a specified number of rows.

3) Move to other storing mechanism (e.g. SQLite).

4) Ignore invalid data and at least one API call won't be send to the server. The Tracker and Buoy App won't be a big problem, but for the RC App it's a blocker, because we will lose important race flow data.

The numbers are in the order, I would change something.

Now, I will analyze the second exception (NPE after stopping tracking).
