### ISSUE TITLE
No "time foiled" output when filtering for leg type "Downwind + Reach"

### ISSUE THREAD

**Issue by aksajhfduwafe** [aksajhfduwafe/bugzilla-to-github-issues-test#4293]
| Field | Value |
|---|---|
| **Reporter** | @axeluhl |
| **Assignee** | @axeluhl |
| **Product** | Sailing Race Analytics |
| **Component** | DataMining |
| **Version** | unspecified |
| **Hardware** | All |
| **OS** | All |
| **Severity** | normal |
| **Priority** | P2 |
| **CC (unmapped)** | Julian Mayland (`j.mayland@appweeve.com`), Milan Cerny (`milan.cerny@sap.com`) |
| **Created** | 2017-08-24T11:40:31Z |
| **Original Bug** | [Bug 4293](https://bugzilla.sapsailing.com/bugzilla/show_bug.cgi?id=4293) |

---

Milan was trying to compile foiling stats. See attached Excel spreadsheet. Reportedly, when he tried to collect the time foiled, filtered for downwind and reach leg types, no times were output. Data was from ESS 2017 (https://ess2017.sapsailing.com).

**Comment by aksajhfduwafe** [comment]
**@axeluhl** commented:

Here is something from the server logs that I see when trying to aggregate the SUM of the *Distance* foiled:

Aug 24, 2017 12:09:15 PM com.sap.sse.datamining.impl.ProcessorQuery logOccuredFailuresAndThrowSevereFailure
SEVERE: A failure occured during the processing of an instruction:
java.lang.ClassCastException: Cannot cast class com.sap.sailing.domain.common.Distance$NullDistance to interface com.sap.sse.common.Duration
        at com.sap.sailing.datamining.impl.components.aggregators.ParallelDurationSumAggregationProcessor.handleElement(ParallelDurationSumAggregationProcessor.java:37)
        at com.sap.sailing.datamining.impl.components.aggregators.ParallelDurationSumAggregationProcessor.handleElement(ParallelDurationSumAggregationProcessor.java:1)
        at com.sap.sse.datamining.impl.components.aggregators.AbstractParallelAggregationProcessor$1.computeResult(AbstractParallelAggregationProcessor.java:35)
        at com.sap.sse.datamining.impl.components.AbstractProcessorInstruction.run(AbstractProcessorInstruction.java:55)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:808)

**Comment by aksajhfduwafe** [comment]
**@axeluhl** commented:

But likewise, at an earlier date, probably when Milan did his analysis:

Aug 23, 2017 7:27:58 PM com.sap.sse.datamining.impl.ProcessorQuery logOccuredFailuresAndThrowSevereFailure
SEVERE: A failure occured during the processing of an instruction:
java.lang.ClassCastException: Cannot cast class com.sap.sse.common.impl.MillisecondsDurationImpl to interface com.sap.sailing.domain.common.Distance
        at com.sap.sailing.datamining.impl.components.aggregators.ParallelDistanceSumAggregationProcessor.handleElement(ParallelDistanceSumAggregationProcessor.java:37)
        at com.sap.sailing.datamining.impl.components.aggregators.ParallelDistanceSumAggregationProcessor.handleElement(ParallelDistanceSumAggregationProcessor.java:1)
        at com.sap.sse.datamining.impl.components.aggregators.AbstractParallelAggregationProcessor$1.computeResult(AbstractParallelAggregationProcessor.java:35)
        at com.sap.sse.datamining.impl.components.AbstractProcessorInstruction.run(AbstractProcessorInstruction.java:55)
        at com.sap.sse.datamining.impl.DataMiningExecutorService$1.rejectedExecution(DataMiningExecutorService.java:17)
        at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:830)
        at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1379)
        at com.sap.sse.datamining.impl.components.AbstractParallelProcessor.processElement(AbstractParallelProcessor.java:49)
        at com.sap.sse.datamining.impl.components.AbstractParallelProcessor.forwardResultToReceivers(AbstractParallelProcessor.java:90)
        at com.sap.sse.datamining.impl.components.AbstractParallelProcessor.instructionSucceeded(AbstractParallelProcessor.java:64)
        at com.sap.sse.datamining.impl.components.AbstractProcessorInstruction.run(AbstractProcessorInstruction.java:56)
        at com.sap.sse.datamining.impl.DataMiningExecutorService$1.rejectedExecution(DataMiningExecutorService.java:17)
        at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:830)
        at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1379)
        at com.sap.sse.datamining.impl.components.AbstractParallelProcessor.processElement(AbstractParallelProcessor.java:49)
        at com.sap.sse.datamining.impl.components.AbstractParallelProcessor.forwardResultToReceivers(AbstractParallelProcessor.java:90)
        at com.sap.sse.datamining.impl.components.AbstractParallelProcessor.instructionSucceeded(AbstractParallelProcessor.java:64)
        at com.sap.sse.datamining.impl.components.AbstractProcessorInstruction.run(AbstractProcessorInstruction.java:56)
        at com.sap.sse.datamining.impl.DataMiningExecutorService$1.rejectedExecution(DataMiningExecutorService.java:17)
        at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:830)
        at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1379)
        at com.sap.sse.datamining.impl.components.AbstractParallelProcessor.processElement(AbstractParallelProcessor.java:49)
        at com.sap.sse.datamining.impl.components.AbstractParallelProcessor.forwardResultToReceivers(AbstractParallelProcessor.java:90)
        at com.sap.sse.datamining.impl.components.AbstractRetrievalProcessor$1.computeResult(AbstractRetrievalProcessor.java:46)
        at com.sap.sse.datamining.impl.components.AbstractProcessorInstruction.run(AbstractProcessorInstruction.java:55)
        at com.sap.sse.datamining.impl.DataMiningExecutorService$1.rejectedExecution(DataMiningExecutorService.java:17)
        at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:830)
        at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1379)
        at com.sap.sse.datamining.impl.components.AbstractParallelProcessor.processElement(AbstractParallelProcessor.java:49)
        at com.sap.sse.datamining.impl.components.AbstractParallelProcessor.forwardResultToReceivers(AbstractParallelProcessor.java:90)
        at com.sap.sse.datamining.impl.components.AbstractParallelProcessor.instructionSucceeded(AbstractParallelProcessor.java:64)
        at com.sap.sse.datamining.impl.components.AbstractProcessorInstruction.run(AbstractProcessorInstruction.java:56)
        at com.sap.sse.datamining.impl.DataMiningExecutorService$1.rejectedExecution(DataMiningExecutorService.java:17)
        at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:830)
        at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1379)
        at com.sap.sse.datamining.impl.components.AbstractParallelProcessor.processElement(AbstractParallelProcessor.java:49)
        at com.sap.sse.datamining.impl.components.AbstractParallelProcessor.forwardResultToReceivers(AbstractParallelProcessor.java:90)
        at com.sap.sse.datamining.impl.components.AbstractRetrievalProcessor$1.computeResult(AbstractRetrievalProcessor.java:46)
        at com.sap.sse.datamining.impl.components.AbstractProcessorInstruction.run(AbstractProcessorInstruction.java:55)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:808)

Note how here a Distance cannot be cast to a Duration. It almost seems as if the selection of aggregator was mixing up the duration and distance aggregators randomly.

**Comment by aksajhfduwafe** [comment]
**@LennartH** commented:

I don't have my hands on the code right now, but I think that it could be possible that an Aggregator is shadowed by another one, if the display name of the Aggregator-DTO is equal.

I think the Aggregator to DTO construction is done by the DataMiningServiceImpl (maybe not the exact name, but it should be the implementation of the async GWT service for the data mining). There you should see how the display name of the DTO is built.
