### ISSUE TITLE
Trying to assign a qualified admin role to a user as global admin fails with an NPE

### ISSUE THREAD

**Issue by aksajhfduwafe** [aksajhfduwafe/bugzilla-to-github-issues-test#4923]
| Field | Value |
|---|---|
| **Reporter** | @axeluhl |
| **Assignee** | @axeluhl |
| **Product** | Sailing Race Analytics |
| **Component** | Security |
| **Version** | unspecified |
| **Hardware** | All |
| **OS** | All |
| **Severity** | normal |
| **Priority** | P2 |
| **CC (unmapped)** | Steffen Schäfer (`steffen.schaefer@pgt.de`) |
| **Created** | 2019-02-27T09:55:02Z |
| **Original Bug** | [Bug 4923](https://bugzilla.sapsailing.com/bugzilla/show_bug.cgi?id=4923) |

---

The problems seems to be that the global admin does not have any defaultTenantForServer set, leading to a request to set an ownership for the role association that only has the global admin as the owning user, but no group as owning group. It seems this case hasn't been accounted for yet.

WARNING: Exception while dispatching incoming RPC call
com.google.gwt.user.server.rpc.UnexpectedException: Service method 'public abstract com.sap.sse.security.ui.shared.SuccessInfo com.sap.sse.security.ui.client.UserManagementService.addRoleToUser(java.lang.String,java.lang.String,java.util.UUID,java.lang.String) throws com.sap.sse.security.shared.UserManagementException,com.sap.sse.security.shared.UnauthorizedException' threw an unexpected exception: java.lang.RuntimeException: java.lang.NullPointerException: while trying to invoke the method com.sap.sse.security.shared.impl.UserGroup.getId() of a null object loaded from local variable 'tenantOwner'
	at com.google.gwt.user.server.rpc.RPC.encodeResponseForFailure(RPC.java:416)
	at com.google.gwt.user.server.rpc.RPC.invokeAndEncodeResponse(RPC.java:605)
	at com.google.gwt.user.server.rpc.RemoteServiceServlet.processCall(RemoteServiceServlet.java:333)
	at com.google.gwt.user.server.rpc.RemoteServiceServlet.processCall(RemoteServiceServlet.java:303)
	at com.google.gwt.user.server.rpc.RemoteServiceServlet.processPost(RemoteServiceServlet.java:373)
	at com.google.gwt.user.server.rpc.AbstractRemoteServiceServlet.doPost(AbstractRemoteServiceServlet.java:62)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:860)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1650)
	at com.sap.sse.gwt.server.GWTCacheControlServletFilter.doFilter(GWTCacheControlServletFilter.java:41)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1637)
	at org.apache.shiro.web.servlet.ProxiedFilterChain.doFilter(ProxiedFilterChain.java:61)
	at org.apache.shiro.web.servlet.AdviceFilter.executeChain(AdviceFilter.java:108)
	at org.apache.shiro.web.servlet.AdviceFilter.doFilterInternal(AdviceFilter.java:137)
	at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125)
	at org.apache.shiro.web.servlet.ProxiedFilterChain.doFilter(ProxiedFilterChain.java:66)
	at org.apache.shiro.web.servlet.AbstractShiroFilter.executeChain(AbstractShiroFilter.java:449)
	at org.apache.shiro.web.servlet.AbstractShiroFilter$1.call(AbstractShiroFilter.java:365)
	at org.apache.shiro.subject.support.SubjectCallable.doCall(SubjectCallable.java:90)
	at org.apache.shiro.subject.support.SubjectCallable.call(SubjectCallable.java:83)
	at org.apache.shiro.subject.support.DelegatingSubject.execute(DelegatingSubject.java:383)
	at org.apache.shiro.web.servlet.AbstractShiroFilter.doFilterInternal(AbstractShiroFilter.java:362)
	at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1629)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:533)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:524)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:190)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1595)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:188)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1253)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:168)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:473)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1564)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:166)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1155)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:219)
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:126)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.Server.handle(Server.java:530)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:347)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:256)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:279)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:102)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:124)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:247)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.produce(EatWhatYouKill.java:140)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:131)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:382)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:708)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:626)
	at java.lang.Thread.run(Thread.java:808)
Caused by: java.lang.RuntimeException: java.lang.NullPointerException: while trying to invoke the method com.sap.sse.security.shared.impl.UserGroup.getId() of a null object loaded from local variable 'tenantOwner'
	at com.sap.sse.security.impl.SecurityServiceImpl.setOwnershipCheckPermissionForObjectCreationAndRevertOnError(SecurityServiceImpl.java:1623)
	at com.sap.sse.security.impl.SecurityServiceImpl.setOwnershipCheckPermissionForObjectCreationAndRevertOnError(SecurityServiceImpl.java:1637)
	at com.sap.sse.security.ui.server.UserManagementServiceImpl.addRoleToUser(UserManagementServiceImpl.java:880)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.gwt.user.server.rpc.RPC.invokeAndEncodeResponse(RPC.java:587)
	... 53 more
Caused by: java.lang.NullPointerException: while trying to invoke the method com.sap.sse.security.shared.impl.UserGroup.getId() of a null object loaded from local variable 'tenantOwner'
	at com.sap.sse.security.impl.SecurityServiceImpl.setOwnership(SecurityServiceImpl.java:582)
	at com.sap.sse.security.impl.SecurityServiceImpl.setDefaultOwnership(SecurityServiceImpl.java:1630)
	at com.sap.sse.security.impl.SecurityServiceImpl.setOwnershipCheckPermissionForObjectCreationAndRevertOnError(SecurityServiceImpl.java:1607)
	... 60 more

**Comment by aksajhfduwafe** [comment]
**@axeluhl** commented:

6da1db658eb39449f4fdfd00cdc8f9fed5a3799a on permission-vertical should have fixed this.
