### ISSUE TITLE
Creating a new LeaderboardGroup doesn't replicate correctly due to extra security check on replica

### ISSUE THREAD

**Issue by aksajhfduwafe** [aksajhfduwafe/bugzilla-to-github-issues-test#5488]
| Field | Value |
|---|---|
| **Reporter** | @axeluhl |
| **Assignee** | @daulenba |
| **Product** | Sailing Race Analytics |
| **Component** | Security |
| **Version** | unspecified |
| **Hardware** | All |
| **OS** | All |
| **Severity** | normal |
| **Priority** | P2 |
| **Created** | 2021-03-04T21:29:53Z |
| **Original Bug** | [Bug 5488](https://bugzilla.sapsailing.com/bugzilla/show_bug.cgi?id=5488) |

---

When the CreateLeaderboardGroup operation runs its internalApplyTo method, it calls com.sap.sailing.server.impl.RacingEventServiceImpl.addOverallLeaderboardToLeaderboardGroup in case the LeaderboardGroup replicated has an overall leaderboard. This tries to set the ownership for the new overall leaderboard, but the ownership will already have been set on the master; furthermore, this checks for the SERVER:CREATE_OBJECT permission, but while executing a replicated operation there is no authenticated subject / session active, so this gets rejected. Below is the stack trace.

The solution has to ensure that ownership checking/setting as well as the checking of the SERVER:CREATE_OBJECT permission happens only where the operation has been received, just where the permission checking and ownership setting for the LeaderboardGroup itself is happening.

Mar 04, 2021 9:13:35 PM com.sap.sse.replication.impl.ReplicationReceiverImpl run
INFO: Exception while processing replica: org.apache.shiro.authz.UnauthorizedException: Subject does not have permission [SERVER:CREATE_OBJECT:axelstest]
Mar 04, 2021 9:13:35 PM com.sap.sse.replication.impl.ReplicationReceiverImpl run
SEVERE: run
java.lang.RuntimeException: org.apache.shiro.authz.UnauthorizedException: Subject does not have permission [SERVER:CREATE_OBJECT:axelstest]
        at com.sap.sse.replication.ReplicableWithObjectInputStream.applyReplicated(ReplicableWithObjectInputStream.java:208)
        at com.sap.sse.replication.Replicable.applyReceivedReplicated(Replicable.java:206)
        at com.sap.sse.replication.impl.ReplicationReceiverImpl.lambda$4(ReplicationReceiverImpl.java:310)
        at com.sap.sse.replication.impl.ReplicationReceiverImpl.apply(ReplicationReceiverImpl.java:312)
        at com.sap.sse.replication.impl.ReplicationReceiverImpl.applyOrQueue(ReplicationReceiverImpl.java:303)
        at com.sap.sse.replication.impl.ReplicationReceiverImpl.readOperationAndApplyOrQueueIt(ReplicationReceiverImpl.java:289)
        at com.sap.sse.replication.impl.ReplicationReceiverImpl.run(ReplicationReceiverImpl.java:184)
        at java.lang.Thread.run(Thread.java:836)
Caused by: org.apache.shiro.authz.UnauthorizedException: Subject does not have permission [SERVER:CREATE_OBJECT:axelstest]
        at org.apache.shiro.authz.ModularRealmAuthorizer.checkPermission(ModularRealmAuthorizer.java:323)
        at org.apache.shiro.mgt.AuthorizingSecurityManager.checkPermission(AuthorizingSecurityManager.java:137)
        at org.apache.shiro.subject.support.DelegatingSubject.checkPermission(DelegatingSubject.java:205)
        at com.sap.sse.security.impl.SecurityServiceImpl.checkCurrentUserServerPermission(SecurityServiceImpl.java:1795)
        at com.sap.sse.security.impl.SecurityServiceImpl.setOwnershipCheckPermissionForObjectCreationAndRevertOnError(SecurityServiceImpl.java:1759)
        at com.sap.sse.security.impl.SecurityServiceImpl.setOwnershipCheckPermissionForObjectCreationAndRevertOnError(SecurityServiceImpl.java:1723)
        at com.sap.sailing.server.impl.RacingEventServiceImpl.addOverallLeaderboardToLeaderboardGroup(RacingEventServiceImpl.java:3267)
        at com.sap.sailing.server.impl.RacingEventServiceImpl.addLeaderboardGroup(RacingEventServiceImpl.java:3129)
        at com.sap.sailing.server.operationaltransformation.CreateLeaderboardGroup.internalApplyTo(CreateLeaderboardGroup.java:48)
        at com.sap.sailing.server.operationaltransformation.CreateLeaderboardGroup.internalApplyTo(CreateLeaderboardGroup.java:1)
        at com.sap.sse.replication.ReplicableWithObjectInputStream.applyReplicated(ReplicableWithObjectInputStream.java:201)
        ... 7 more

**Comment by aksajhfduwafe** [comment]
**@axeluhl** commented:

https://hudson.sapsailing.com/job/#5488/2/ was successful.

**Comment by aksajhfduwafe** [comment]
**@daulenba** commented:

I reviewed the changes and backtraced any other usages of RacingEventServiceImpl.addOverallLeaderboardToLeaderboardGroup. 
I found no occurences remaining, where the missing security check would cause problems. 
-> resolving bug

**Comment by aksajhfduwafe** [comment]
*@daulenba* changed status from **ASSIGNED** to **RESOLVED** (FIXED)

**Comment by aksajhfduwafe** [comment]
*Subscribing participants (reporter + CC):*

@axeluhl
