### ISSUE TITLE
RejectedExecutionException during ORC PCS leaderboard calculation

### ISSUE THREAD

**Issue by aksajhfduwafe** [aksajhfduwafe/bugzilla-to-github-issues-test#5756]
| Field | Value |
|---|---|
| **Reporter** | @axeluhl |
| **Assignee** | @axeluhl |
| **Product** | Sailing Race Analytics |
| **Component** | Leaderboard |
| **Version** | unspecified |
| **Hardware** | All |
| **OS** | All |
| **Severity** | normal |
| **Priority** | P2 |
| **CC (unmapped)** | Tim Hessenmüller (`tim@hessenmueller.de`) |
| **Created** | 2022-07-26T08:21:44Z |
| **Original Bug** | [Bug 5756](https://bugzilla.sapsailing.com/bugzilla/show_bug.cgi?id=5756) |

---

On the TracTrac server (replica set "TracTracTest") the following exception was observed:

Jul 25, 2022 9:20:42 AM com.sap.sailing.domain.leaderboard.impl.AbstractLeaderboardWithCache computeDTO
SEVERE: com.sap.sailing.domain.leaderboard.impl.AbstractSimpleLeaderboardImpl.computeDTO(ORC Europeans 2021 - ORC C, Thu May 20 20:04:44 UTC 2021, [R1], addOverallDetails=true): exception during computing leaderboard entry for competitor TOPAS in race column [TOPAS with boat TOPAS, R1]. Leaving empty.
java.util.concurrent.ExecutionException: java.util.concurrent.RejectedExecutionException: java.util.concurrent.RejectedExecutionException: Thread limit exceeded replacing blocked worker
        at java.util.concurrent.FutureTask.report(FutureTask.java:122)
        at java.util.concurrent.FutureTask.get(FutureTask.java:206)
        at com.sap.sse.util.impl.HasTracingGetImpl.callGetAndTraceAfterEachTimeout(HasTracingGetImpl.java:28)
        at com.sap.sse.util.impl.ThreadPoolAwareRunnableScheduledFutureDelegate.get(ThreadPoolAwareRunnableScheduledFutureDelegate.java:53)
        at com.sap.sailing.domain.leaderboard.impl.AbstractLeaderboardWithCache.computeDTO(AbstractLeaderboardWithCache.java:559)
        at com.sap.sailing.domain.leaderboard.caching.LeaderboardDTOCache$2.call(LeaderboardDTOCache.java:148)
        at com.sap.sailing.domain.leaderboard.caching.LeaderboardDTOCache$2.call(LeaderboardDTOCache.java:1)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at com.sap.sailing.domain.leaderboard.caching.LeaderboardDTOCache.getLeaderboardByName(LeaderboardDTOCache.java:162)
        at com.sap.sailing.domain.leaderboard.impl.AbstractLeaderboardWithCache.getLeaderboardDTO(AbstractLeaderboardWithCache.java:354)
        at com.sap.sailing.gwt.ui.server.SailingServiceImpl.getLeaderBoardByNameInternal(SailingServiceImpl.java:837)
        at com.sap.sailing.gwt.ui.server.SailingServiceImpl.getLeaderboardByName(SailingServiceImpl.java:784)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.sap.sse.gwt.server.DelegatingProxiedRemoteServiceServlet.invokeAndEncodeResponse(DelegatingProxiedRemoteServiceServlet.java:67)
        at com.sap.sse.gwt.server.DelegatingProxiedRemoteServiceServlet.processCall(DelegatingProxiedRemoteServiceServlet.java:38)
        at com.google.gwt.user.server.rpc.RemoteServiceServlet.processCall(RemoteServiceServlet.java:303)
        at com.google.gwt.user.server.rpc.RemoteServiceServlet.processPost(RemoteServiceServlet.java:373)
        at com.google.gwt.user.server.rpc.AbstractRemoteServiceServlet.doPost(AbstractRemoteServiceServlet.java:62)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
        at com.sap.sse.gwt.server.ProxiedRemoteServiceServlet.service(ProxiedRemoteServiceServlet.java:146)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
        at com.sap.sailing.gwt.ui.server.SailingServiceImpl.service(SailingServiceImpl.java:5707)
        at org.eclipse.jetty.servlet.ServletHolder$NotAsync.service(ServletHolder.java:1459)
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:799)
        at org.eclipse.jetty.servlet.ServletHandler$ChainEnd.doFilter(ServletHandler.java:1631)
        at com.sap.sailing.www.CookieSameSiteFilter.doFilter(CookieSameSiteFilter.java:37)
        at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)
        at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601)
        at com.sap.sse.gwt.server.GWTCacheControlServletFilter.doFilter(GWTCacheControlServletFilter.java:41)
        at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)
        at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601)
        at org.apache.shiro.web.servlet.ProxiedFilterChain.doFilter(ProxiedFilterChain.java:61)
        at org.apache.shiro.web.servlet.AdviceFilter.executeChain(AdviceFilter.java:108)
        at org.apache.shiro.web.servlet.AdviceFilter.doFilterInternal(AdviceFilter.java:137)
        at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125)
        at org.apache.shiro.web.servlet.ProxiedFilterChain.doFilter(ProxiedFilterChain.java:66)
        at org.apache.shiro.web.servlet.AdviceFilter.executeChain(AdviceFilter.java:108)
        at org.apache.shiro.web.servlet.AdviceFilter.doFilterInternal(AdviceFilter.java:137)
        at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125)
        at org.apache.shiro.web.servlet.ProxiedFilterChain.doFilter(ProxiedFilterChain.java:66)
        at org.apache.shiro.web.servlet.AbstractShiroFilter.executeChain(AbstractShiroFilter.java:450)
        at org.apache.shiro.web.servlet.AbstractShiroFilter$1.call(AbstractShiroFilter.java:365)
        at org.apache.shiro.subject.support.SubjectCallable.doCall(SubjectCallable.java:90)
        at org.apache.shiro.subject.support.SubjectCallable.call(SubjectCallable.java:83)
        at org.apache.shiro.subject.support.DelegatingSubject.execute(DelegatingSubject.java:387)
        at org.apache.shiro.web.servlet.AbstractShiroFilter.doFilterInternal(AbstractShiroFilter.java:362)
        at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125)
        at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)
        at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601)
        at com.sap.sailing.www.CORSFilter.doFilter(CORSFilter.java:25)
        at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:201)
        at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:548)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
        at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:600)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:235)
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1624)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1434)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:501)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1594)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1349)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
        at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:234)
        at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:146)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
        at org.eclipse.jetty.server.Server.handle(Server.java:516)
        at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:400)
        at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:645)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:392)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:277)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
        at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:338)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:315)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:173)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:131)
        at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:409)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:883)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1034)
        at java.lang.Thread.run(Thread.java:836)
Caused by: java.util.concurrent.RejectedExecutionException: java.util.concurrent.RejectedExecutionException: Thread limit exceeded replacing blocked worker
        at sun.reflect.GeneratedConstructorAccessor97.newInstance(Unknown Source)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:593)
        at java.util.concurrent.ForkJoinTask.reportException(ForkJoinTask.java:677)
        at java.util.concurrent.ForkJoinTask.join(ForkJoinTask.java:720)
        at com.sap.sailing.domain.orc.impl.ORCPerformanceCurveByImpliedWindRankingMetric.getRankingInfo(ORCPerformanceCurveByImpliedWindRankingMetric.java:656)
        at com.sap.sailing.domain.orc.impl.ORCPerformanceCurveByImpliedWindRankingMetric.getRankingInfo(ORCPerformanceCurveByImpliedWindRankingMetric.java:1)
        at com.sap.sailing.domain.leaderboard.impl.AbstractLeaderboardWithCache.lambda$4(AbstractLeaderboardWithCache.java:528)
        at java.util.HashMap.computeIfAbsent(HashMap.java:1127)
        at com.sap.sailing.domain.leaderboard.impl.AbstractLeaderboardWithCache.lambda$3(AbstractLeaderboardWithCache.java:525)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at com.sap.sse.util.impl.ThreadPoolAwareRunnableScheduledFutureDelegate.run(ThreadPoolAwareRunnableScheduledFutureDelegate.java:25)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        ... 1 more
Caused by: java.util.concurrent.RejectedExecutionException: Thread limit exceeded replacing blocked worker
        at java.util.concurrent.ForkJoinPool.tryCompensate(ForkJoinPool.java:2011)
        at java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3310)
        at com.sap.sailing.domain.leaderboard.caching.LeaderboardDTOCalculationReuseCache.getRelativeCorrectedTime(LeaderboardDTOCalculationReuseCache.java:345)
        at com.sap.sailing.domain.orc.impl.ORCPerformanceCurveRankingMetric.lambda$7(ORCPerformanceCurveRankingMetric.java:145)
        at java.util.concurrent.ForkJoinTask$AdaptedCallable.exec(ForkJoinTask.java:1424)
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
        at java.util.concurrent.ForkJoinPool$WorkQueue.tryRemoveAndExec(ForkJoinPool.java:1107)
        at java.util.concurrent.ForkJoinPool.awaitJoin(ForkJoinPool.java:2046)
        at java.util.concurrent.ForkJoinTask.doJoin(ForkJoinTask.java:390)
        at java.util.concurrent.ForkJoinTask.join(ForkJoinTask.java:719)
        at com.sap.sailing.domain.orc.impl.ORCPerformanceCurveRankingMetric.getRelativeCorrectedTimesByCompetitor(ORCPerformanceCurveRankingMetric.java:149)
        at com.sap.sailing.domain.orc.impl.ORCPerformanceCurveRankingMetric.getRaceRankingComparator(ORCPerformanceCurveRankingMetric.java:59)
        at com.sap.sailing.domain.ranking.RankingMetric.getRaceRankingComparator(RankingMetric.java:159)
        at com.sap.sailing.domain.orc.impl.ORCPerformanceCurveRankingMetricLeaderForBaseline.getBaseLineCompetitorForAbsoluteCorrectedTimes(ORCPerformanceCurveRankingMetricLeaderForBaseline.java:47)
        at com.sap.sailing.domain.orc.impl.ORCPerformanceCurveRankingMetric.getCorrectedTime(ORCPerformanceCurveRankingMetric.java:177)
        at com.sap.sailing.domain.orc.impl.ORCPerformanceCurveByImpliedWindRankingMetric.lambda$15(ORCPerformanceCurveByImpliedWindRankingMetric.java:643)
        at java.util.concurrent.ForkJoinTask$AdaptedCallable.exec(ForkJoinTask.java:1424)
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)

The exception keeps occurring again and again.

**Comment by aksajhfduwafe** [comment]
**@axeluhl** commented:

The problem can be reproduced by running a "Master Data Import" from https://tractractest.sapsailing.com for the leaderboard group "66 REGATA DEI TRE GOLFI ORC Europeans 2021" and then opening R1 of the ORC C leaderboard. Locally, this has the URL http://127.0.0.1:8888/gwt/RaceBoard.html?regattaName=ORC+Europeans+2021+-+ORC+C&raceName=ORC+EUROPEANS+-+LONG+DISTANCE+ORC+C&leaderboardName=ORC+Europeans+2021+-+ORC+C&canReplayDuringLiveRaces=true. The stack trace observed is then:

Jul 26, 2022 11:55:33 AM com.sap.sailing.domain.leaderboard.impl.AbstractLeaderboardWithCache computeDTO
SEVERE: com.sap.sailing.domain.leaderboard.impl.AbstractSimpleLeaderboardImpl.computeDTO(ORC Europeans 2021 - ORC C, Sat May 15 19:14:19 CEST 2021 (+380ms), [R1], addOverallDetails=false): exception during computing leaderboard entry for competitor COSIXTY 8 in race column [COSIXTY 8 with boat COSIXTY 8, R1]. Leaving empty.
java.util.concurrent.ExecutionException: java.util.concurrent.RejectedExecutionException: java.util.concurrent.RejectedExecutionException: Thread limit exceeded replacing blocked worker
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:206)
	at com.sap.sse.util.impl.HasTracingGetImpl.callGetAndTraceAfterEachTimeout(HasTracingGetImpl.java:28)
	at com.sap.sse.util.impl.ThreadPoolAwareRunnableScheduledFutureDelegate.get(ThreadPoolAwareRunnableScheduledFutureDelegate.java:53)
	at com.sap.sailing.domain.leaderboard.impl.AbstractLeaderboardWithCache.computeDTO(AbstractLeaderboardWithCache.java:559)
	at com.sap.sailing.domain.leaderboard.caching.LeaderboardDTOCache$2.call(LeaderboardDTOCache.java:148)
	at com.sap.sailing.domain.leaderboard.caching.LeaderboardDTOCache$2.call(LeaderboardDTOCache.java:1)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at com.sap.sailing.domain.leaderboard.caching.LeaderboardDTOCache.getLeaderboardByName(LeaderboardDTOCache.java:162)
	at com.sap.sailing.domain.leaderboard.impl.AbstractLeaderboardWithCache.getLeaderboardDTO(AbstractLeaderboardWithCache.java:354)
	at com.sap.sailing.gwt.ui.server.SailingServiceImpl.getLeaderBoardByNameInternal(SailingServiceImpl.java:837)
	at com.sap.sailing.gwt.ui.server.SailingServiceImpl.getLeaderboardForRace(SailingServiceImpl.java:816)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.sap.sse.gwt.server.DelegatingProxiedRemoteServiceServlet.invokeAndEncodeResponse(DelegatingProxiedRemoteServiceServlet.java:67)
	at com.sap.sse.gwt.server.DelegatingProxiedRemoteServiceServlet.processCall(DelegatingProxiedRemoteServiceServlet.java:38)
	at com.google.gwt.user.server.rpc.RemoteServiceServlet.processCall(RemoteServiceServlet.java:303)
	at com.google.gwt.user.server.rpc.RemoteServiceServlet.processPost(RemoteServiceServlet.java:373)
	at com.google.gwt.user.server.rpc.AbstractRemoteServiceServlet.doPost(AbstractRemoteServiceServlet.java:62)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
	at com.sap.sse.gwt.server.ProxiedRemoteServiceServlet.service(ProxiedRemoteServiceServlet.java:146)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at com.sap.sailing.gwt.ui.server.SailingServiceImpl.service(SailingServiceImpl.java:5707)
	at org.eclipse.jetty.servlet.ServletHolder$NotAsync.service(ServletHolder.java:1459)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:799)
	at org.eclipse.jetty.servlet.ServletHandler$ChainEnd.doFilter(ServletHandler.java:1631)
	at com.sap.sailing.www.CookieSameSiteFilter.doFilter(CookieSameSiteFilter.java:37)
	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)
	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601)
	at com.sap.sse.gwt.server.GWTCacheControlServletFilter.doFilter(GWTCacheControlServletFilter.java:41)
	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)
	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601)
	at org.apache.shiro.web.servlet.ProxiedFilterChain.doFilter(ProxiedFilterChain.java:61)
	at org.apache.shiro.web.servlet.AdviceFilter.executeChain(AdviceFilter.java:108)
	at org.apache.shiro.web.servlet.AdviceFilter.doFilterInternal(AdviceFilter.java:137)
	at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125)
	at org.apache.shiro.web.servlet.ProxiedFilterChain.doFilter(ProxiedFilterChain.java:66)
	at org.apache.shiro.web.servlet.AdviceFilter.executeChain(AdviceFilter.java:108)
	at org.apache.shiro.web.servlet.AdviceFilter.doFilterInternal(AdviceFilter.java:137)
	at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125)
	at org.apache.shiro.web.servlet.ProxiedFilterChain.doFilter(ProxiedFilterChain.java:66)
	at org.apache.shiro.web.servlet.AbstractShiroFilter.executeChain(AbstractShiroFilter.java:450)
	at org.apache.shiro.web.servlet.AbstractShiroFilter$1.call(AbstractShiroFilter.java:365)
	at org.apache.shiro.subject.support.SubjectCallable.doCall(SubjectCallable.java:90)
	at org.apache.shiro.subject.support.SubjectCallable.call(SubjectCallable.java:83)
	at org.apache.shiro.subject.support.DelegatingSubject.execute(DelegatingSubject.java:387)
	at org.apache.shiro.web.servlet.AbstractShiroFilter.doFilterInternal(AbstractShiroFilter.java:362)
	at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125)
	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)
	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601)
	at com.sap.sailing.www.CORSFilter.doFilter(CORSFilter.java:25)
	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:201)
	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:548)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:600)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:235)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1624)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1434)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:501)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1594)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1349)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:234)
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:146)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
	at org.eclipse.jetty.server.Server.handle(Server.java:516)
	at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:400)
	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:645)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:392)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:277)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
	at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:338)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:315)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:173)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:131)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:409)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:883)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1034)
	at java.lang.Thread.run(Thread.java:838)
Caused by: java.util.concurrent.RejectedExecutionException: java.util.concurrent.RejectedExecutionException: Thread limit exceeded replacing blocked worker
	at sun.reflect.GeneratedConstructorAccessor75.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:593)
	at java.util.concurrent.ForkJoinTask.reportException(ForkJoinTask.java:677)
	at java.util.concurrent.ForkJoinTask.join(ForkJoinTask.java:720)
	at com.sap.sailing.domain.orc.impl.ORCPerformanceCurveByImpliedWindRankingMetric.getRankingInfo(ORCPerformanceCurveByImpliedWindRankingMetric.java:656)
	at com.sap.sailing.domain.orc.impl.ORCPerformanceCurveByImpliedWindRankingMetric.getRankingInfo(ORCPerformanceCurveByImpliedWindRankingMetric.java:1)
	at com.sap.sailing.domain.leaderboard.impl.AbstractLeaderboardWithCache.lambda$4(AbstractLeaderboardWithCache.java:528)
	at java.util.HashMap.computeIfAbsent(HashMap.java:1128)
	at com.sap.sailing.domain.leaderboard.impl.AbstractLeaderboardWithCache.lambda$3(AbstractLeaderboardWithCache.java:525)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:182)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:295)
	at com.sap.sse.util.impl.ThreadPoolAwareRunnableScheduledFutureDelegate.run(ThreadPoolAwareRunnableScheduledFutureDelegate.java:25)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	... 1 more
Caused by: java.util.concurrent.RejectedExecutionException: Thread limit exceeded replacing blocked worker
	at java.util.concurrent.ForkJoinPool.tryCompensate(ForkJoinPool.java:2022)
	at java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3321)
	at com.sap.sailing.domain.leaderboard.caching.LeaderboardDTOCalculationReuseCache.getRelativeCorrectedTime(LeaderboardDTOCalculationReuseCache.java:345)
	at com.sap.sailing.domain.orc.impl.ORCPerformanceCurveRankingMetric.lambda$7(ORCPerformanceCurveRankingMetric.java:145)
	at java.util.concurrent.ForkJoinTask$AdaptedCallable.exec(ForkJoinTask.java:1424)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.tryRemoveAndExec(ForkJoinPool.java:1118)
	at java.util.concurrent.ForkJoinPool.awaitJoin(ForkJoinPool.java:2057)
	at java.util.concurrent.ForkJoinTask.doJoin(ForkJoinTask.java:390)
	at java.util.concurrent.ForkJoinTask.join(ForkJoinTask.java:719)
	at com.sap.sailing.domain.orc.impl.ORCPerformanceCurveRankingMetric.getRelativeCorrectedTimesByCompetitor(ORCPerformanceCurveRankingMetric.java:149)
	at com.sap.sailing.domain.orc.impl.ORCPerformanceCurveRankingMetric.getRaceRankingComparator(ORCPerformanceCurveRankingMetric.java:59)
	at com.sap.sailing.domain.ranking.RankingMetric.getRaceRankingComparator(RankingMetric.java:159)
	at com.sap.sailing.domain.orc.impl.ORCPerformanceCurveRankingMetricLeaderForBaseline.getBaseLineCompetitorForAbsoluteCorrectedTimes(ORCPerformanceCurveRankingMetricLeaderForBaseline.java:47)
	at com.sap.sailing.domain.orc.impl.ORCPerformanceCurveRankingMetric.getCorrectedTime(ORCPerformanceCurveRankingMetric.java:177)
	at com.sap.sailing.domain.orc.impl.ORCPerformanceCurveByImpliedWindRankingMetric.lambda$15(ORCPerformanceCurveByImpliedWindRankingMetric.java:643)
	at java.util.concurrent.ForkJoinTask$AdaptedCallable.exec(ForkJoinTask.java:1424)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1067)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1703)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:172)

**Comment by aksajhfduwafe** [comment]
**@FinnHuelsbusch** commented:

The first observation was made on https://tractrac.sapsailing.com/gwt/Home.html#/regatta/leaderboard/:eventId=4e5c7f2e-a088-44aa-b100-c7cd09bf330b&regattaId=ORC%20Europeans%202021%20-%20ORC%20C 
when opening the race details. After loading the details, the column of the selected race is empty except for one rank. Regardless of what is to be displayed in the details.

**Comment by aksajhfduwafe** [comment]
**@axeluhl** commented:

The problem seems to be that in the "common" ForkJoinPool the maximum number of threads created to "compensate" for potential blocking inside a ManagedBlocker is limited to 256. For other ForkJoinPool instances the limit is 2^16 (65536) "compensation" threads.

I currently see two possible approaches to fix this problem:
 1) We catch the RejectedExecutionException and try again a little later
 2) We use a dedicated ForkJoinPool with 256 times the number of compensation threads which should hopefully carry us through even the largest leaderboard calculations

**Comment by aksajhfduwafe** [comment]
**@axeluhl** commented:

The ForkJoinPool.tryCompensate method keeps returning false for the following case:

            if (nbusy != (tc << 1) || ctl != c)
                canBlock = false;                 // unstable or stale

Based on the comment this suggests the pool has become "unstable or stale", whatever this means. It leads to an endless loop because the pool doesn't recover and hence never actually runs the ManagedBlocker's block(...) method. It almost seems as if the ForkJoinPool implementation was inconsistent.

Can we use something else instead?
