### ISSUE TITLE
Get an NullPointerException from the SpectatorView

### ISSUE THREAD

**Issue by aksajhfduwafe** [aksajhfduwafe/bugzilla-to-github-issues-test#667]
| Field | Value |
|---|---|
| **Reporter** | Marcus Kammer (`marcus.kammer@sap.com`) |
| **Assignee** | @axeluhl |
| **Product** | Sailing Race Analytics |
| **Component** | Sailing Simulator |
| **Version** | unspecified |
| **Hardware** | Macintosh |
| **OS** | Mac OS |
| **Severity** | normal |
| **Priority** | P3 |
| **Created** | 2012-05-24T11:20:12Z |
| **Original Bug** | [Bug 667](https://bugzilla.sapsailing.com/bugzilla/show_bug.cgi?id=667) |

---

When i browse to the spectator view from the raceboard view, and there are no races to choose, i get an nullpointerexception. But i see different input fields to search for Events, and that makes no sense.

11:00:57.794 [ERROR] [com.sap.sailing.gwt.ui.Spectator] Uncaught exception escaped

java.lang.NullPointerException: null
    at com.sap.sailing.gwt.ui.shared.RaceColumnDTO.getPlaces(RaceColumnDTO.java:98)
    at com.sap.sailing.gwt.ui.shared.LeaderboardDTO.getPlaces(LeaderboardDTO.java:443)
    at com.sap.sailing.gwt.ui.shared.LeaderboardGroupDTO.getGroupPlaces(LeaderboardGroupDTO.java:79)
    at com.sap.sailing.gwt.ui.spectator.LeaderboardGroupOverviewPanel$6.getValue(LeaderboardGroupOverviewPanel.java:210)
    at com.sap.sailing.gwt.ui.spectator.LeaderboardGroupOverviewPanel$6.getValue(LeaderboardGroupOverviewPanel.java:1)
    at com.google.gwt.user.cellview.client.Column.render(Column.java:150)
    at com.google.gwt.user.cellview.client.AbstractCellTable.renderRowValues(AbstractCellTable.java:1286)
    at com.google.gwt.user.cellview.client.AbstractHasData$View.render(AbstractHasData.java:82)
    at com.google.gwt.user.cellview.client.HasDataPresenter.resolvePendingState(HasDataPresenter.java:1369)
    at com.google.gwt.user.cellview.client.HasDataPresenter.access$3(HasDataPresenter.java:1130)
    at com.google.gwt.user.cellview.client.HasDataPresenter$2.execute(HasDataPresenter.java:1055)
    at com.google.gwt.core.client.impl.SchedulerImpl$Task$.executeScheduled$(SchedulerImpl.java:50)
    at com.google.gwt.core.client.impl.SchedulerImpl.runScheduledTasks(SchedulerImpl.java:228)
    at com.google.gwt.core.client.impl.SchedulerImpl.flushFinallyCommands(SchedulerImpl.java:327)
    at com.google.gwt.core.client.impl.Impl.exit(Impl.java:237)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at com.google.gwt.dev.shell.ModuleSpace.onLoad(ModuleSpace.java:409)
    at com.google.gwt.dev.shell.OophmSessionHandler.loadModule(OophmSessionHandler.java:200)
    at com.google.gwt.dev.shell.BrowserChannelServer.processConnection(BrowserChannelServer.java:525)
    at com.google.gwt.dev.shell.BrowserChannelServer.run(BrowserChannelServer.java:363)
    at java.lang.Thread.run(Thread.java:680)

**Comment by aksajhfduwafe** [comment]
**@axeluhl** commented:

Can reproduce by loading three opti races, adding them to a leaderboard, then going to one of their race boards and then from there, using the "Home" link/anchor, try to jump to the Spectator.html overview.
