### ISSUE TITLE
NPE in conjunction with reverse geocoder

### ISSUE THREAD

**Issue by aksajhfduwafe** [aksajhfduwafe/bugzilla-to-github-issues-test#680]
| Field | Value |
|---|---|
| **Reporter** | @axeluhl |
| **Assignee** | @axeluhl |
| **Product** | Sailing Race Analytics |
| **Component** | Server |
| **Version** | unspecified |
| **Hardware** | All |
| **OS** | All |
| **Severity** | normal |
| **Priority** | P1 |
| **Created** | 2012-05-26T19:44:16Z |
| **Original Bug** | [Bug 680](https://bugzilla.sapsailing.com/bugzilla/show_bug.cgi?id=680) |

---

com.google.gwt.user.server.rpc.UnexpectedException: Service method 'public abstract com.sap.sailing.gwt.ui.shared.Leader
boardGroupDTO com.sap.sailing.gwt.ui.client.SailingService.getLeaderboardGroupByName(java.lang.String)' threw an unexpec
ted exception: java.lang.NullPointerException
        at com.google.gwt.user.server.rpc.RPC.encodeResponseForFailure(RPC.java:385)
        at com.google.gwt.user.server.rpc.RPC.invokeAndEncodeResponse(RPC.java:588)
        at com.google.gwt.user.server.rpc.RemoteServiceServlet.processCall(RemoteServiceServlet.java:208)
        at com.google.gwt.user.server.rpc.RemoteServiceServlet.processPost(RemoteServiceServlet.java:248)
        at com.google.gwt.user.server.rpc.AbstractRemoteServiceServlet.doPost(AbstractRemoteServiceServlet.java:62)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:547)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:480)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:119)
        at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:483)
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:227)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:941)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:409)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:186)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:875)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:117)
        at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:250)
        at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:149)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:110)
        at org.eclipse.jetty.server.Server.handle(Server.java:349)
        at org.eclipse.jetty.server.HttpConnection.handleRequest(HttpConnection.java:441)
        at org.eclipse.jetty.server.HttpConnection$RequestHandler.content(HttpConnection.java:936)
        at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:801)
        at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:224)
        at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:51)
        at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:586)
        at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:44)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:598)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:533)
        at java.lang.Thread.run(Thread.java:722)
Caused by: java.lang.NullPointerException
        at com.sap.sailing.domain.common.quadtree.impl.QuadTreeNode.put(QuadTreeNode.java:207)
                at com.sap.sailing.domain.common.quadtree.impl.QuadTreeNode.put(QuadTreeNode.java:169)
        at com.sap.sailing.domain.common.quadtree.QuadTree.put(QuadTree.java:69)
        at com.sap.sailing.geocoding.impl.ReverseGeocoderImpl.cachePlacemarks(ReverseGeocoderImpl.java:197)
        at com.sap.sailing.geocoding.impl.ReverseGeocoderImpl.getPlacemarkNearest(ReverseGeocoderImpl.java:62)
        at com.sap.sailing.gwt.ui.server.SailingServiceImpl.getStartFinishPlacemarksForTrackedRace(SailingServiceImpl.java:1294)
        at com.sap.sailing.gwt.ui.server.SailingServiceImpl.getRacePlaces(SailingServiceImpl.java:1267)
        at com.sap.sailing.gwt.ui.server.SailingServiceImpl.createStrippedLeaderboardDTO(SailingServiceImpl.java:1250)
        at com.sap.sailing.gwt.ui.server.SailingServiceImpl.convertToLeaderboardGroupDTO(SailingServiceImpl.java:1775)
        at com.sap.sailing.gwt.ui.server.SailingServiceImpl.getLeaderboardGroupByName(SailingServiceImpl.java:1767)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:601)
        at com.google.gwt.user.server.rpc.RPC.invokeAndEncodeResponse(RPC.java:569)
        ... 29 more

**Comment by aksajhfduwafe** [comment]
**@axeluhl** commented:

*** #682 has been marked as a duplicate of this bug. ***

**Comment by aksajhfduwafe** [comment]
**@axeluhl** commented:

Re-occurred, see 682. We obviously need to take care of this. Try to come up with a reproduction scenario first.

**Comment by aksajhfduwafe** [comment]
**@axeluhl** commented:

Analysis: the problem is not, as previously assumed, a null entry passed to the put(...) method but rather a null firstPoint attribute. This, in turn, only seems possible to explain by a race condition. Otherwise, there is a check for item.size(). If 1, meaning the item collection was previously empty, firstPoint will be set. The access to the null-values firstPoint, however, happens in the "else" branch, meaning that item.size() was at least 2 at the time the if/else was decided. However, with concurrency, it's well possible that firstPoint hasn't been set.

Generally, QuadTree is not thread safe. Clients must synchronize their calls.

I will try to reproduce the issue by running two threads which keep trying to insert one value each which should lead to the same issue. Then, the next step should be to show that with synchronization the problem doesn't occur anymore.

**Comment by aksajhfduwafe** [comment]
**@axeluhl** commented:

Fixed by d62a42079b3bb6900d50d0597c1a1bc3a6bf7e52. Can re-enable use of placemarks in stripped leaderboard group again.

**Comment by aksajhfduwafe** [comment]
*@axeluhl* changed status from **REOPENED** to **RESOLVED** (FIXED)

**Comment by aksajhfduwafe** [comment]
*Subscribing participants (reporter + CC):*

@LennartH
