### ISSUE TITLE
Get ClassCastException calling the Raceboard

### ISSUE THREAD

**Issue by aksajhfduwafe** [aksajhfduwafe/bugzilla-to-github-issues-test#733]
| Field | Value |
|---|---|
| **Reporter** | Marcus Kammer (`marcus.kammer@sap.com`) |
| **Assignee** | @axeluhl |
| **Product** | Sailing Race Analytics |
| **Component** | Leaderboard |
| **Version** | unspecified |
| **Hardware** | Macintosh |
| **OS** | Mac OS |
| **Severity** | normal |
| **Priority** | P3 |
| **CC (unmapped)** | Timur Menekse (`t.menekse@sap.com`) |
| **Created** | 2012-06-06T14:44:11Z |
| **Original Bug** | [Bug 732](https://bugzilla.sapsailing.com/bugzilla/show_bug.cgi?id=732) |

---

14:39:31.154 [ERROR] [com.sap.sailing.gwt.ui.RaceBoard] Uncaught exception escaped

java.lang.ClassCastException: com.google.gwt.dev.shell.JavaLong cannot be cast to com.google.gwt.dom.client.Style
    at com.google.gwt.dom.client.Element$.getStyle$(Element.java)
    at com.google.gwt.user.client.DOM.setStyleAttribute(DOM.java:1240)
    at com.sap.sailing.gwt.ui.shared.controls.slider.TimeSlider.drawTicks(TimeSlider.java:69)
    at com.sap.sailing.gwt.ui.shared.controls.slider.SliderBar.onResize(SliderBar.java:616)
    at com.sap.sailing.gwt.ui.shared.controls.slider.SliderBar.redraw(SliderBar.java:629)
    at com.sap.sailing.gwt.ui.client.RaceTimePanel.redrawAllMarkers(RaceTimePanel.java:233)
    at com.sap.sailing.gwt.ui.client.RaceTimePanel.updateLegMarkers(RaceTimePanel.java:218)
    at com.sap.sailing.gwt.ui.client.RaceTimePanel.updateTimeInfo(RaceTimePanel.java:76)
    at com.sap.sailing.gwt.ui.client.RaceTimePanel.raceTimesInfosReceived(RaceTimePanel.java:238)
    at com.sap.sailing.gwt.ui.client.RaceTimesInfoProvider$3.onSuccess(RaceTimesInfoProvider.java:172)
    at com.sap.sailing.gwt.ui.client.RaceTimesInfoProvider$3.onSuccess(RaceTimesInfoProvider.java:1)
    at com.google.gwt.user.client.rpc.impl.RequestCallbackAdapter.onResponseReceived(RequestCallbackAdapter.java:232)
    at com.google.gwt.http.client.Request.fireOnResponseReceived(Request.java:287)
    at com.google.gwt.http.client.RequestBuilder$1.onReadyStateChange(RequestBuilder.java:395)
    at sun.reflect.GeneratedMethodAccessor153.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at com.google.gwt.dev.shell.MethodAdaptor.invoke(MethodAdaptor.java:103)
    at com.google.gwt.dev.shell.MethodDispatch.invoke(MethodDispatch.java:71)
    at com.google.gwt.dev.shell.OophmSessionHandler.invoke(OophmSessionHandler.java:172)
    at com.google.gwt.dev.shell.BrowserChannelServer.reactToMessagesWhileWaitingForReturn(BrowserChannelServer.java:337)
    at com.google.gwt.dev.shell.BrowserChannelServer.invokeJavascript(BrowserChannelServer.java:218)
    at com.google.gwt.dev.shell.ModuleSpaceOOPHM.doInvoke(ModuleSpaceOOPHM.java:136)
    at com.google.gwt.dev.shell.ModuleSpace.invokeNative(ModuleSpace.java:561)
    at com.google.gwt.dev.shell.ModuleSpace.invokeNativeObject(ModuleSpace.java:269)
    at com.google.gwt.dev.shell.JavaScriptHost.invokeNativeObject(JavaScriptHost.java:91)
    at com.google.gwt.core.client.impl.Impl.apply(Impl.java)
    at com.google.gwt.core.client.impl.Impl.entry0(Impl.java:213)
    at sun.reflect.GeneratedMethodAccessor152.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at com.google.gwt.dev.shell.MethodAdaptor.invoke(MethodAdaptor.java:103)
    at com.google.gwt.dev.shell.MethodDispatch.invoke(MethodDispatch.java:71)
    at com.google.gwt.dev.shell.OophmSessionHandler.invoke(OophmSessionHandler.java:172)
    at com.google.gwt.dev.shell.BrowserChannelServer.reactToMessages(BrowserChannelServer.java:292)
    at com.google.gwt.dev.shell.BrowserChannelServer.processConnection(BrowserChannelServer.java:546)
    at com.google.gwt.dev.shell.BrowserChannelServer.run(BrowserChannelServer.java:363)
    at java.lang.Thread.run(Thread.java:680)

commit: master c21ea5dae25db9502654af04560bf8312c160321

**Comment by aksajhfduwafe** [comment]
**@axeluhl** commented:

Hasn't occured in years. Resolving as WORKSFORME.
