### ISSUE TITLE
TestStoringAndLoadingEventsAndRegattas broken in central build

### ISSUE THREAD

**Issue by aksajhfduwafe** [aksajhfduwafe/bugzilla-to-github-issues-test#736]
| Field | Value |
|---|---|
| **Reporter** | @axeluhl |
| **Assignee** | @axeluhl |
| **Product** | Sailing Race Analytics |
| **Component** | Server |
| **Version** | unspecified |
| **Hardware** | All |
| **OS** | All |
| **Severity** | normal |
| **Priority** | P2 |
| **Created** | 2012-06-07T18:30:03Z |
| **Original Bug** | [Bug 736](https://bugzilla.sapsailing.com/bugzilla/show_bug.cgi?id=736) |

---

When executing the test locally it works just fine. Could this be a race condition? Could it depend on how MongoDB makes the results of the dropDatabase() that is executed in the test's setUp() visible to its clients?

The trace as copied from the server build log:

Running com.sap.sailing.mongodb.test.TestStoringAndLoadingEventsAndRegattas
Jun 07, 2012 5:23:07 PM com.sap.sailing.mongodb.internal.MongoDBServiceImpl setConfiguration
INFO: Used Mongo configuration: host:port/DBName: 127.0.0.1:27017/winddbTest
Jun 07, 2012 5:23:07 PM com.sap.sailing.mongodb.internal.MongoDBServiceImpl setConfiguration
INFO: Used Mongo configuration: host:port/DBName: 127.0.0.1:27017/winddbTest
Jun 07, 2012 5:23:07 PM com.sap.sailing.server.impl.RacingEventServiceImpl createRegatta
INFO: Created regatta Kieler Woche (29erXX) (1096457097)
Jun 07, 2012 5:23:07 PM com.sap.sailing.mongodb.internal.MongoDBServiceImpl setConfiguration
INFO: Used Mongo configuration: host:port/DBName: 127.0.0.1:27017/winddbTest
Jun 07, 2012 5:23:07 PM com.sap.sailing.server.impl.RacingEventServiceImpl createRegatta
INFO: Created regatta Kieler Woche (29erXX) (546826245)
Jun 07, 2012 5:23:07 PM com.sap.sailing.mongodb.internal.MongoDBServiceImpl setConfiguration
INFO: Used Mongo configuration: host:port/DBName: 127.0.0.1:27017/winddbTest
Jun 07, 2012 5:23:07 PM com.sap.sailing.mongodb.internal.MongoDBServiceImpl setConfiguration
INFO: Used Mongo configuration: host:port/DBName: 127.0.0.1:27017/winddbTest
Jun 07, 2012 5:23:07 PM com.sap.sailing.mongodb.internal.MongoDBServiceImpl setConfiguration
INFO: Used Mongo configuration: host:port/DBName: 127.0.0.1:27017/winddbTest
Tests run: 6, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.121 sec <<< FAILURE!
testLoadStoreRegattaLeaderboardWithScoreCorrections(com.sap.sailing.mongodb.test.TestStoringAndLoadingEventsAndRegattas)
  Time elapsed: 0.02 sec  <<< ERROR!
java.lang.IllegalArgumentException: Leaderboard with name Kieler Woche (29erXX) already exists
        at com.sap.sailing.server.impl.RacingEventServiceImpl.addRegattaLeaderboard(RacingEventServiceImpl.java:272)
        at com.sap.sailing.mongodb.test.TestStoringAndLoadingEventsAndRegattas.testLoadStoreRegattaLeaderboardWithScoreCorrections(TestStoringAndLoadingEventsAndRegattas.java:136)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:601)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:44)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:41)
        at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
        at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:28)
        at org.junit.runners.BlockJUnit4ClassRunner.runNotIgnored(BlockJUnit4ClassRunner.java:79)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:71)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:49)
                at org.junit.runners.ParentRunner$3.run(ParentRunner.java:193)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:52)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:191)
        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:42)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:184)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:236)
        at org.apache.maven.surefire.junit4.JUnit4TestSet.execute(JUnit4TestSet.java:62)
        at org.apache.maven.surefire.suite.AbstractDirectoryTestSuite.executeTestSet(AbstractDirectoryTestSuite.java:140)
        at org.apache.maven.surefire.suite.AbstractDirectoryTestSuite.execute(AbstractDirectoryTestSuite.java:127)
        at org.apache.maven.surefire.Surefire.run(Surefire.java:177)
        at org.eclipse.tycho.surefire.osgibooter.OsgiSurefireBooter.run(OsgiSurefireBooter.java:72)
        at org.eclipse.tycho.surefire.osgibooter.HeadlessTestApplication.run(HeadlessTestApplication.java:21)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:601)
        at org.eclipse.equinox.internal.app.EclipseAppContainer.callMethodWithException(EclipseAppContainer.java:587)
        at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:198)
        at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:110)
        at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:79)
        at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:344)
        at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:179)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:601)
        at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:622)
        at org.eclipse.equinox.launcher.Main.basicRun(Main.java:577)
        at org.eclipse.equinox.launcher.Main.run(Main.java:1410)
        at org.eclipse.equinox.launcher.Main.main(Main.java:1386)

**Comment by aksajhfduwafe** [comment]
**@axeluhl** commented:

When after an otherwise successful build doing an "mvn install" in the com.sap.sailing.mongodb.test bundle, the tests fail. If adjusting the pom.xml such that remote debugging is possible, then when stepping through the leaderboard creation the exceptions don't occur and the test succeeds. This again suggest some sort of race condition, probably in conjunction with the sailing.server bundle activator which creates a RacingEventServiceImpl instance which loads its state from the database. Analyze closer!

**Comment by aksajhfduwafe** [comment]
**@axeluhl** commented:

The build / test even succeeds on the server if not setting any breakpoints in the remote debugging session. An even closer race condition, it seems...

**Comment by aksajhfduwafe** [comment]
**@axeluhl** commented:

Again a MongoDB timing problem, "solved" by adding explicit DBCollection.drop() calls for the collections affected.

**Comment by aksajhfduwafe** [comment]
*@axeluhl* changed status from **ASSIGNED** to **RESOLVED** (FIXED)
