### ISSUE TITLE
Exception in Testserver (Kieler Woche 2012) Live race tracking

### ISSUE THREAD

**Issue by aksajhfduwafe** [aksajhfduwafe/bugzilla-to-github-issues-test#784]
| Field | Value |
|---|---|
| **Reporter** | @fmittag |
| **Assignee** | @axeluhl |
| **Product** | Sailing Race Analytics |
| **Component** | Server |
| **Version** | unspecified |
| **Hardware** | PC |
| **OS** | Windows |
| **Severity** | enhancement |
| **Priority** | P5 |
| **Created** | 2012-06-16T13:20:23Z |
| **Original Bug** | [Bug 784](https://bugzilla.sapsailing.com/bugzilla/show_bug.cgi?id=784) |

---

java.lang.NumberFormatException: For input string: ""
        at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
        at java.lang.Long.parseLong(Long.java:453)
        at java.lang.Long.parseLong(Long.java:483)
        at java.text.DigitList.getLong(DigitList.java:194)
        at java.text.DecimalFormat.parse(DecimalFormat.java:1316)
        at java.text.SimpleDateFormat.subParse(SimpleDateFormat.java:2089)
        at java.text.SimpleDateFormat.parse(SimpleDateFormat.java:1455)
        at java.text.DateFormat.parse(DateFormat.java:355)
        at com.sap.sailing.declination.impl.DeclinationStore.readExternal(DeclinationStore.java:89)
        at com.sap.sailing.declination.impl.DeclinationStore.getStoredDeclinations(DeclinationStore.java:51)
        at com.sap.sailing.declination.impl.DeclinationServiceImpl.getYearStore(DeclinationServiceImpl.java:105)
        at com.sap.sailing.declination.impl.DeclinationServiceImpl.getDeclination(DeclinationServiceImpl.java:59)
        at com.sap.sailing.declination.impl.DeclinationServiceImpl.getDeclination(DeclinationServiceImpl.java:46)
        at com.sap.sailing.expeditionconnector.ExpeditionWindTracker.received(ExpeditionWindTracker.java:87)
        at com.sap.sailing.expeditionconnector.ExpeditionWindTracker.received(ExpeditionWindTracker.java:1)
        at com.sap.sailing.udpconnector.UDPReceiver$ToListenerDispatcher.run(UDPReceiver.java:64)

**Comment by aksajhfduwafe** [comment]
*@axeluhl* changed status from **NEW** to **RESOLVED** (WORKSFORME)
