### ISSUE TITLE
Concurrent modification exception (Kieler Woche 2012)

### ISSUE THREAD

**Issue by aksajhfduwafe** [aksajhfduwafe/bugzilla-to-github-issues-test#796]
| Field | Value |
|---|---|
| **Reporter** | @fmittag |
| **Assignee** | @axeluhl |
| **Product** | Sailing Race Analytics |
| **Component** | Server |
| **Version** | unspecified |
| **Hardware** | PC |
| **OS** | Windows |
| **Severity** | enhancement |
| **Priority** | P5 |
| **Created** | 2012-06-19T17:29:22Z |
| **Original Bug** | [Bug 796](https://bugzilla.sapsailing.com/bugzilla/show_bug.cgi?id=796) |

---

In the lastest version the following exception occured:

Caused by: java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:819)
	at java.util.ArrayList$Itr.next(ArrayList.java:791)
	at com.sap.sailing.gwt.ui.server.SailingServiceImpl.convertToLeaderboardGroupDTO(SailingServiceImpl.java:1917)
	at com.sap.sailing.gwt.ui.server.SailingServiceImpl.getLeaderboardGroupByName(SailingServiceImpl.java:1910)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:601)
	at com.google.gwt.user.server.rpc.RPC.invokeAndEncodeResponse(RPC.java:569)
	... 29 more

**Comment by aksajhfduwafe** [comment]
**@axeluhl** commented:

Fixed by commit 0d35aa348cc59305609f60265cbf2519dd3a2114
