### ISSUE TITLE
Potential deadlock?

### ISSUE THREAD

**Issue by aksajhfduwafe** [aksajhfduwafe/bugzilla-to-github-issues-test#964]
| Field | Value |
|---|---|
| **Reporter** | @axeluhl |
| **Assignee** | @axeluhl |
| **Product** | Sailing Race Analytics |
| **Component** | Server |
| **Version** | unspecified |
| **Hardware** | All |
| **OS** | All |
| **Severity** | normal |
| **Priority** | P1 |
| **Created** | 2012-09-14T18:43:39Z |
| **Original Bug** | [Bug 964](https://bugzilla.sapsailing.com/bugzilla/show_bug.cgi?id=964) |

---

Sep 14, 2012 6:23:03 PM com.sap.sailing.util.impl.LockUtil lock
INFO: Couldn't acquire lock writeLock competitor rankings for race Gold fleet - race 7 for time point 2012-09-14T18:22:32.924+0200 in 5s at java.lang.Throwable: This is where the l
ock interaction happened
        at com.sap.sailing.util.impl.LockUtil.getCurrentStackTrace(LockUtil.java:87)
        at com.sap.sailing.util.impl.LockUtil.lock(LockUtil.java:37)
        at com.sap.sailing.util.impl.LockUtil.lockForWrite(LockUtil.java:60)
        at com.sap.sailing.domain.tracking.impl.TrackedRaceImpl.getCompetitorsFromBestToWorst(TrackedRaceImpl.java:835)
        at com.sap.sailing.domain.tracking.impl.TrackedRaceImpl.getRank(TrackedRaceImpl.java:805)
        at com.sap.sailing.domain.leaderboard.impl.AbstractLeaderboardImpl.getTrackedRank(AbstractLeaderboardImpl.java:106)
        at com.sap.sailing.domain.leaderboard.impl.AbstractSimpleLeaderboardImpl$1.call(AbstractSimpleLeaderboardImpl.java:198)
        at com.sap.sailing.domain.leaderboard.impl.AbstractSimpleLeaderboardImpl$1.call(AbstractSimpleLeaderboardImpl.java:1)
        at com.sap.sailing.domain.leaderboard.impl.ScoreCorrectionImpl.getCorrectedNonMaxedScore(ScoreCorrectionImpl.java:220)
        at com.sap.sailing.domain.leaderboard.impl.ScoreCorrectionImpl.getCorrectedScore(ScoreCorrectionImpl.java:157)
        at com.sap.sailing.domain.leaderboard.impl.AbstractSimpleLeaderboardImpl.getNetPoints(AbstractSimpleLeaderboardImpl.java:195)
        at com.sap.sailing.domain.leaderboard.impl.ResultDiscardingRuleImpl$1.compare(ResultDiscardingRuleImpl.java:68)
        at com.sap.sailing.domain.leaderboard.impl.ResultDiscardingRuleImpl$1.compare(ResultDiscardingRuleImpl.java:1)
        at java.util.TimSort.binarySort(TimSort.java:265)
        at java.util.TimSort.sort(TimSort.java:190)
        at java.util.TimSort.sort(TimSort.java:173)
        at java.util.Arrays.sort(Arrays.java:659)
        at java.util.Collections.sort(Collections.java:217)
        at com.sap.sailing.domain.leaderboard.impl.ResultDiscardingRuleImpl.getDiscardedRaceColumns(ResultDiscardingRuleImpl.java:80)
        at com.sap.sailing.domain.leaderboard.impl.AbstractSimpleLeaderboardImpl.isDiscarded(AbstractSimpleLeaderboardImpl.java:212)
        at com.sap.sailing.domain.leaderboard.impl.AbstractSimpleLeaderboardImpl.getTotalPoints(AbstractSimpleLeaderboardImpl.java:219)
        at com.sap.sailing.domain.leaderboard.impl.LeaderboardTotalRankComparator.<init>(LeaderboardTotalRankComparator.java:63)
        at com.sap.sailing.domain.leaderboard.impl.AbstractSimpleLeaderboardImpl.getTotalRankComparator(AbstractSimpleLeaderboardImpl.java:302)
        at com.sap.sailing.domain.leaderboard.impl.AbstractSimpleLeaderboardImpl.getCompetitorsFromBestToWorst(AbstractSimpleLeaderboardImpl.java:297)
        at com.sap.sailing.server.impl.LeaderboardJsonExportServlet.doGet(LeaderboardJsonExportServlet.java:51)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:547)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:480)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:119)
        at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:483)
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:227)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:941)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:409)
                at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:186)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:875)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:117)
        at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:250)
        at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:149)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:110)
        at org.eclipse.jetty.server.Server.handle(Server.java:345)
        at org.eclipse.jetty.server.HttpConnection.handleRequest(HttpConnection.java:441)
        at org.eclipse.jetty.server.HttpConnection$RequestHandler.headerComplete(HttpConnection.java:919)
        at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:582)
        at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:218)
        at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:51)
        at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:586)
        at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:44)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:598)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:533)
        at java.lang.Thread.run(Thread.java:722)

**Comment by aksajhfduwafe** [comment]
**@axeluhl** commented:

Here's a log obtained during a debug session, after adding enhanced lock tracing:

Trying again...
Oct 02, 2012 12:42:01 PM com.sap.sailing.util.impl.LockUtil lock
INFO: Couldn't acquire lock writeLock VirtualWindTrackImpl for race Gold fleet - race 3 in 5s at java.lang.Thread.getStackTrace(Thread.java:1567)
com.sap.sailing.util.impl.LockUtil.getStackTrace(LockUtil.java:107)
com.sap.sailing.util.impl.LockUtil.getCurrentStackTrace(LockUtil.java:115)
com.sap.sailing.util.impl.LockUtil.lock(LockUtil.java:39)
com.sap.sailing.util.impl.LockUtil.lockForWrite(LockUtil.java:80)
com.sap.sailing.domain.tracking.impl.TrackImpl.lockForWrite(TrackImpl.java:75)
com.sap.sailing.domain.tracking.impl.TrackBasedEstimationWindTrackImpl.scheduleCacheRefresh(TrackBasedEstimationWindTrackImpl.java:264)
com.sap.sailing.domain.tracking.impl.TrackBasedEstimationWindTrackImpl.buoyPositionChanged(TrackBasedEstimationWindTrackImpl.java:544)
com.sap.sailing.domain.tracking.impl.DynamicTrackedRaceImpl.notifyListeners(DynamicTrackedRaceImpl.java:256)
com.sap.sailing.domain.tracking.impl.DynamicTrackedRaceImpl.access$4(DynamicTrackedRaceImpl.java:249)
com.sap.sailing.domain.tracking.impl.DynamicTrackedRaceImpl$1.gpsFixReceived(DynamicTrackedRaceImpl.java:170)
com.sap.sailing.domain.tracking.impl.DynamicTrackedRaceImpl$1.gpsFixReceived(DynamicTrackedRaceImpl.java:1)
com.sap.sailing.domain.tracking.impl.DynamicTrackImpl.addGPSFix(DynamicTrackImpl.java:49)
com.sap.sailing.domain.tracking.impl.DynamicGPSFixTrackImpl.addGPSFix(DynamicGPSFixTrackImpl.java:14)
com.sap.sailing.domain.tractracadapter.impl.TracTracRaceTrackerImpl$1.run(TracTracRaceTrackerImpl.java:257)
java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
java.util.concurrent.FutureTask$Sync.innerRunAndReset(FutureTask.java:351)
java.util.concurrent.FutureTask.runAndReset(FutureTask.java:178)
java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:178)
java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603)
java.lang.Thread.run(Thread.java:722)

The current readers are:
Thread[pool-72-thread-1,5,main]
sun.misc.Unsafe.park(Native Method)
java.util.concurrent.locks.LockSupport.park(LockSupport.java:186)
java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2043)
java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442)
java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1043)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1103)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603)
java.lang.Thread.run(Thread.java:722)

This suggests that thread "Thread[pool-72-thread-1,5,main]" has returned to its thread pool loop but for some reason is still considered to hold a read lock. This would in turn suggest that either a "finally" clause is missing or that there is a bug (-XX:UseMembar ???) in the VM implementation that doesn't properly release the lock. But then again, if we still have the reader thread in our lock's tracing structure, it rather seems the unlock statement wasn't executed than there being a VM bug...

**Comment by aksajhfduwafe** [comment]
**@axeluhl** commented:

Resolving this as fixed. Understood the effect of read vs. read locks in case a writer is waiting on a fair ReentrantReadWriteLock. Several potential deadlocks were avoided by the commits at and before db57bdc6eba48e66ee2ea65b9fae6f8c19cb8ebc.
